### ISSUE TITLE
BEAST 2.6.6 Apps fail to launch under MacOS Big Sur

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#1003]
I have the following JVMs installed (output of `/usr/libexec/java_home -V`):
```
Matching Java Virtual Machines (2):
    17 (x86_64) "Eclipse Temurin" - "Eclipse Temurin 17" /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
    1.8.0_302 (x86_64) "Eclipse Temurin" - "Eclipse Temurin 8" /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home
/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
```
but opening BEAST.app from the 2.6.6 release (no bundled JVM) yields:
![Screenshot 2021-09-24 at 11 47 39](https://user-images.githubusercontent.com/512538/134654992-9ff0380a-d27a-4acd-b210-90fc37c1887f.png)
After some burrowing, it seems the problem is with the version of `universalJavaApplicationStub` which we're using to launch the apps.  Specifically, this is due to [this issue](https://github.com/tofi86/universalJavaApplicationStub/issues/91), which is a parsing error due to the output format of `/usr/libexec/java_home -V` changing in Big Sur.

The [most recent release](https://github.com/tofi86/universalJavaApplicationStub/releases/tag/v3.2.0) of `universalJavaApplicationStub` solves this problem and should work for both earlier and later MacOS java_home versions.  (I can confirm that this solves the problem for Big Sur - copying the latest universalJavaApplicationStub script over the old one in the `Contents/MacOS/` directory allows the apps to launch without a problem.)

**Comment by rbouckaert** [comment]
Hi Tim, Thanks for digging into this. It sounds like this is a matter of replacing `universalJavaApplicationStub` and perhaps `universalJavaApplicationStubJRE`.

Did you try this with the BEAST version that has a jvm included? If that runs, this is an argument for only releasing BEAST with jvm only, so we do not get surprised by OS changes.

**Comment by tgvaughan** [comment]
The JRE-inclusive package does run when launched from Finder, but only when the "BEAST 2.6.6" directory is located in /Applications.  The script to launch from the command line produces the following:
```
/Applications/BEAST 2.6.6/bin $ ./beast
./beast: line 58: ./../jre1.8.0_282/bin/java: No such file or directory
```

As for the issue with the no-JRE package being an OS-related problem; it technically is, but it's mostly because univeralJavaApplicationStub had a very fragile dependence on the exact form form of the /usr/libexec/java_home output.
In fact, java_home has a command-line switch for producing XML output which is specifically meant for cases like this, and should have been used from the start.  The new version of the script does things properly and uses the XML output, so shouldn't break in the same way in future.

**Comment by rbouckaert** [comment]
Thanks for letting me know BEAST still starts when the JRE is included -- I added a note on the beast2.org site about this. Walter is preparing a release with updated `univeralJavaApplicationStub`, so hopefully that will sort out this problem.

**Comment by walterxie** [comment]
I am still struggling to upgrade my iMac to big sur. As Tim suggested, I created the new release by replacing `univeralJavaApplicationStub` to its latest released version 3.2.0. Our previous release was using 3.0.3. 

Both notarized dmg files are available from the links below, until next Monday. They were created under Catalina, but should work in Big Sur. Hi @tgvaughan and @alexeid, can you please do us a favour to test these two versions in Big Sur? Remco has a problem to upgrade his Mac as well. If any problems, please give me a screenshot:  

https://www.dropbox.com/s/wvvivej3uij47w0/BEAST.v2.6.6-macOS11.dmg?dl=0

https://www.dropbox.com/s/rnrfu0jar4yj69j/BEAST_with_JRE.v2.6.6-macOS11.dmg?dl=0

I also tested under Catalina. They could launch successfully.

<img width="626" alt="Screen Shot 2021-09-28 at 4 02 19 PM" src="https://user-images.githubusercontent.com/5743014/135015955-9d5c5743-e684-49e7-b524-5dc732033c2f.png">

<img width="1018" alt="Screen Shot 2021-09-28 at 3 35 47 PM" src="https://user-images.githubusercontent.com/5743014/135015942-a51c7b13-3345-4e67-bfce-c25d6d58ff5b.png">

**Comment by rbouckaert** [comment]
@walterxie Thanks a lot! Just confirming both releases allow starting apps by double clicking icons in the BEAST applications folder on Catelina. Also, the scripts in the bin folder in the version without JRE work fine. However, the version with JRE included assume that the JRE is in folder ../jre1.8.0_282 but the JRE includes is ../jre1.8.0_262. Would be good if you could include the 1.8.0_282 JRE instead.

**Comment by walterxie** [comment]
I will update the JRE once I get any confirmations this new release is working in Big Sur.

**Comment by walterxie** [comment]
@rbouckaert I have upgraded openjdk to 1.8.0_292, and replaced the release with jre. I have not got any confirmations whether they are working in Big Sur yet, but I will start another attempt to upgrade my iMac to Big Sur soon after backup.

**Comment by tgvaughan** [comment]
@walterxie Your updated no-JRE package works flawlessly for me on Big Sur.

On the other hand, the updated JRE-included package does not launch at all neither from the command line script nor via BEAST.app.  As Remco mentioned above, both of these problems are due to incorrect JRE directories being embedded in the bin/ scripts and universalJavaApplicationJREStub.  Fixing these by hand allows this version to work.

**Comment by walterxie** [comment]
Whoops, I updated the JRE in the last commit, but forgot to update its path in `universalJavaApplicationJREStub`. I will make a new release for with_JRE now.

**Comment by walterxie** [comment]
It should work now:

<img width="904" alt="Screen Shot 2021-09-30 at 9 46 19 AM" src="https://user-images.githubusercontent.com/5743014/135346638-c8729723-e009-4b2e-a5bd-5a0ae74d94cb.png">

**Comment by walterxie** [comment]
I will put both dmg to the GitHub release page shortly.

**Comment by rbouckaert** [comment]
Fixed by d927fae

**Comment by walterxie** [comment]
update all bash scripts

**Comment by walterxie** [comment]
create branch https://github.com/CompEvol/beast2/tree/2.6.6

**Comment by walterxie** [comment]
https://developer.apple.com/forums/thread/126901

**Comment by walterxie** [comment]
Both GUI and bash scripts are working now

**Comment by rbouckaert** [comment]
Thanks Walter. Seems related to #1008
