### ISSUE TITLE
Error with epopsize scale operator optimisation 

### ISSUE THREAD

**Issue by Wytamma** [CompEvol/beast2#1005]
I have an issue where `beast` produces different results if I run it on my local machine vs the HPC at my university. Basically the epopsize scale operator for the Coalescent Exponential Population tree prior is set to 1 by default on the HPC. Beast fails to tune from this starting value and MCMC takes tiny steps which results in a ~100% acceptance rate and poor mixing. 

I think the issue is partly because BEAUti doesn't add a default `scaleFactor` value to the xml file. If I manually set `scaleFactor="0.75"` (the default locally) then the analysis works as expected. However, this doesn't explain why it works on my local machine but not the HPC when I leave out the scaleFactor.  

The only difference I can see is that I'm using beast v2.6.6 locally and v2.6.3 of the HPC, however, I can't see anything in the change log that would explain this...

Local 
![local](https://user-images.githubusercontent.com/13726005/135089687-5941b297-532e-4355-aaae-3175aabb1130.png)

HPC
![HPC](https://user-images.githubusercontent.com/13726005/135089713-632ba27a-9959-47d5-93a2-dad26e4281e6.png)

**Comment by rbouckaert** [comment]
The default value for scale factor has changed between v2.6.3 and v2.6.6 to 0.75. BEAUti saves only values in the XML that are not default values. So, BEAUti did not save the scale factor value locally, and the BEAST on the HPC interpreted that as using the default value of 1.0. Your fix (changing the XML to set the scale factor explicitly) works, but if you could convince the HPC maintainers to use v2.6.6 it should have worked too.

**Comment by Wytamma** [comment]
Ah that makes sense! Thanks 😊 any idea why the optimisation fails when starting at 1.0? Would it just be a matter of setting a larger number of tuning steps?

**Comment by rbouckaert** [comment]
The scale operator takes a random value to scale between `scaleFactor` and `scaleFactor+(1.0 / scaleFactor) - scaleFactor)`, which works out as a range from 1.0 to 1.0 when `scaleFactor=1.0`. So, the default value of 1.0 does not allow any scaling, which is why the default value was changed. When optimising, the `scaleFactor` is set to
```
            double delta = calcDelta(logAlpha);
            delta += Math.log(1.0 / scaleFactor - 1.0);
            setCoercableParameterValue(1.0 / (Math.exp(delta) + 1.0));
```
so delta is set to positive infinity at the second line and the third line sets the scale factor to 1 (apart from some numerical noise), allowing for only very slow tuning of the scale factor.

**Comment by Wytamma** [comment]
Fantastic, thanks @rbouckaert !
