### ISSUE TITLE
TreeAnnotator CommandLine -heights option 

### ISSUE THREAD

**Issue by Lars-B** [CompEvol/beast2#1009]
When using TreeAnnotator from the command line, the option `-heights keep` does not work.
Additionally, the [default annotation](https://github.com/CompEvol/beast2/blob/7584dc92124595651e090b0d3e8b26aed49665f7/src/beast/app/treeannotator/TreeAnnotator.java#L1450) used for the MCC tree is the _Common Ancestor heights_ option and not the _Keep target heights_ option as stated within `-help`.

The following calls will all result in the exact same MCC tree (the one with _Common Ancestor heights_):

- `treeannotator test.trees out.tree`
- `treeannotator -heights ca test.trees out.tree`
- `treeannotator -heights keep test.trees out.tree`

**Comment by seidels** [comment]
I can confirm this issue.

**Comment by tgvaughan** [comment]
Thanks @Lars-B, and sorry this went so long without response.
