### ISSUE TITLE
MultiTypeTree template: tip dates issue

### ISSUE THREAD

**Issue by amymariecampbell** [CompEvol/beast2#1011]
Hi there! 

I've created an xml using the MultiTypeTree template. My analysis runs fine UNTIL I add in tip dates. Then, the analysis runs really slowly and when it gets to ~4000 steps, I get the following error: 

`java.lang.reflect.InvocationTargetException`
        `at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)`
        `at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)`
        `at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)`
        `at java.lang.reflect.Method.invoke(Method.java:498)`
        `at beast.app.beastapp.BeastLauncher.run(Unknown Source)`
        `at beast.app.beastapp.BeastLauncher.main(Unknown Source)`
`Caused by: java.lang.StackOverflowError`
        `at java.util.Collections$UnmodifiableCollection$1.<init>(Collections.java:1039)`
        `at java.util.Collections$UnmodifiableCollection.iterator(Collections.java:1038)`
        `at beast.evolution.tree.Node.toShortNewick(Unknown Source)`
        `at beast.evolution.tree.Node.toShortNewick(Unknown Source)` 
        `at beast.evolution.tree.Node.toShortNewick(Unknown Source)` 
        `at beast.evolution.tree.Node.toShortNewick(Unknown Source)` 
         ....... [repeats this last line many many times]
`-- org.jblas INFO Deleting /tmp/jblas1020249646408363090/libjblas.so`
`-- org.jblas INFO Deleting /tmp/jblas1020249646408363090/libjblas_arch_flavor.so`
`-- org.jblas INFO Deleting /tmp/jblas1020249646408363090`

The tip dates all look correct in Beauti (ie height of 0 for most recent). Just removing the tip dates allows the analysis to run, but these are really integral to the analysis I am running. Could you please help? Thanks!

**Comment by tgvaughan** [comment]
Hi Amy,

The error message you've included is saying that java is running out of memory when trying to construct a newick representation of the multi-type tree.  This suggests that there are probably an unrealistically huge number of migration events being produced in the analysis.  You could try either putting upper bounds on the migration rate parameters, or on the population size parameters.  You might also want to check to see whether your starting tree is perhaps too tall.

Cheers,
Tim

**Comment by amymariecampbell** [comment]
Hi Tim, 

Thanks so much for your response! Interesting that it is a Java memory issue. 

I have tried adding upper bounds to the migration rate and population size parameters but unfortunately still getting the error. 

I stripped the xml down to basics (MultiTypeTree template, Tip Dates, Tip Locations, HKY model, Gamma Category Count 4, default strict clock model and default priors- so not even estimating the migration rate and population size) and I am also getting this java memory error. (Same analysis runs perfectly when I don't add in the tip dates). 

The tip dates are in yyyy-m-dd format, and the 'heights' all look correct. 

There is only 10 different entries in the alignment as this was a smaller testset (hoping to run this analysis on many more once I get it working.) 

Thanks so much again for your help so far, 
Amy

**Comment by tgvaughan** [comment]
Hi Amy, you might want to take a peek at the trees and parameter values being sampled in the run-up to the memory errors.  You might have to increase the logging frequency to see anything useful, but what you're looking for are (a) loads of migration events on the trees, and (b) some combination of super-high migration rates and/or super-long edges.

Tim

**Comment by amymariecampbell** [comment]
Hi Tim, 

Thanks for your help. After tinkering around with different priors and clock rates, the issue seems to have gone away!

Thanks again! 
Amy

**Comment by tgvaughan** [comment]
No problem; that's great to hear.
