### ISSUE TITLE
Allow scientific notation in XML

### ISSUE THREAD

**Issue by J-Moravec** [CompEvol/beast2#1024]
Scientific notation for some parameters, notably MCMC chain length, is easier to read.

How many zeros are there?
```
chainLength="50000000"
```
Takes a while to count. While with scientific notation, it is obvious:
```
chainLength="5e7"
```

The problem lies in this function:

https://github.com/CompEvol/beast2/blob/518a0ed4178425251690365bd1379afd46719c17/src/beast/core/Input.java#L591-L709

Suggested solutions:

use either `BigDecimal(stringValue).intValueExact()` (`longValueExact()`) or `DecimalFormat` class to parse the input before converting to `Integer` or `Long`.

Happy to create pull request and write tests.

**Comment by tgvaughan** [comment]
I completely agree, and in fact suggested this previously in the related issue/question #555.

**Comment by J-Moravec** [comment]
Fixed by #1025

**Comment by rbouckaert** [comment]
Perhaps BEAUti can benefit from this as well, so users can input scientific notation there. I suppose we have to chase any `Integer.parseInt` and `Long.parseLong` instances to find these places.

**Comment by J-Moravec** [comment]
I will open a new issue then.
