### ISSUE TITLE
Error 1017 parsing the xml input file Tree.t:Species

### ISSUE THREAD

**Issue by emrullahub** [CompEvol/beast2#1027]
Hi,

<stateNode id='Tree.t:Species' spec='starbeast2.SpeciesTree'>
I got this issue when i run beast with java or both it does not matter. I attached a screenshot. So, could you please help me?
![screenshot](https://user-images.githubusercontent.com/62052339/167301544-bbd02eef-fa19-42ab-8638-e6bcaddbc582.png)

Best regards,
Emrullah

**Comment by rbouckaert** [comment]
Hi Emrullah,

The screen shot shows that StarBeast2 is not installed, but the XML requires a class from StarBeast2.The [page](https://www.beast2.org/managing-packages/) on managing packages has more information on how to install packages in various ways.
Hope this helps,
Remco
PS This question is more suitable for the [beast-user list](https://groups.google.com/forum/#!forum/beast-users).
