### ISSUE TITLE
Data from time layers

### ISSUE THREAD

**Issue by eugeniosss** [CompEvol/beast2#1034]
Hello,
So my goal is to estimate divergence dates with BEAST2 (I am using version 2.5.0), through aDNA. My problem is that my samples come from archaeological layers, they are labeled as belonging to the Roman period, for instance. Therefore, I have a period range from to 1567 to 2144 before present. So my question is what is the best way to input this in BEAST2? In the tip dates menu I am not able to give a sample an interval of dates, only one definite value (maybe I could use the mean, to minimize the error?). But what I am trying is to do priors with an uniform distribution corresponding to the period range of the sample. Is this the best way? And if so I am doing a prior per sample, although I have, in most cases, more than one sample per time period, could I put all samples from the same period range in the same prior? If I use one prior per sample, I have to assign "Use originate" to the prior, is this correct, given that I want to infer the dates with the age of my samples? (I am not sure if BEAST is instead assuming the age of the node as the age of the sample)?

Any insight on this matter is welcome! Hope I was clear enough!

**Comment by rbouckaert** [comment]
The tip dates panel only allows you to enter a starting value for tips, but you can add distributions for tips in the priors panel: add an MRCA prior with a single taxon (just for the tip), add a distribution and make sure `tipsonly` is checked for that MRCA prior. If you have many of them, perhaps adding them in the NEXUS file is easier (see https://www.beast2.org/2021/04/12/constraining-trees.html for details).

Perhaps the [CladeAge](https://github.com/BEAST2-Dev/cladeage/releases/download/v1.2.0/cladeage20160609.pdf) or [sampled ancestor](https://github.com/CompEvol/sampled-ancestors) package could be useful.

Please upgrade to v2.6 (v2.6.7 is the latest at the moment): it has many bug fixes and many more capabilities.

This facility is meant for bug reports and feature requests. The BEAST users list (https://groups.google.com/forum/#!forum/beast-users) is a more appropriate place to ask these kind of questions.
