### ISSUE TITLE
Why the prior and posterior didn't reach convergence after a long chain

### ISSUE THREAD

**Issue by biozhajie** [CompEvol/beast2#1035]
Dear Professors,
Why the prior and posterior didn't reach convergence after a long chain, the both values always keep breaking the top limits when running. 
I have attached my xml file below, please help me fix this issue.

Thanks,
Jie
[H1N1_HA-4.zip](https://github.com/CompEvol/beast2/files/9204905/H1N1_HA-4.zip)

**Comment by rbouckaert** [comment]
This may have some useful information about increasing the ESS:
https://www.beast2.org/2019/08/01/increasing-ess.html
