### ISSUE TITLE
Not explicit documentation about setting distribution on MRCAPrior

### ISSUE THREAD

**Issue by MordorianGuy** [CompEvol/beast2#1043]
This is not explicit & comprehensible from [documentation](https://www.beast2.org/xml/beast.math.distributions.MRCAPrior.html), of **which** should we specify distribution? Age or height?

For instance, I specified distribution of all taxa mrca as N(125.508; 16.951) & expected to get the mean of root height nearby this value. However, it turned out about 1850-1900 (it equals to 70-80 without the prior). When I read the code of the class, I saw that prior is calculated from the method `getDate` result. As it is not specified in BEAUTi, documentation, & can be confounded due to BEAST 1 experience, it would be nice to describe the moment in [documentation](https://www.beast2.org/xml).

**Comment by rbouckaert** [comment]
@MordorianGuy thanks for pointing this out -- I updated the description of MRCPrior with commit https://github.com/CompEvol/beast2/commit/caca47dfeeda8cb9d4fd2f811e4527cbf8737498, which should clarify this.

The documentation you refer to was updated as well. This documentation is usually automatically generated, so it will be there for newer versions of BEAST as well.
