### ISSUE TITLE
Loading XML back into BEAUti seems to break things

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#1064]
I've been testing the [Introduction to BEAST 2 tutorial](https://taming-the-beast.org/tutorials/Introduction-to-BEAST2/) with BEAST 2.7.  This involves

1. Importing primate-mtDNA.nex into BEAUti.
2. Setting up a simple analysis with a calibration on the human-chimp divergence time and the chain length set to 10^6 steps.
3. Saving the XML and running the analysis
4. Loading the XML back into BEAUti to modify the chain length to 10^7 steps.
5. Saving the new XML and running the analysis.

Everything went as expected, except for step 5.  When running the XML, BEAST exits with the following error:
```
validate and intialize error: Operator gammaShapeScaler.s:noncoding has a statenode meanClockRate.c:clock in its inputs that is missing from the state.
```

It seems as though this parameter has been added to several operators somehow during the reload and save, as it's not present in the original file.

I've attached both the pre- and post-reload XML files.
[Primates_long.xml.txt](https://github.com/CompEvol/beast2/files/10102648/Primates_long.xml.txt)
[Primates.xml.txt](https://github.com/CompEvol/beast2/files/10102650/Primates.xml.txt)

**Comment by rbouckaert** [comment]
It looks like a bug in the RandomLocalClock template. https://github.com/CompEvol/BeastFX/commit/cff71442d26cd5931f1a66b22e5a08fba8d00578 might have fixed it.

**Comment by rbouckaert** [comment]
Hi Tim, No problem, still could find it :-) Turned out to be some frequencies related connector issues as well, which should be fixed now. I could reload the Primates.xml file, save it and BEAST runs on the saved file, so I think the problem is fixed now.
