### ISSUE TITLE
Sample from Prior : one or more traces contain invalid values and are not able to be displayed

### ISSUE THREAD

**Issue by qianxuans** [CompEvol/beast2#1067]
Hi,
I used HKY site model with 2.0 Kappa, coalescent constant population, and the MCMC chain length is 300,000,000. It works fine when the 'sample from prior' is not clicked. However, when I used the 'sample from prior' and read the log file using Tracer. There were warning messages of "One or more traces contain invalid values and are not able to be displayed." when checking likelihood, treeLikelihood, and clockRate.
Can someone help me fix this, please?

**Comment by rbouckaert** [comment]
When sampling from the prior, the likelihood and treelikelihood is reported as `NaN`, which means `not a number`. It is fine to ignore these entries in tracer. However, the clock rate is probably escaping to infinity if the prior allows that. Changing the prior on the clock rate will prevent this. There is some more information [here](https://beast2-dev.github.io/hmc/hmc/Priors/ClockPrior/).

By the way, this facility is for reporting bugs and feature request for BEAST. For user questions, please use the [beast user list](https://groups.google.com/g/beast-users/).
