### ISSUE TITLE
beast2 only usable wich OpenCL

### ISSUE THREAD

**Issue by pgrt** [CompEvol/beast2#1069]
Hello,

I am working on my Debian packaging of beast2; when typing (from the unpacked source dir, with beast2-mcmc being my script launching beast.pkgmgmt.launcher.BeastLauncher)

$ beast2-mcmc examples/testPlates.xml

I get some output ending with 

----------
[...]
Starting frequencies: [0.3407928388744389, 0.2442455242966905, 0.16496163682887072, 0.25]

OpenCL error: CL_DEVICE_NOT_FOUND from file <GPUInterfaceOpenCL.cpp>, line 122.

----------

If I type

$ beast2-mcmc -beagle_CPU examples/testPlates.xml

I get the same error message. Is there a way to enforce CPU mode?

Thanks a lot,
Pierre

**Comment by rbouckaert** [comment]
Hi Pierre,

The `-beagle_CPU` options should force use of the CPU version of BEAGLE, but apparently it does not. 

What information do you get with `beast2-mcmc -beagle_info`? 

Does `beast2-mcmc -java examples/testPlates.xml` make it start?

Cheers,

 Remco

**Comment by pgrt** [comment]
Hi Remco,

Thanks again for the quick answer!

Indeed,
$ beast2-mcmc -beagle_info outputs the headers and then

---------------------------------------------------------------------------------------------
                               Thanks to:
          Roald Forsberg, Beth Shapiro and Korbinian Strimmer


--- BEAGLE RESOURCES ---


OpenCL error: CL_DEVICE_NOT_FOUND from file <GPUInterfaceOpenCL.cpp>, line 122.

---------------------------------------------------------------------------------------------

Using
$ beast2-mcmc -java examples/testPlates.xml
it works, cool!
Do you think we should make this the default?

Warm thanks again,

Pierre

**Comment by rbouckaert** [comment]
Hi Pierre,

Usually, BEAGLE will give a big performance improvement, so if a all possible, using the `-java` option should not be the default. 

Perhaps the version of BEAGLE you have installed is compiled with OpenCL support, but no OpenCL libraries are installed? This [post](https://groups.google.com/g/beast-users/c/DwF6bSaD_Qc/m/per-uVikBAAJ) suggests to use the `--without-opencl` command when running `./configure` when building BEAGLE. Maybe worth a try?

Cheers,

Remco

**Comment by pgrt** [comment]
Hi Remco,

Huge thanks for your advice on this, I could add the `--without-opencl` in the configure step of beagle as you suggested, and the problem has disappeared.

Now I will look at our other ongoing issues...

Cheers,

Pierre
