### ISSUE TITLE
PackageManager -dir does not alter installation directory

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#1070]
The following line from the packagemanager usage
```
-dir Install/uninstall package in directory <DIR>. This overrides the useAppDir option
```
seems to suggest that by writing
```
packagemanager -dir ./my_app_dir -add feast
```
I should be able to install feast in ./my_app_dir instead of the default location.

Instead, the packagemanager ignores the argument and proceeds to try to install in the standard user package directory:
```
Packages user path : /Users/vaughant/Library/Application Support/BEAST/2.7
Access URL : https://raw.githubusercontent.com/CompEvol/CBAN/master/packages2.7.xml
Access URL : https://tgvaughan.github.io/remaster/package.xml
Getting list of packages ...Done!

Installation aborted: feast is already installed.
```

Looking at the [source](https://github.com/CompEvol/beast2/blob/451e2ff62fab6f97e6ada09f4aafdf576ed5712b/src/beast/pkgmgmt/PackageManager.java#L2045), the -dir argument seems to add the provided path to a path list which is then assigned to the property with the hard-coded name "BEAST_PACKAGE_DIR".  This property doesn't seem to be referenced at all by the getPackageUserDir() method, which instead references the "beast.user.package.dir" property.

Is this a bug?  Or am I misunderstanding the purpose of -dir?  For what it's worth, adding -Dbeast.user.package.dir=./my_app_dir when running packagemanager produces the expected behaviour, so I can work around this. The documentation seems wrong to me though.

**Comment by rbouckaert** [comment]
Just tried
```
packagemanager -dir /tmp/ -add ClaDS
```
and it ends with the message `Package ClaDS is installed in /tmp//ClaDS.`, and indeed the directory `/tmp/ClaDS/` is created and contains the ClaDS package files, and it is not in the default user directory. 

Before installing a package, the package manager checks if the package is already installed somewhere, including in the user directory. If the package is already installed, it stops with the installation in order not to end up with several versions of a package in different directories. Is there a better way to do this?

**Comment by rbouckaert** [comment]
It actually makes more sense to treat it as a user defined user directory, so when this directory is specified, the `beast.users.package.dir` property is set, and any packages installed in the default user package directory are ignored. [206ad74](https://github.com/CompEvol/beast2/commit/206ad74aa226d4228a2b7fb263f0c4e3ca2a2ce7) does this. This way you won't have to set the java directive explicitly. Perhaps BEAST and BEAuti should have matching command line options?

**Comment by rbouckaert** [comment]
[206ad74](https://github.com/CompEvol/beast2/commit/206ad74aa226d4228a2b7fb263f0c4e3ca2a2ce7) makes packagemanager set the `beast.user.package.dir` property when specifying the `-dir` option, thus ignoring packages installed in the default user package location. I think it behaves now more like you expected and should work in combination with the BEAST and BEAUti options as well.
