### ISSUE TITLE
Unicode (UTF-8) input support for BEAST XML inputs

### ISSUE THREAD

**Issue by jjmccollum** [CompEvol/beast2#1076]
According to the BEAST 2 FAQ (https://www.beast2.org/2021/05/17/beast-xml.html), XML input files to BEAST are said to have declarations that assume a UTF-8 encoding:

> The only part allowed before the beast element is the XML declaration (which contains some information about the XML format), which should look like this `<?xml version="1.0" encoding="UTF-8" standalone="no"?>`.

But I am working with a dataset that uses Unicode characters (specifically, Greek characters) in state labels, and the presence of these characters (or perhaps the UTF-8 encoding of the entire file) is causing the BEAST v2.7.3 app to throw the following error:

```
java.lang.IllegalArgumentException: org.xml.sax.SAXParseException; lineNumber: 50; columnNumber: 178; Invalid byte 2 of 2-byte UTF-8 sequence.
```

I checked my input file and verified that it does have UTF-8 encoding, so there doesn't appear to be any discrepancy between the file encoding and the encoding specified by the XML declaration. So my question is, does BEAST not presently support XML inputs with UTF-8 encoding? I can easily convert my Greek Unicode characters to ASCII mode and remove the XML declaration to avoid any confusion, so this isn't necessarily a feature request; I just wanted to make sure that I wasn't missing something.

**Comment by jjmccollum** [comment]
@tgvaughan Apologies that it took me so long to come up with one! It turns out that very little is needed to reproduce the error:

```xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<beast version="2.7" namespace="beast.pkgmgmt:beast.base.core:beast.base.inference:beast.base.evolution:beast.base.evolution.alignment:beast.base.evolution.datatype:beast.base.evolution.tree:beast.base.evolution.tree.coalescent:beast.base.evolution.branchratemodel:beast.base.inference.util:beast.evolution.nuc:beast.base.evolution.operator:beast.base.inference.operator:beast.base.evolution.sitemodel:beast.base.evolution.substitutionmodel:beast.base.evolution.likelihood">
  <data spec="Alignment" id="alignment" dataType="standard" statecount="2">
    <!-- Remove the following line, and the SAXParseException will not be thrown: -->
    <charstatelabels spec="UserDataType" characterName="B10K1V18U2-12" codeMap="0=0, 1=1, ?=0 1" states="2" value="πεφωτισμενους_τους_οφθαλμους_της_καρδιας_υμων, πεφωτισμενους_τους_οφθαλμους_της_καρδιας"/>
  </data>
</beast>
```

(Granted, this example will fail for other reasons once you get past the `SAXParseException`, but the parsing is my only concern here.) I was able to isolate the line that was triggering the `SAXParseException`; it seems to be something in the `value` attribute of the `charstatelabels` element. Curiously, the exception still gets thrown if the `charstatelabels` element is commented out.

**Comment by jjmccollum** [comment]
It sounds like it must be! For what it's worth, I'm running BEAST v2.7.3 in the BEAST.exe GUI on Windows 10, using the download for Windows at https://www.beast2.org/.

**Comment by jjmccollum** [comment]
It's a possibility. I checked for this before I posted this issue because I've made that mistake before, but VS Code and Notepad both are telling me that the encoding is UTF-8. Still, I can't think of what else it could be, so I've attached the file here. (I had to zip it because GitHub doesn't allow XML attachments.)
[beast_unicode_mwe.zip](https://github.com/CompEvol/beast2/files/10435229/beast_unicode_mwe.zip)

**Comment by jjmccollum** [comment]
It took me a while to confirm it, but your suspicion was correct: for some reason (which I still don't know), my JVM did not have UTF-8 as the default file encoding. I had to enter the command

```bash
set JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
```

and then run BEAST.exe from the command line, and this time I got to missing element error message you got.

I can now close this issue. But I do have to ask: is UTF-8 file encoding the default setting in Java for most people? And if not, is there a simple way to set this on Windows so I don't have to do it on the command line every time? (I suppose adding `JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8` as an environment variable would work, but I'm wondering if there's an alternate way to configure the default settings of the JVM.)

**Comment by rbouckaert** [comment]
Weirdly enough, this does not seem to be a problem with Linux or Mac, only Windows. I updated configuration files so BEAST and BEAUti should recognise UTF-8 under Windows at the next release.

**Comment by rbouckaert** [comment]
But only under Windows, so it must have had something to do with the way the OS loads files into memory then. Anyway, I hope [adeb99c](https://github.com/CompEvol/beast2/commit/adeb99cf273949ff7ebacb425f1aba352a30550b) fixed the problem for the future.
