### ISSUE TITLE
Sequence.initProbabilities assumes all sites have the same number of states

### ISSUE THREAD

**Issue by jjmccollum** [CompEvol/beast2#1077]
The `Sequence` class's `initProbabilities` method contains the following double loop:

```java
String str = data.trim();
String[] strs = str.split(";");		
for (int i=0; i<strs.length; i++) {
    String[] pr = strs[i].split(",");
    //double total = 0;
    for (int j=0; j<pr.length; j++) {    			
        if (likelihoods == null) likelihoods = new double[strs.length][pr.length];
        likelihoods[i][j] = Double.parseDouble(pr[j].trim());
        //total += likelihoods[i][j]; 
    }    		
}
```

This issue concerns the conditional memory allocation

```java
if (likelihoods == null) likelihoods = new double[strs.length][pr.length];
```

If all sites have the same number of states (as is the case for nucleotide data), then this makes perfect sense. But for a standardData sequence in which any site has more states than the first, then this line will allocate too few columns, and this will result in an indexing error at a subsequent site.

Probably the simplest and most consistent way to resolve this would be to calculate the `likelihoods` row and column sizes with an initial loop over the sequence finding the maximum value of `pr.length`.

**Comment by rbouckaert** [comment]
Just some background: `initProbabilities` is called from `initAndValidate` only if the sequence data is uncertain. Support for uncertain data was added with sequences having the same number of states in mind, e.g. nucleotide data where uncertainty comes from the number of reads provided by the sequencing machine. In this case, the sequence data would be erroneous if it contains sites with different lengths. The `TreeLikelihood` also assumes equal number of states for each sites, and to a large extent gets its efficiency from it. When a `Sequence` has different state counts at different sites would require a custom tree likelihood or splitting into sub-sequences, each with sites with the same state count (like is done in the morph-models package).

Anyway, would adding

```java
			if (likelihoods != null && likelihoods[i].length != pr.length) {
				likelihoods[i] = new double[pr.length];
			}
```

at `//double total = 0;` be sufficient for your requirements?

**Comment by jjmccollum** [comment]
To answer your question first, adding those lines should be sufficient, but you would have to add them before the line

```java
likelihoods[i][j] = Double.parseDouble(pr[j].trim());
```

because otherwise, if `j >= pr.length`,  then the indexing will raise an `ArrayIndexOutOfBoundsException`.

It may also be worthwhile for me to explain why I was interested in using uncertain sequence data. In the textual setting where I'm applying Bayesian phylogenetics, it is sometimes possible when a witness (= taxon) has a gap to determine the likelihoods of different readings (= states) filling that gap in the witness. So instead of an ambiguous state token like `{01}` (which assumes the states are equally likely), it would be nice to specify that one disambiguation is more likely than another.

My impression was that using tip likelihoods could allow me to take advantage of this situation, but if I'm misunderstanding how they work, please feel free to correct me. I know that in his book, Felsenstein warns that treating tip states as probabilities summing to 1 is tempting, but incorrect, and that ambiguities should be encoded as 1s in all their potential states, but I don't think he ever explains what to do if we know that one state in an ambiguity is actually more likely than another.
