### ISSUE TITLE
beast 2 package guide out of date

### ISSUE THREAD

**Issue by Wytamma** [CompEvol/beast2#1081]
Hi @rbouckaert,

It seems the [beast2 package guide](http://www.beast2.org/package-development-guide/writing-a-beast-2-package/) is out of date for version 2.7 and I'm having trouble converting it. Do you have a simple template repo for writing a beast 2.7 package or instructions for version 2.7?

**Comment by rbouckaert** [comment]
Thanks for pointing this out -- documentation indeed lags a bit with the release, but it is certainly on the todo list, including making the website both v2.6 and v2.7 compatible. Will let you know when the package guide is updated.

**Comment by rbouckaert** [comment]
Kylie wrote a developer guide for Intellij that may be useful: https://github.com/kche309/beast-developer-guide

**Comment by rbouckaert** [comment]
@Wytamma the beast2 package writing tutorial is updated now, and can be found [here](http://www.beast2.org/package-development-guide/writing-a-beast-2_7-package.html). 
The [developers page](http://www.beast2.org/package-development-guide/) has been updated as well.
Let me know if you into any problems.

**Comment by Wytamma** [comment]
Amazing! Thanks so much @rbouckaert :D
