### ISSUE TITLE
ComplexSubstitutionModel should have a check that beagle is disabled

### ISSUE THREAD

**Issue by jordandouglas** [CompEvol/beast2#1086]
Irreversible substitution models have imaginary eigenvectors, which are not supported by beagle. If the user runs one of these models using beagle, the likelihood calculation is wrong (and oftentimes a positive number). 

So either the tree likelihood, or the substitution model, should turn beagle off (or throw an error) if the substitution model is complex

**Comment by rbouckaert** [comment]
Using the `setTransitionMatrix` method of BEAGLE, it is still possible to use the library with subst models that have imaginary Eigen vectors. By starting BEAST with the `-java` flag, it can always be switched off in case the java version is faster. https://github.com/CompEvol/beast2/commit/e46fc965da029c447e45432fb5deac3e30dc3e85 implements this, so BEAGLE is still used by default if available.
