### ISSUE TITLE
BEAUti stopped working

### ISSUE THREAD

**Issue by vahava** [CompEvol/beast2#1088]
Hello,

I have been running analyses on BEAST 2.7.3 for the past two weeks and have suddenly started to experience problems with BEAUti. Until now it has been working OK but since a couple of days ago it started giving the error message below immediately when choosing "Import alignment" (before even choosing the file to import). Installing the program again did not help. I tested opening the same BEAUTi file under a different username on the same computer. Weirdly, it worked for a couple of hours and then suddenly started giving the same error message than before. 

I have macOS Monterey (M1), Java 8. 

Thanks in advance for any help.

<img width="998" alt="Beauti error message" src="https://user-images.githubusercontent.com/126508104/221645780-137b972b-cdca-4235-810d-886844225637.png">

**Comment by rbouckaert** [comment]
Could you try deleting the `beauti.properties` file, e.g. from a terminal using `rm ~/Library/Application\ Support/BEAST/2.7/beauti.properties` and see whether this fixes the problem? This file stores the working directory, which is used by the file chooser that opens when selecting the `File/Import alignment` menu. Perhaps the working directory disappeared and that trips over the file chooser.

**Comment by vahava** [comment]
This resolved the issue, thanks so much for your help!

**Comment by rbouckaert** [comment]
Should be fixed by https://github.com/CompEvol/BeastFX/commit/fa99b81e42cdf1b45be51cbefd91ad9e54fbd2ba
