### ISSUE TITLE
Unable to open

### ISSUE THREAD

**Issue by YuchiXi** [CompEvol/beast2#1103]
Hello,
This warning will pop up every time BEAUTi is opened，I can't find a solution.
![$ }40T}8 {W$J2G%`F%72WB](https://user-images.githubusercontent.com/63325316/227974065-be44b3eb-22a8-48a8-b089-d03110edd61c.png)

**Comment by rbouckaert** [comment]
Through the package manager (BEAUti menu File => Manage packages) you should be able to check if the BEASTLabs package is installed? If not, install that package (it should have been installed when ORC was installed, but perhaps something went wrong), or uninstall ORC, then install ORC again. Next time BEAUti starts, the message should not appear any more.

**Comment by YuchiXi** [comment]
> Through the package manager (BEAUti menu File => Manage packages) you should be able to check if the BEASTLabs package is installed? If not, install that package (it should have been installed when ORC was installed, but perhaps something went wrong), or uninstall ORC, then install ORC again. Next time BEAUti starts, the message should not appear any more.

Thank you for your reply!
But it seems that a new problem has arisen in this way.![-be28ea4bdaee65.png](https://user-images.githubusercontent.com/63325316/228107895-6a669457-ce2f-4653-9e35-d2c0b45492bb.png)

**Comment by rbouckaert** [comment]
Could you try to install v2.7.4 of BEAST, which is available for Windows [here](https://github.com/CompEvol/beast2/releases/download/v2.7.4pre/BEAST.v2.7.4.Windows.zip): it should have a fix for not being able to access the URL mentioned in the error message, and uses a copy of the file from bitbucket instead. 

For Windows, the release is already available, but we still building the Mac version. The download link may change to https://github.com/CompEvol/beast2/releases/download/v2.7.4/BEAST.v2.7.4.Windows.zip once the Mac version is available and the release is official.
