### ISSUE TITLE
using a MRCA + snapper made mismatches with Taxon ~ TaxonSet labels

### ISSUE THREAD

**Issue by drelo** [CompEvol/beast2#1106]
Dear BEAST users, 

I have used BEAST2 before with other routines but I am stuck in this analysis. 
I am using snapper to try to date a dataset using some secondary calibrations. I noticed the best approach to establish Species/Population in the Taxon Set tab was using the '_guess_' option, so I relabeled the data to conform to this and I used the "everything before first '_'" . Since samples under the same species are labeled like this 'agu_H8' or 'agu_F5' etc, a Species label '_agu_' is generated and it seemed to work, i.e. if I don't specify a taxon prior I can run this analysis just fine.

As soon as I include 2 sequences of agu + mk in a MRCA Taxon prior in the _**Priors**_ panel the analysis fails.
For example I have these labels in the dataset

> mk_B2
> agu_A8
> agu_H7 

and the MRCA built has this 

```
<distribution id="prior" spec="CompoundDistribution">
                <distribution id="AG.prior" spec="beast.base.evolution.tree.MRCAPrior" tree="@Tree.t:shorty">
                    <taxonset id="AG" spec="TaxonSet">
                        <taxon id="agu_A8_" spec="TaxonSet">
                            <taxon id="agu_A81" spec="Taxon"/>
                        </taxon>
                        <taxon id="agu_H7_" spec="TaxonSet">
                            <taxon id="agu_H71" spec="Taxon"/>
                        </taxon>
                        <taxon id="mk_B2_" spec="TaxonSet">
                            <taxon id="mk_B21" spec="Taxon"/>
```
_and  I got this error_

> validate and intialize error: Taxon <agu_A8_> could not be found in list of taxa. Choose one of [mob, olb, rz, oli, mk, agu]

If I use agu as a label for both I get another error

> IDs should be unique. Duplicate id 'agu' found

Is there a way to fix this? I have no problem to manually edit the xml as a workaround now, but I haven't found a way to conciliate this. 

Maybe this is related to this issue https://github.com/CompEvol/beast2/issues/957

Please find attached the xml generated moreprior.xml, the shorty.fasta file  and the modified xml I tried to use replace.xml

[shorty.txt](https://github.com/CompEvol/beast2/files/11253440/shorty.txt)
[moreprior.txt](https://github.com/CompEvol/beast2/files/11253511/moreprior.txt)
[replace.txt](https://github.com/CompEvol/beast2/files/11253502/replace.txt)

Thanks for your help.

Andrés

**Comment by rbouckaert** [comment]
Hi Andrés, 

In snapper, there is only a single tree: the species tree, and the taxa of that tree are [mob, olb, rz, oli, mk, agu], so the MRCA prior should refer to these taxa, not the lineage taxa specified in the alignment. So, you were on the right way replacing `agu_A8_` with`agu`. But since the `agu` taxon was already specified in the taxonset for the tree, an `idref` attribute should be used instead of an `id` attribute. If you replace in `replace.txt`

```
                    <taxonset id="AG" spec="TaxonSet">
                        <taxon id="agu" spec="TaxonSet">
                            <taxon id="agu_A81" spec="Taxon"/>
                        </taxon>
                        <taxon id="agu" spec="TaxonSet">
                            <taxon id="agu_H71" spec="Taxon"/>
                        </taxon>
                        <taxon id="mk" spec="TaxonSet">
                            <taxon id="mk_B21" spec="Taxon"/>
                        </taxon>
                    </taxonset>
```

with

```
                    <taxonset id="AG" spec="TaxonSet">
                        <taxon idref="agu"/>
                        <taxon idref="mk"/>
                    </taxonset>
```

it will run.

In BEAUti, there seems to be a problem with the `MRCAPriorInputEditor` picking up the correct taxon sets after they have been edited in the `TaxonSetInputEditor` in the snapper template, which is a [BeastFX](https://github.com/CompEvol/BeastFX) issues, so I'll create an issue there () and close this one.

**Comment by drelo** [comment]
Thank you very much! that fix made it work

All the best,

Andrés
