### ISSUE TITLE
Push new build v2.7.4 to conda?

### ISSUE THREAD

**Issue by russellsmithies** [CompEvol/beast2#1110]
Can we get the latest v2.7.4 pushed to conda please? I've been trying to build from src but not having much luck so far as Babel and BEASTLabs won't compile for me.

**Comment by rbouckaert** [comment]
What problem exactly are you running into when compiling from source?
Did you follow the instructions for building from https://github.com/CompEvol/BeastFX/blob/master/README.md?

**Comment by rbouckaert** [comment]
By lack of detail, I'll close the issue, but please reopen if you have still have trouble compiling from source.
