### ISSUE TITLE
About BEAST2 run error

### ISSUE THREAD

**Issue by bseonghyeon** [CompEvol/beast2#1119]
Whenever I put an xml file into BEAST2, I get this error message. Do you know how to solve this error? Also, why are these errors occurring? To add, I'm using Beast in a Windows 10.

Error detected about here:

> <beast>

> <run` id='mcmc' spec='MCMC'>

> <init id='RandomTree.t:Korea' spec='beast.evolution.tree.RandomTree'>

**Comment by rbouckaert** [comment]
What is the complete error message? 

Are you perhaps using BEAST v2.7 to run an XML produced for V2.6? The XML format changed between v2.6 and v2.7, so make sure to use the correct version of BEAST when running the XML.

**Comment by bseonghyeon** [comment]
![image](https://github.com/CompEvol/beast2/assets/140041065/0aff350d-b354-44a7-b08a-b804e3cef6cb)

The complete one is here.
I'm using v2.6.7 and v2.6.0. But both versions give the same error message. I used v2.6 beast because I created the xml files with beuti included in v2.6 package.

**Comment by rbouckaert** [comment]
The error message suggests a taxon `2-4` was referred to from the Random tree (which initialises the tree at the start of the MCMC run), but that taxon does not exist in the tree. It is hard to say what is going wrong here. If you can send me the XML higgs.ml@gmail.com I am happy to investigate further.

**Comment by rbouckaert** [comment]
Looks like this was caused by clade information in the nexus file that refers to non-existing taxa in the alignment (see email 25 Jul 2023). Removing MRCA priors fixed the problem.
