### ISSUE TITLE
BactrianUpDownOperator modifies the wrong index when elementWise is true

### ISSUE THREAD

**Issue by bjoelle** [CompEvol/beast2#1126]
l95 and l105 have this code `p.setValue(p.getValue(index) * scale);` which as far as I can tell will modify the value at position 0 regardless of what `index` is set to
the equivalent code in `UpDown` operator is `p.setValue(index, p.getValue(index) * scale);` as expected

**Comment by rbouckaert** [comment]
Good point! Should be fixed by https://github.com/CompEvol/beast2/commit/c9862c540afc80e9fa6d7b690163f9bf030db3b7
