### ISSUE TITLE
Clarification about Trees and StateNodeInitialiser

### ISSUE THREAD

**Issue by jacklo225** [CompEvol/beast2#1142]
Hello! 
I'm currently writing a Coalescent-variant Tree class extending Tree. I want the class to be able to take an input Tree if given one, and also simulate a starting Tree if no input Tree is given—does this mean that the class should implement StateNodeInitialiser (SNI) like the RandomTree class? I'm a bit confused about when Trees should themselves be SNIs, and what being or not being a SNI means for whether an initial tree should be given via m_initial or not. Perhaps this stems from lacking understanding of how SNIs differ from state nodes in the first place, particularly when they are themselves state nodes. 

On a related note,
The initAndValidate() function in Tree.java contains these lines:

``` 
if (m_initial.get() != null && !(this instanceof StateNodeInitialiser)) {
    throw new RuntimeException("initial-input should be specified for tree that is not a StateNodeInitialiser");
}
```

The exception comment seems contradictory to the if-condition; does it mean to say that initial-input should NOT be specified for tree that is not a SNI? 

Thank you for your help!

**Comment by rbouckaert** [comment]
SNIs are supposed to be specified as `init` inputs to the MCMC object, while `StateNode`s are supposed to be specified as `stateNode` inputs to the `state` of the MCMC. In theory, an SNI does not necessarily have to be a `StateNode`, but being an SNI means it must be able to initialise a `StateNode`, which is supposed to be specified by the `initial` input to the SNI.  

In practice, it is convenient for SNIs to be implementations of for example `Tree`, which happens to be a `StateNode` as well. So, that is why for example `RandomTree` and `ClusterTree` are SNI as well as `StateNode`.

I agree that the location of the `m_initial` input is a bit confusing, and makes more sense to be specified in each of the SNIs deriving from `Tree`. The exception you mention is a consequence of this somewhat illogical design decision, but we usually specify a `beast.base.evolution.tree.Tree` as `StateNode` and have a Tree-derived SNI to initialise the tree, which is enforced by the exception.

Hope this clarifies things.

**Comment by jacklo225** [comment]
Thank you for your speedy and detailed response! That does clarify things a bunch. So, to double-check my understanding, `ClusterTree` follows that usual pattern stated in your last sentence whereby it is a Tree-derived SNI that initialises an `m_initial` input if it exists and then steps back, but if a `m_initial` input is not provided then it steps in acts as the tree itself? 

Therefore, `m_initial` doesn't act as an preexisting initial tree itself, but as a receiver of the initial tree build by the SNI, and if I wanted to work with a preexisting initial tree, I'd be looking at classes like `TreeParser` instead?

Thanks again for your help.

**Comment by rbouckaert** [comment]
`ClusterTree` does behave like you describe, but common usage is supposed to be that `m_initial` should be specified for BEAUti generated XML.

Indeed `m_initial` should refer to the StateNode to be initialised.

`TreeParser` can parse Newick trees, but be aware it binarises trees and sets all tips at the same time by default.

**Comment by jacklo225** [comment]
Thanks a bunch!
