### ISSUE TITLE
Treeannotator not going to 100%

### ISSUE THREAD

**Issue by asad-869** [CompEvol/beast2#1154]
Hi all, 

Attached is an image of treeannotator output. I am not getting the process to 100%. I am using 256 GB ram, 2 cores, 1 cpu, 2 nodes. I am unable to fix the issue. Any help would be much appreciated. Thanks.
 
<img width="819" alt="image" src="https://github.com/CompEvol/beast2/assets/139593182/1cb22d32-7d2b-4fea-9b32-312d41bbe656">

**Comment by rbouckaert** [comment]
fixed by https://github.com/CompEvol/BeastFX/commit/b1d667b74f4fc66be8d65a301f34fa00cd78dc02
