### ISSUE TITLE
Generate xml file in linux command line

### ISSUE THREAD

**Issue by Chonghao98** [CompEvol/beast2#1156]
Dear all,

I would like to know whether there is a way to generate xml file in a server based on linux command. Using beauti requires GUI, which needs to be run in a local machine. Is there a tool that does the same thing as beauti while is based on command line?

Thank you.

**Comment by rbouckaert** [comment]
There maybe something of use here: http://www.beast2.org/2018/03/09/10-ways-to-generate-beast-xml.html
It is an older post, so not all of the tools described may be updated, but it gives an idea on what is possible.

Also, if you want to do the same kind of analysis but with different data, the `-DF` option for BEAST can be useful. More details here: http://www.beast2.org/2021/03/31/command-line-options.html

**Comment by Chonghao98** [comment]
> There maybe something of use here: http://www.beast2.org/2018/03/09/10-ways-to-generate-beast-xml.html It is an older post, so not all of the tools described may be updated, but it gives an idea on what is possible.
> 
> Also, if you want to do the same kind of analysis but with different data, the `-DF` option for BEAST can be useful. More details here: http://www.beast2.org/2021/03/31/command-line-options.html

I see, thank you very much.
