### ISSUE TITLE
Request a feature to use "version_file" in AppLauncher

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#1158]
It will be very convenient to allow the "version_file" argument in AppLauncher for debugging in IDE, such as

`new Arguments.StringOption("version_file", "VERSIONFILE" ,"Provide a version file containing a list of services to explicitly allow. (Useful for package development.)")`

It then could be used to debug the following lines using `BEASTClassLoader` inside IDE:

https://github.com/alexeid/TreeStat2/blob/eeceb0ab7d6e6f6b9f14a5d3016fa52b6a9d544e/src/treestat2/TreeStatApp.java#L49-L50

**Comment by rbouckaert** [comment]
This adds a `-version_file` argument to AppLauncher: https://github.com/CompEvol/BeastFX/commit/5ab22365ae3ee518af78407bb792dd83e37c1181

**Comment by walterxie** [comment]
It works now :

<img width="555" alt="Screenshot 2024-08-06 at 11 58 46 AM" src="https://github.com/user-attachments/assets/3c25e2a8-37e6-4251-85eb-99636a32fb86">
