### ISSUE TITLE
BEAST 2.7.7 is not launched after update 

### ISSUE THREAD

**Issue by trilisser** [CompEvol/beast2#1165]
Hi there!

On my desktop (windows 10), after update BEAST 2.7.5 -> BEAST 2.7.7, BEAUti and BEAST doesn't launch at all without errors or warnings.
On the other desktop, BEAST 2.7.7  launches after downloading from the website but in the Package Manager I cannot download or update any package. It gives the next:
![image](https://github.com/user-attachments/assets/32b13671-fc5b-4f22-879e-dec4f83f4964)

There is something wrong with 2.7

**Comment by rbouckaert** [comment]
Thanks for the bug report. If BEAST and BEAUti do not launch, perhaps removing the package director and reinstalling packages may fix things. On Windows, the BEAST package directory can be found in your home directory `c:\Users\<yourname>\BEAST` where `<yourname>` is your user name. Hope this helps.

**Comment by trilisser** [comment]
Hello Remco
Thank you, that worked!

**Comment by rbouckaert** [comment]
Good to hear :-) Let me know if you run into any more trouble -- I'll close the issue, but you can reopen if the problem appears again.
