### ISSUE TITLE
MC3 requested

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#118]
immigrate BEAST1 MCMC3 for a start

**Comment by tgvaughan** [comment]
Why did this get closed?  I think there's a really good argument for having the core support more sophisticated algorithms such as (MC)^3 by _default_.  The existing random walk metropolis algorithm has known convergence issues with multimodal distributions, which includes at least a significant minority (if not majority) of the target densities we use BEAST to sample...
