### ISSUE TITLE
BEAUti error reporting

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#122]
Error reports for BEAUti are often poorly specified, and messages on standard output and standard error are probably quite useful, but only available if BEAUti is run from the command line. An option to capture these outputs in a log or some hidden panel where the user can copy these messages would be helpful in resolving BEAUti issues.

E.g. by redirecting System.err and Sytem.out to a stream that becomes visible in a dialog when clicking the Help/Log menu.

**Comment by walterxie** [comment]
@rbouckaert 
Do you think whether it will help to diagnose some issues like #829, if we log/append BEAUti errors into a file instead of `BeautiDoc.baos`? You could ask the user to provide the file, if `ByteArrayOutputStream baos` would save enough information before BEAUti failed.
