### ISSUE TITLE
plugins (aka addons) versioning

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#14]
I tried running the latest version of Beauti with an old version of the RBS addon.

This resulted in an exception, and no user level error message.

Would be nice to have some versioning information which enable Beauti to detect this on startup and issue a sane, user-level warning or failure.

**Comment by rbouckaert** [comment]
Related to #91

**Comment by rbouckaert** [comment]
Just tested that when the atmost-attribute is set in the version.xml file an error is shown indicating impeding doom due to version clashes in a JOpionPane, so this seems to be fixed.
Package managers are responsible for putting in an atmost-attribute in their version.xml file.
