### ISSUE TITLE
Relative operator weights

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#17]
Relative operator weights would make life easier for *BEAST implementers.

My proposal is straightforward.

Note: not valid beast2 XML, but you get the idea

``` xml
<operator weight="10">
  <operator name="op1" weight="2"/>
  <operator name="op2" weight="1"/>
</operator>

<operator name="op3" weight="5">
```

This is equivalent to the weights (10/15 \* 2/3),(10/15 \* 1/3) for op1/op2 and 5/15 for op3.

Basically, the total sum of all operators grouped together is equal to the weight of the group. It would be nice to have a democratic default:

``` xml
<operator weight="10">
  <operator name="op1"/>
  <operator name="op2"/>
</operator>
```

is equivalent to a weight of 5 for both.
### Comments from GC issue

Project Member #1 higgs.ml

Note, these meta-operators need care to store/restore from file (when resuming).

Sep 30, 2013
Project Member #4 higgs.ml

 Issue 20  has been merged into this issue.

Cc: jheled
Oct 8, 2013
Project Member #5 higgs.ml

support for nested operator info in state file is now available

**Comment by rbouckaert** [comment]
duplicate #633
