### ISSUE TITLE
Porting of Bayesian Skyride from BEAST1

### ISSUE THREAD

**Issue by alexeid** [CompEvol/beast2#172]
Bayesian skyride (http://mbe.oxfordjournals.org/content/25/7/1459.full) has been cited 170+ times. It is actually remarkably similar to BSP mathematically (the skyride is basically just a lognormal smoothing function instead of the exponential smoothing function in BSP, when the number of pieces is set equal to the number of intervals). It should be very easy to port this functionality, and users like it.

**Comment by rbouckaert** [comment]
There is now an implementation in beast-classic awaiting testing.
