### ISSUE TITLE
Error in BEAUti prior panel for GTR model

### ISSUE THREAD

**Issue by alexeid** [CompEvol/beast2#175]
From Tracy Heath:

The default priors on the GTR exchangeability rates have the "estimate" checked for all of the hyperparameters (alpha and beta of the gamma dist). However, these parameters aren't in the list in the priors panel. If you un-check "estimate", then check it again, these show up in the list. So it isn't clear why they are checked when you first go to the priors window.

**Comment by rbouckaert** [comment]
I checked that the hyper parameters are no longer shown as estimated initially, so this does no seem to be an issue any longer.
