### ISSUE TITLE
Tree height should be available in prior panel when a tree prior conditioned on root is selected

### ISSUE THREAD

**Issue by alexeid** [CompEvol/beast2#176]
From Tracy Heath:

"Is there a reason why the tree-height parameter isn't available in the priors window (even when the BD process is conditioned on the root)? It seems like the only way to put a prior on the root is to create a taxon-set containing all species, but then, both this value and "TreeHeight" are logged to file (and identical)."

If a tree prior that is conditioned on the root height is chosen (like BD process) then shouldn't the tree height be placed in the prior panel?

**Comment by rbouckaert** [comment]
If conditioned on the root, an MRCA prior must be placed on the root. I added a sanity check so that if there is no MRCA prior BEAST will print a warning.
