### ISSUE TITLE
Need functionality to remove unwanted MRCA statistics in BEAUti

### ISSUE THREAD

**Issue by alexeid** [CompEvol/beast2#178]
From Tracy Heath:

"The only other note I have coming from the TAs was that they were wondering if there was a way in BEAUti2 to delete a tmrca variable if you wanted get rid of it. For instance, if you click the + button and create a new taxon set, there is no way to remove it. They acknowledge that you didn't have to put a prior on the node or force it to be monophyletic, but mentioned that some students were uncertain about whether it would change their model if it was in the list of "Priors", even if it didn't have a prior on it. I did mention to them that this would only monitor the node, but if they didn't want to do this, then they would have to eliminate that node from the list of parameters logged to file in the XML. "

**Comment by rbouckaert** [comment]
See #291
