### ISSUE TITLE
Improve the starting state for *BEAST analyses with a large number of loci (i.e. >= 8 loci)

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#18]
Joseph has devised a new heuristic for creating a starting state for a *BEAST analysis when there are a large numbers of loci. We should incorporate this into the *BEAST state initialisation in BEAST2 to avoid very long burn-in times with large analyses.

### Comments from GC issue

Project Member #1 jheled

Code submitted, tested lightly. Needs more testing, and integration with templates and BEAUTI.

**Comment by rbouckaert** [comment]
Implemented in StarBeastStartState.
