### ISSUE TITLE
Incorrect XML for calibration in BEAUti 2.1.3

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#183]
Dear Walter,

Can you log this bug on GitHub please? BEAUti is not generating the XML correctly...

Alexei

Begin forwarded message:
# 

Hi Ashok,

The warning messages indicate that there are a few parameters that you may want to be estimating, but are not being estimated (since there are no operators that can do proposals for these parameters, as the warning message indicate). They are made part of the state by BEAUti, but not always removed while they should.

In your case, the mutation rates for CytB, ND4 and CMos are not estimated. This is not a problem if you estimate the clock rates for these loci.
The rateCategories.c:clock parameter is used when you have a relaxed clock. If you intend to use a relaxed clock model, this really should have a few operators in the XML, but if you use strict clock or random clock you can ignore the warning.

Cheers,

Remco
# 

On Tuesday, 12 August 2014 07:18:54 UTC+12, Ashok Mallik wrote:
Hello,

I am new to BEAST. Using BEAST 2.1.3. I am trying to calibrate my tree with three calibration points. However, when I run BEAST it shows following WARNING massage. However beast runs well. I have tried to figure out and could not understand well how to correct those informations. Someone please help me. screen print is attached here.

Thanks
Ashok

**Comment by alexeid** [comment]
Why are you closing this? Issues should only be closed if they are fixed surely? Otherwise what is the point of an issue tracker. If it remains an issue then it remains open, right?

**Comment by rbouckaert** [comment]
I looked at this again, and commented earlier (in 2014) that I thought the issue was too minor to be worth fixing (even if it still can be reproduced, for which there is not much info) and I have not changed my opinion. Since nobody has volunteered fixing this for all this time, I don't think it is worth keeping open. I closed it with the comment that if you would like to fix this, please reopen.
