### ISSUE TITLE
Some tree operators don't mark as dirty all relevant nodes

### ISSUE THREAD

**Issue by jheled** [CompEvol/beast2#198]
The tree operators Wide-Exchange, Node-Slide and Wilson-Balding don't mark all "relevant" nodes as 'filthy'. This is not a problem for likelihood evaluation, since it propagates the changes upwards anyhow, and the lowermost nodes are marked. However, for this can be a problem for other objects such as a function having the tree as an argument.

**Comment by rbouckaert** [comment]
Is this still an issue?

**Comment by jheled** [comment]
The TreeOperator now contains a markclades input - which is implemented for all current relevant operators.
