### ISSUE TITLE
BEAUti 2: Exception thrown selecting empirical base frequencies

### ISSUE THREAD

**Issue by alexeid** [CompEvol/beast2#201]
class beast.evolution.sitemodel.SiteModel != interface beast.evolution.sitemodel.SiteModelInterface
class beast.evolution.substitutionmodel.HKY != class beast.evolution.substitutionmodel.SubstitutionModel$Base
beast.evolution.sitemodel.SiteModel.substModel: java.lang.Exception: Can only handle amino acid data
beast.evolution.sitemodel.SiteModel.substModel: java.lang.Exception: Can only handle amino acid data
beast.evolution.sitemodel.SiteModel.substModel: java.lang.Exception: Can only handle amino acid data
beast.evolution.sitemodel.SiteModel.substModel: java.lang.Exception: Can only handle amino acid data
beast.evolution.sitemodel.SiteModel.substModel: java.lang.Exception: Can only handle amino acid data
beast.evolution.sitemodel.SiteModel.substModel: java.lang.Exception: Can only handle amino acid data
beast.evolution.sitemodel.SiteModel.substModel: java.lang.Exception: substitution model cannot handle data type

**Comment by rbouckaert** [comment]
It looks like this has been solved: import alignment, switch to HKY, switch to empirical frequencies does not throw an Exception any more.
