### ISSUE TITLE
Easy way to find example xml files of packages

### ISSUE THREAD

**Issue by gavryushkina** [CompEvol/beast2#204]
It would be convenient for users if there was an easy way to access example folder of different packages from BEAUti and BEAST. Then if you want to load an example xml for some package to BEATi, for example, you just hit some button and example nexus files pop up in a window.

**Comment by gavryushkina** [comment]
The same as newly opened issue #273 .

**Comment by tgvaughan** [comment]
Oops, sorry for the dupe.  We should have closed mine!
