### ISSUE TITLE
hardcoded java.library.path ?

### ISSUE THREAD

**Issue by pescobar** [CompEvol/beast2#213]
Hi,

When installing Beast-2.1.3 I found this line in the "bin/beast" script

```
java -Xms256m -Xmx1024m -Djava.library.path="$BEAST_LIB" -cp "$BEAST_LIB/beast.jar" beast.app.beastapp.BeastMain $*
```

I have beagle-libs installed in my system but beast could not find beagle-libs because they are in a non-standard location (not /usr/lib or /usr/local/lib). In our cluster $LD_LIBRARY_PATH environment variable points to all the directories in the system which contains libraries. I think this is a quite common setup in many computing clusters.

To make beast find the beagle-libs in my system I had to modify the script to add the $LD_LIBRARY_PATH environment varible. Like this:

```
java -Xms256m -Xmx1024m -Djava.library.path="$BEAST_LIB:$LD_LIBRARY_PATH" -cp "$BEAST_LIB/beast.jar" beast.app.beastapp.BeastMain $*
```

I think it would be nice if beast by default would use LD_LIBRARY_PATH to find all the available libs in the system. 

by the way, I also had to do the same fix for previous version Beast-1.8.0.

regards,
pablo.

p.s. In case you are interested, I contributed two build recipes for Beast to the EasyBuild project
https://github.com/hpcugent/easybuild-easyconfigs/pull/1054

**Comment by rbouckaert** [comment]
See #487
