### ISSUE TITLE
Error and Warning reporting in initAndValidate

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#23]
CalibratedYuleModel.initAndValidate() contains this code

```java
if (!_MRCAPrior.isMonophyleticInput.get()) {
  throw new Exception("MRCAPriors must be monophyletic for Calibrated Yule prior");
}
```

and

```java
 if (_MRCAPrior.isMonophyleticInput.get()) {
    System.err.println("WARNING: MRCAPriors must have a distribution when monophyletic for Calibrated Yule prior");
}
```
I hope the exception is caught by BEAST2 and passed in a nicer way to the user (but not sure).

But the System.err.println looks bad to me. How does a plugin issues a warning? I think We need a system wide facility.

### Comments on GC issue

 Project Member #2 higgs.ml

Is this an error condition or should this be treated as warning?

Sep 29, 2013
Project Member #3 jheled

Since I can't remember adding this part of the code, I am assuming it is one of your additions. I would rather not have any of this "magic" and always require the calibration points to be specified explicitly.

My report was more on the topic of error reporting by a plugin.
A user may want to add other monophyly constraints. This breaks the prior guarantee, but the code can still run, so my guess it is just a warning.

**Comment by rbouckaert** [comment]
The logger consolidation (#472) should have taken care of this.
