### ISSUE TITLE
BEAUTi's "Import Alignment" is missing helpful information on OSX

### ISSUE THREAD

**Issue by SimonGreenhill** [CompEvol/beast2#236]
The file picker in "Import Alignment" doesn't have useful path information (e.g. sidebar, recent choices, $HOME, desktop, etc), unlike "Load", which does have these useful things. 

This means that every time I want to import a nexus, I have to navigate from the root of my harddrive, until I get to /Users/me/path/to/nexus. Load is much less frustrating.

I *think* this is an OSX issue, as there seems to be an OSX specific check on L249 of `BeautiBase.java`.

![import](https://cloud.githubusercontent.com/assets/220169/4695364/40ac201e-584b-11e4-826c-05ff4a5afa5a.png)

![load](https://cloud.githubusercontent.com/assets/220169/4695363/40a8cd06-584b-11e4-9fd6-f441ab2e5b2b.png)

**Comment by rbouckaert** [comment]
closed  by 2fafd8fd61
