### ISSUE TITLE
Default prior distribution for BirthRate should be 1/X for Birth-Death models

### ISSUE THREAD

**Issue by genomescale** [CompEvol/beast2#239]
In BEAUTi 2 (2.2.0-pre), using StarBeast.xml, the default prior for BirthRate when a Yule species tree prior is selected is a 1/X distribution. When this is changed to a Birth-Death species tree prior, BEAUTi changes this to a uniform distribution. It doesn't make sense for the default prior on BirthRate to be uniform for the Yule model but not the Birth-Death model. BEAUTi should probably use 1/X distributions for the BirthRate prior in both cases.

**Comment by rbouckaert** [comment]
The reason for this difference in priors is that the Standard template uses a uniform prior on birth rate for Yule by default, so switching to Birth Death gives a uniform prior on the birth rate, which is consistent with that of the Yule prior that was switched from. A uniform birth rate prior leads to small trees, while a 1/X prior leads to very large trees.

Only when the StarBeast template is used, a prior on the species tree is needed to prevent the species tree collapsing, and 1/X for birth rate of Yule will do so (the default in the StarBeast template). The gene trees will ensure the species tree will not escape to infinite size in this case.

Anyway, the user can switch to whatever is suitable, so there is no need to change the current behaviour.
