### ISSUE TITLE
STARBEAST population size "Gamma Parameter" is mislabeled in BEAUTi 2

### ISSUE THREAD

**Issue by genomescale** [CompEvol/beast2#241]
The constant population size "Gamma Parameter" is the scale parameter of the PopMean distribution. However, the label "Gamma Parameter" is ambiguous as gamma distributions have two parameters, and the mouse-over text wrongly calls it the "Shape Parameter".

**Comment by rbouckaert** [comment]
Fixed by 3cb76fc8bb1f14f5265e3f873cfcc2160ae7a8a4
