### ISSUE TITLE
Beauti 2 hyperpriors for substitution matrix parameters

### ISSUE THREAD

**Issue by dcmarshall** [CompEvol/beast2#255]
In Beauti 2, in regards to the values that establish the shapes of distributions (e.g., M and S for the lognormal), the boxes for estimating those values appear as checked when the distribution is first chosen for the prior of a substitution rate matrix parameter, even though no hyperpriors for those values appear in the priors panel.  If those boxes are unchecked and re-selected, the hyperparameters then appear in the list.  

Note that this does not seem to happen for such distributions when they are selected for other parameters like birthrate2, gammashape, ucld.stdev, etc.

**Comment by rbouckaert** [comment]
Hi Dave,

Is it possible to give more details? I have not been able to reproduce this problem -- all parameters in priors (on substitution rates) are unchecked.

Cheers, Remco

**Comment by dcmarshall** [comment]
No problem.  If I use the version of Beauti that came with my Beast 2.1.3 download, and open a single-partition nexus file with DNA data (e.g., the anolis.nex file from the supplied examples folder), and just choose GTR for the site model and relaxed clock lognormal for the clock model, then go to the priors panel, I find that the alpha and beta parameters for the gamma (default) prior on rateAC, rateAG, etc. are all checked for estimation, even though there are no hyperpriors listed in the panel window.  If I un-check those boxes, and re-check them, the hyperpriors then appear.  The alpha and beta parameters for ucld.stdev do not appear as checked off, in contrast.

I did find out some more about it.  This happens only for the default gamma setting on rateAC (and the other substitution parameters) when it first appears upon opening of the priors panel.  If you change the rateAC prior distribution from the dropdown menu first (e.g., to beta), the additional parameters do not appear as checked off for estimation, and if you switch back to gamma then alpha and beta are not checked anymore!  So it has to do with the default loading only I guess.
