### ISSUE TITLE
BEAUti: NEXUS filename is used for tracelog filename, but removes the underscores

### ISSUE THREAD

**Issue by richelbilderbeek** [CompEvol/beast2#269]
If I use use BEAUti (fresh pull and install yesterdag) to generate a BEAST XML parameter file, it suggests an incorrect tracelog filename if the alignment filename has underscores.

From the alignment file `x.nex` BEAUti will suggest `x.log` correctly
From the alignment file `x_y.nex` BEAUti will suggest `x y.log` (replacing the underscore for a space)

To make sure if this was just the alignment its filename, I tested this by copying the alignment file. In the screenshots below, you see both suggestions from BEAUti.

![works](https://cloud.githubusercontent.com/assets/2098230/6230735/457025d4-b6c2-11e4-8491-fdfc35f5528d.png)
![doesnotwork](https://cloud.githubusercontent.com/assets/2098230/6230737/4819bb9c-b6c2-11e4-969a-496acb30d4c4.png)

**Comment by tgvaughan** [comment]
Hi @richelbilderbeek, I've had a look at this and it seems to be just that the text box in BEAUti is truncating the bottoms of the characters.  If you save and run the XML, the log file should be generated with the underscore in place.

**Comment by tgvaughan** [comment]
I'm closing this issue and opening a new issue (#270) specific to the truncation problem.

**Comment by richelbilderbeek** [comment]
Note to self: I observed a filename `a b` instead of `a_b` somewhere later in my multiple scripts. After the remark from tgvaughan, I thought the `a b` was written to the `.xml` parameter file. The parameter files are created correctly, however. I assume one of my regexes needs to be fixed instead.

Hi @tgvaughan, you are right at closing the issue. You guys/gals have done your part of the job excellently!
