### ISSUE TITLE
Improve accessibility of package examples

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#273]
BEAST 2 packages contain an `examples/` directory containing representative data sets and analyses.  When a package is installed, this directory is found in the `$PLATFORM_SPECIFIC_PREFIX/$BEAST_VERSION/$PACKAGE_NAME` directory.  The actual location of the package folder can only be found by clicking the tiny '?' button in the package manager.  This means that in order to load an example analysis or dataset users must:

1. Find a tiny, fairly nondescript button.
2. Remember a lengthy path.  (No copying is allowed from the dialog displayed by the '?' button.)
3. Enter this path by hand using a file chooser dialog.

To make matters worse, under Linux the prefix specifies a hidden directory which can only be accessed in the file chooser by typing the name of the hidden directory into a text field.

Can we maybe provide a simpler way to access these examples?  E.g. a File->Load example->Package_Name->chooser type menu structure?  Or perhaps a simple way to navigate to the example directories using the file choosers?  (Maybe a drop down menu of installed package example directories to navigate to.)

**Comment by alexeid** [comment]
Absolutely agree. This was a real pain at the workshop in Cesky Krumlov.

Alexei

**Comment by tgvaughan** [comment]
The above commit is in a separate branch named custom_file_selector.  I haven't put this in master as the existing file selection code includes special cases for OS X that I've ignored in my example.  (Interestingly, this special case is only implemented for the File->Load dialog, not File->Import alignment dialog.  It can't be too important then?)

Please let me know whether you think the new file selector is workable.

**Comment by rbouckaert** [comment]
Hi Tim, I like it very much. Just tried and it works on Mac as well. The File->Import in BEAUti may need a bit of work and should use the special case, but your implementation looks acceptable to me -- Mac users may not agree...

**Comment by alexeid** [comment]
The special case on OS X is important and should be called in both places in the software...

**Comment by rbouckaert** [comment]
After discussion with Tim, we came up with a way that preserves the precious OSX file chooser: by having a concept of current working directory, and being able to set it in a "File/Set current dir" menu with package-example directories as sub-menu choises, a user can set the working dir conveniently, then the file chooser can select files starting in the current directory. Beauti.g_sDir holds the working directory already, so it is just a matter of creating the menus and setting this variable.

**Comment by rbouckaert** [comment]
by 2fafd8f
