### ISSUE TITLE
Suggested add in wiki

### ISSUE THREAD

**Issue by richelbilderbeek** [CompEvol/beast2#276]
At http://www.beast2.org/wiki/index.php/DensiTree_How_To%27s the FAQ `Can I batch process tree set files?` has the following text, and I'd like to add an example:

```
Use the command line options to specify your settings, and use the -o <filename>

option to specify a file. The DensiTree is exported in png format to the specified file. 
```

My suggested lines to add (as I needed it):

```
Example:

densitree -o my_output.png my_input.trees
```

I thought the best way to do suggest this was by creating this issue, because I could not register for the wiki, nor is it AFAIK part of this repo. Hope you appreciate this.

**Comment by tgvaughan** [comment]
Thanks @richelbilderbeek, I've added your example.
