### ISSUE TITLE
FixMeanMutationRatesOperator with 1 partition

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#277]
In BEAUti, when there is one partition, and substitution rates are estimated (not default) and mean rates are fixed (default) the delta exchange operator with id FixMeanMutationRatesOperator will hang.

Possible solution: 
- delta exchange operator should fail in initAndValidate when there is one partition, hence nothing to exchange.
- delta exchange operator should warn in initAndValidate, and proposal() should not hang but just do nothing.

**Comment by alexeid** [comment]
Why is the deltaExchange even in the XML with this setting? Isn’t that the real bug? A hand-crafted XML for this setup wouldn’t have a deltaExchange in the XML.

**Comment by tgvaughan** [comment]
The FixMeanMutationRatesOperator is currently created during the
SiteModelInputEditor initialization, but the partition-specific mutation
rate parameters are added in by a custom connector method.  Couldn't we
move the creation of the operator to the custom connector?  This method
knows how many partitions there are, so it would then be easy to leave the
operator out entirely when only 1 partition exists.

**Comment by rbouckaert** [comment]
The logic for adding FixMeanMutationRatesOperator is built into BEAUti, which has a setting (accessible under the menu "Mode/Automatic set fix substitution rate flag") to automatically set up the FixMeanMutationRatesOperator. In the past, lack of this feature has caused quite a few people to set up analyses with identifiability issues (since both subst. and clock rate were set to be estimated) and users had to set the "Fix mean substitution rate"-flag by hand (which was often forgotten).

**Comment by alexeid** [comment]
Is this closed because it have been fixed to not produce buggy XML when there is only one partition? It would be good to include a message on how an issue has been resolved when closing an issue.
