### ISSUE TITLE
BEAUti may produce irrelevant warning

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#278]
How to reproduce:
Open BEAUti with SNAPP template
Import nexus file
Go to MCMC panel, where an recursive error is indicated in RealParameter.0, which is not part of the XML being produced.

Possible solution: suppress warning, or perhaps fix SNAPP template

**Comment by alexeid** [comment]
Fix template is 10x better than suppressing the warning. Otherwise we will end up with lots of weird tests in the codebase because of buggy templates, that will make it hard to navigate the BEAUti code.

**Comment by rbouckaert** [comment]
Fixed the SNAPP template to suppress the message. It was caused by having no value for clock.rate input on ClusterTree, and even though a default value is created, its constructor does not set the "value" input, which causes the warning. Also, updated the Parameter constructor to set these values (so without the template fix the warning disappears as well).
