### ISSUE TITLE
New BEAUti should import data partitions from BEAST 1.x files

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#29]
A minimum amount of parsing ability is required to extract taxa, sequences, dates and attributes from the XML files of BEAST 1.x. An importer for these is already available in dr. app.beauti.utils. 

This would be a great benefit for the transition between versions.

**Comment by rbouckaert** [comment]
BeautiAlignmentProvider has a method parseBeast1XML that imports simple alignments from BEAST 1 XML.
