### ISSUE TITLE
Move tree operator connections to tree prior sub templates in BEAUti

### ISSUE THREAD

**Issue by gavryushkina** [CompEvol/beast2#290]
Different tree prior models can require different types of trees or tree operators. It would be convenient if the connection of tree operators happened in the tree prior template rather than in the main template. 
So for all required operators, a connection like this:

```xml
<connect srcID='operatorID.t:$(n)' targetID='mcmc' inputName='operator' if='inposterior(Tree.t:$(n)) and Tree.t:$(n)/estimate=true and in posterior(treePrior.t$(n))'>
```

should go to each tree prior template with a unique operatorID (so the same operator in different tree prior sub templates has different ID's) 

This should work if we always have a tree prior when a tree is estimated.

**Comment by tgvaughan** [comment]
Off topic, but you need to quote code  (esp XML or HTML) using markdown's syntax to include it in the issue text.  For example, to include an XML fragment use:

    ```xml
    <my fragment/>
    ```

This also gives you syntax highlighting.

**Comment by gavryushkina** [comment]
Thank you. It is good to know.

**Comment by rbouckaert** [comment]
Good idea. I suggest we target the 2.3 release to get this done in order to ensure current 2.2 compatible template can be updated for this.

**Comment by gavryushkina** [comment]
If we don't fix this in the next release than we need to find a way to fix another issue: the FBD prior disconnects the operators from the standard template. So if the user chooses this prior and then decides to change it to another tree prior then the operators are still disconnected.

**Comment by gavryushkina** [comment]
There are also templates for BDSKY package that disconnect main tree operators.

**Comment by rbouckaert** [comment]
templates are updated now
