### ISSUE TITLE
It is impossible to remove a calibration prior for a taxon set once you created it in BEAUti

### ISSUE THREAD

**Issue by gavryushkina** [CompEvol/beast2#291]
Once you created a taxon set on the Prior panel in BEAUti. It is impossible to remove it. But it should be possible in case you added a wrong taxon in the clade for example.

**Comment by rbouckaert** [comment]
The taxon set can be edited, so you can just remove/replace the incorrect taxon by clicking the first button of the line with MRCA prior.

**Comment by gavryushkina** [comment]
But how can you actually remove it? I can only see how to edit it.

**Comment by alexeid** [comment]
Yes, but you might want to remove all calibrations. Or you might have added too many. You might have a multiple-calibration analysis and want to reduce the number of calibrations for a subsequent analysis. You shouldn’t be forced to keep the calibrations forever, it just adds clutter to the interface unnecessarily. It is really inelegant to not have a [-] button. It was a major issue at the workshop in Cesky Krumlov for many of the users.

**Comment by rbouckaert** [comment]
by 3de78dd
