### ISSUE TITLE
BEAUti does not display some components properly 

### ISSUE THREAD

**Issue by gavryushkina** [CompEvol/beast2#292]
There are two problems of the same nature with how BEAUti displays things: 
1. In FBD template there is a connector that disconnects the origin input from the tree prior if conditionOnRoot input is true. BEAUti doesn't display this disconnection immediately after the conditionOnRoot box is checked but only after some other action is performed. 
2. If you choose a gamma variation across sites and tick estimate box for the shape parameter then an exponential prior for the shape appears in the prior panel with estimate Mean checked. However there is no prior for the mean. It only appears after unchecking and checking estimate Mean.

**Comment by rbouckaert** [comment]
@gavryushkina  89ada01 should fix the problem, but let me know if it doesn't.
