### ISSUE TITLE
Incorrect operator optimisation when preBurnin is specified

### ISSUE THREAD

**Issue by gavryushkina** [CompEvol/beast2#306]
If preBurnin is specified then an operator can be 'optimised' to an extent when it is never accepted anymore. Optimising only  when sampleNr >= 0 (in doLoop in MCMC) seems to solve this problem but I am not sure if it might cause any other problems.

**Comment by rbouckaert** [comment]
But preBurnin is not different from normal running the loop or am I missing something? Perhaps changing the transform-input of the OperatorSchedule (which is normally hidden, but is an input to MCMC) could fix this problem as well?

**Comment by gavryushkina** [comment]
We call accept or reject methods on an operator only if  sampleNr >= 0 and these methods increase m_nNrAcceptedForCorrection and m_nNrRejectedForCorrection, which are used in calculating delta. So this may be the reason.

**Comment by rbouckaert** [comment]
Also needs updating in model-selection and SNAPP packages
