### ISSUE TITLE
Launchers should not include complete beast.jar but discover and load

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#309]
The windows and mac versions are much larger than the linux version because they include a copy of beast.jar in each executable. Keeping the beast.jar separate makes upgrading point releases a breeze: just replace the jar file. 

There may be an issue on mac when applications are launched from withing a dmg file and beast.jar cannot be found.

Related to #144

**Comment by tgvaughan** [comment]
Maybe we shouldn't even distribute beast.jar with the archives users
download from beast2.org.  The launcher could be responsible for
downloading this initially and subsequently checking for updates.  Of
course we'd have to cater to people behind firewalls, although if we stick
to HTTP this shouldn't be too much of a problem.

**Comment by rbouckaert** [comment]
by cec4254
