### ISSUE TITLE
Releases for China

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#310]
http://viewdns.info/chinesefirewall/?domain=github.com suggests github is blocked in China, which means the releases cannot be downloaded. I suppose this implies packages cannot be installed either.

beast2.org is accessible http://viewdns.info/chinesefirewall/?domain=beast2.org, so perhaps releases should be moved there. However, beas2.org is uni-hosted, which does not have a good track record for uptime, so having them in both places would be safest. What about packages? Perhaps allow alternative sites for download?

BTW the beast user group on google is blocked as well - markmail.org allows you to read posts (and is more responsive than google), but does not allow new posts.

**Comment by tgvaughan** [comment]
Is this really a good reason for moving away from GH?  Maybe we could just
mirror the releases on the beast2 website?

**Comment by alexeid** [comment]
Agree.

**Comment by walterxie** [comment]
Google is shutting down Google code, you have no choice now.

**Comment by rbouckaert** [comment]
A cron job copying the latest release and latest packages to beast2.org from wherever they are hosted could do the trick. The package manager could be updated to look at beast2.org if it cannot get it from its original location.

**Comment by rbouckaert** [comment]
Looking at
http://viewdns.info/chinesefirewall/?domain=github.com
as well as https://en.wikipedia.org/wiki/Censorship_of_GitHub
github is no longer blocked.
