### ISSUE TITLE
TreeLikelihood does not scale ascertainment correction

### ISSUE THREAD

**Issue by gavryushkina** [CompEvol/beast2#315]
The ascertainment correction is not scaled when TreeLikelihood is scaled. So if scaling is used it should also scale the correction or scaling should not be used with ascertained alignments.

**Comment by rbouckaert** [comment]
When ascertainment correction is used, the TreeLikelihood.calcLogP() uses patternLogLikelihoods to calculate logP with ascertainment correction. patternLogLikelihoods contains all log-likelihoods that are scaled when scaling is used. So, the correction -- which is based on patternLogLikelihoods -- is scaled as well. Where else do you think scaling is required?

**Comment by gavryushkina** [comment]
Right. I think I mixed it up with something. Sorry.
