### ISSUE TITLE
NullPointerException when RealRandomWalk is first operator called

### ISSUE THREAD

**Issue by Anaphory** [CompEvol/beast2#317]
It seems that the RealRandomWalk operator tries to resolve a null pointer when it is the first operator called.

For the Beast xml file listed below, I get 
````
java.lang.NullPointerException
    at beast.core.StateNode.startEditing(StateNode.java:202)
    at beast.core.StateNode.getCurrentEditable(StateNode.java:42)
    at beast.core.Input.get(Input.java:333)
    at beast.evolution.operators.RealRandomWalkOperator.proposal(RealRandomWalkOperator.java:40)
    at beast.core.Operator.proposal(Operator.java:81)
    at beast.core.MCMC.doLoop(MCMC.java:412)
    at beast.core.MCMC.run(MCMC.java:347)
    at beast.app.BeastMCMC.run(BeastMCMC.java:305)
    at beast.app.BeastMCMC.main(BeastMCMC.java:519)
````
if the weight of Scaler is any lower, and with what appears to me a 1/6 chance when trying varying seed values. In the other case, Beast runs as expected. This indicates to me that something is wrong with RealRandomWalk as first operator being run (something uninitialised?).

````
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<beast version='2.0'
    namespace="beast.core:beast.core.parameter:beast.math.distributions:beast.evolution.operators:parameterclone.splitandmerge">
    <run chainLength="10000" id="mcmc" preBurnin="1" spec="MCMC">
        <state id="state" storeEvery="100">
            <input name="stateNode">
                <parameter estimate="false" id="parameters" lower="0.0"
                    upper="1.0">
                    0.5 0.5 0.5 0.5
                    </parameter>
            </input>
        </state>
       
        <distribution spec="Prior" x="@parameters">
            <distr spec="Uniform"></distr>
        </distribution>

        <operator id="Scaler" spec="ScaleOperator" scaleFactor="0.25"
            weight="5">
            <parameter idref="parameters" />
        </operator>
        <operator id="Mover" spec="RealRandomWalkOperator" windowSize="2.0"
            weight="1">
            <parameter idref="parameters" />
        </operator>
       

        <logger logEvery="100">
            <log idref="parameters"></log>
        </logger>
    </run>
</beast>

**Comment by Anaphory** [comment]
I get essentially the same traceback when trying to use my own MergeOperator, so I'll try to debug it myself, but if someone knows the solution, I'll appreciate that.

**Comment by Anaphory** [comment]
It appears that the `public index` property of the SateNode encapsulating `parameters` is not set, and still has the value `-1`, even though from the accompanying comments I would expect it to be `0`. Is this a problem in Beast (such that the intialisation of one of those objects should have specified this), or should I specify the parameter values differently?

**Comment by Anaphory** [comment]
Aha, so `MergeOperator.proposal()` has an outer wrapper of `try { ... } catch (Exception e) { return Double.NEGATIVE_INFINITY }`. Therefore in the first pass, the NullPointerException is caught, and after that, the `.index` is magically set, and everything works fine. Adding such a `try … catch` to other operators fixes the symptoms, but this does not look like it is the intended solution.

**Comment by tgvaughan** [comment]
Hi @Anaphory, the XML you posted above seems to have a buggy `<state>` element:

1. The `parameters` element has `estimate="false"`.  This should be `estimate="true"` or just omitted - true is the default.
2. The `parameters` element describes a RealParameter which is itself a StateNode, but you've included it as a child of a `<stateNode>` element.  I don't think this makes sense.  Instead, the RealParameter itself should correspond to the `<stateNode>` element.

The following `<state>` seems to work.

```xml
<state id="state" storeEvery="100">
  <stateNode spec='RealParameter' estimate="true" id="parameters"
        lower="0.0" upper="1.0">
    0.5 0.5 0.5 0.5
  </stateNode>
</state>
```

The stack trace you gives hints that this is the problem.  The null pointer exception in startEditing() usually signifies that the state has not been defined correctly.  (Not the best error reportage there - should fix this.)

**Comment by alexeid** [comment]
BTW: A nasty design decision was made early on to use try { … } catch (Exception e) in the BEAST2 code. It is a terrible pattern to use regularly because as you point out it even catches RuntimeExceptions. Slowly but surely I hope to weed out such code and replace with the appropriate catch which should almost always be a more specific exception.

**Comment by tgvaughan** [comment]
I believe the XML problem I posted above is the issue here rather than a bug in the source.  (A separate issue could perhaps be opened re the user unfriendly error message.)
