### ISSUE TITLE
<run> without <operator> leads to NullPointerException

### ISSUE THREAD

**Issue by Anaphory** [CompEvol/beast2#318]
A Beast xml file with a `<run>` tag containing no `<operator>` is parsed as valid, but the operator choice raises a NullPointerException.

**Comment by rbouckaert** [comment]
There is code for requiring at least one operator, which is commented out -- so there must be a reason (perhaps for unit tests) to not enforce requiring at least one operator, though I'm not quite sure what it was.

**Comment by tgvaughan** [comment]
Make sure the check for this is within the MCMC class - there are plenty of
Runnables that don't use operators!
