### ISSUE TITLE
Newick tree is wrong 

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#33]
input original tree below into newick tree TreeParser, and then BEAST 2 output a different tree as inputted.

BEAST 2 output:
0.036831999999999976,1217:(615:(613:(612:(611:(2:0.0,3:0.006647999999999987):0.09753100000000003

input:
0.036831999999999976,(((('NZAC03011539|Plot_4|Subplot_P|LBIinv0013|G6|MT-CO1':0.0,'NZAC03013498|Plot_5|Subplot_A|LBIinv0012|B2|MT-CO1':0.006647999999999987):0.09753100000000003,

the number of brackets increased from 4 to 5.

original tree is attached.
### Comments from GC issue

 Project Member #1 alexei.drummond

Not sure this is a bug with TreeParser class. We should focus on issues with BEAST2, rather than code that uses BEAST2 classes.

Status: New
Labels: -Priority-High Priority-Low

**Comment by rbouckaert** [comment]
Could not reproduce.
