### ISSUE TITLE
Polish GUI for "import alignment" in BEAUti

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#337]
Searching through the combobox for adding an alignment when there are many other packages loaded is cumbersome.

Having a dialog with buttons, or just a JList to pick from with 'Import alignment' as default would be a bit nicer.

**Comment by alexeid** [comment]
We should just make import alignment be its own menu item and use some other mechanism for the template loading. Anything that requires a second click is annoying. There should be a direct top-level way to load an alignment that doesn’t require you to confirm the decision a second time.

**Comment by rbouckaert** [comment]
That is exactly how it used to be, till the functionality of the + button on the partition panel was made to do the same as the File/Import alignment menu...
Anyway, having a menu, one for each partition that can be added would be another option, either as submenu of File/Import, or all entries under File.

**Comment by rbouckaert** [comment]
closed by eb4c06a
