### ISSUE TITLE
Gamma quantiles

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#343]
In BEAUti priors tab
gamma [alpha (shape)=0.001 and a beta (scale)=1000

Beauti displays 8.73e-10 for the median.  In R
> qgamma(.5, shape=.001, scale=1000)
[1] 5.244206e-299

Why the discrepancy?

**Comment by tgvaughan** [comment]
The apache math GammaDistribution class allows you to set the precision of the quantile estimates.  

```java
public GammaDistribution(RandomGenerator rng,
                 double shape,
                 double scale,
                 double inverseCumAccuracy)
```

If you don't set this then the default value of 10^-9 is used (http://commons.apache.org/proper/commons-math/apidocs/src-html/org/apache/commons/math3/distribution/GammaDistribution.html#line.37).

**Comment by alexeid** [comment]
So, set it to 10^-99? Or increase the exponent by 1 until convergence? Any other ideas?

**Comment by tgvaughan** [comment]
I vote against increasing the threshold until convergence simply because there's already a root finding algorithm doing this inside the inverseCumulativeProbabiltiy method so we'd wind up with nested root finding methods!  Setting it to 10^-320 gets agreement with R's result for Remco's example above.  Maybe simply make the tolerance a bit smaller and put a little asterisk next to BEAUti's quantile numbers stating this tolerance?  We're always going to be bitten by rounding errors at some point, especially with distributions as evil as Remco's example...

**Comment by alexeid** [comment]
I agree. Decrease the tolerance. In BEAUti I don’t think there is a cost to decreasing it to a very small number, since the GUI is only doing this calculation infrequently.

Remco’s example is for a distribution that is very often used and I believe it is the default distribution for some parameters. So it would be nice if it worked for that case.

**Comment by tgvaughan** [comment]
Hrm, ParametricInputEditor uses the ParametricDistribution instance that is part of the beast model.  This maintains a single instance of the apache math `Distribution` class.  The tolerance can only be set via the Distribution constructor, so the only way to get BEAUti to use a different tolerance is to have each ParametricDistribution maintain two distinct Distribution instances.  As the abstract ParametricDistribution doesn't know enough to create these instances, code needs to be added to each of its subclasses.  Some of these are probably not in the core...

**Comment by rbouckaert** [comment]
Perhaps we can report in BEAUti that numbers shown in below the density graph are within the tolerance of 1e-6, in case these reported  numbers get within twice the tolerance (2e-6). E.g. by adding an asterisk to the number and a line below the last number.

**Comment by alexeid** [comment]
We should decrease the tolerance substantially. The tolerance is too high at the moment. Gamma(0.001, 1000) is a quite standard prior.

**Comment by tgvaughan** [comment]
If accurately reporting the quantiles for Gamma(0.001, 1000) is required, we need to force a tolerance of _at most_ 10^-300.  Is this wise?

**Comment by alexeid** [comment]
What is the downside? Has anybody investigated the computational costs?

**Comment by tgvaughan** [comment]
Good question.  I just get a dirty feeling when setting tolerances that close to Double.MIN_VALUE :-)

**Comment by rbouckaert** [comment]
This gives results for small values, but does not affect larger values:
1. set max iteration in BrentSolver to 1000
2. replace in AbstractContinuousDistribution.inverseCumulativeProbability

the call

      double root = UnivariateRealSolverUtils.solve(rootFindingFunction,
        		bracket[0], bracket[1], getSolverAbsoluteAccuracy());

with an adaptive solver accuracy, like so:

        double eps = 10.0 * getSolverAbsoluteAccuracy();
        double root = 0;
        while (Math.abs(root) < 1000*eps && eps > 1e-320) {
        	eps /= 10.0;
                root = UnivariateRealSolverUtils.solve(rootFindingFunction, bracket[0], bracket[1], eps);
        }
        if (Math.abs(root) < eps) {
        	root = 0;
        }

This gives the correct answer for the originally posed problem.

**Comment by tgvaughan** [comment]
Great news, Remco.  We'll still need that asterisk though! :-)

**Comment by alexeid** [comment]
Is there a speed cost for that solution?

**Comment by rbouckaert** [comment]
There is a speed cost when a cummulative distribution is close to 0 (<1e-9).

I am not aware of any call to inverseCumulativeProbability from anything during the MCMC, except for the relaxed clock model (and non-default Gamma site models, though probably only for large values). Other calls are from pre- (like BEAUti) and post-processing tools where speed does not matter much anyway.  

A quick test with the testRelaxedClock.xml shows there is no measurable actual impact on the relaxed clock though.

**Comment by rbouckaert** [comment]
by e7a6af5
