### ISSUE TITLE
Uncaught NullPointerException for empty StartValue of Input<List<>> constructor

### ISSUE THREAD

**Issue by Anaphory** [CompEvol/beast2#345]
Some of the `Input` constructors do helpfully inform me about “Programmer Errors”. But if a `List<>` type input is required, and `startValue` is not given, the program dies, complaining about a cryptic `java.lang.NullPointerException` at beast.core.Input.determineClass (Input.java:529). Is there a way to check for this case of Programmer Error and report it, as well?

**Comment by rbouckaert** [comment]
As far as I know, introspection does not allow you to check whether the type of Input is List or otherwise, unless its value is initialised, so I am afraid we have to live with this.

**Comment by Anaphory** [comment]
Would it be appropriate to add a something like

    System.err.println("Programmer error: Lists must be initialised for any Input constructor");

to one of the `try/catch` blocks encountered in this process? For example in `Input.determineClass()`?

**Comment by Anaphory** [comment]
Sorry, I just saw that there is such a message (Input.java:532ff), but I did not see it printed, because the `NullPointerException` occurs in 529:

    id = method.invoke(plugin).toString()
