### ISSUE TITLE
StarBeastStartState should take bounds of popMean in account

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#350]
Bounds are not checked when setting this parameter, resulting in non-starters.

**Comment by tgvaughan** [comment]
Maybe we could make Parameter.setValue raise an out of bounds exception if
the argument is outside the boundaries?  This would force package
programmers to deal with this situation rather than forget about it.

**Comment by rbouckaert** [comment]
This was initiated by http://markmail.org/message/4aoor6tz64onr5fy where a user to chanced bounds that by default would not cause any problems. In this case, StarBeastStartState set the popMean value outside the user's bounds. Not sure whether an out of bounds exception would help the user much, and it would most likely not be picked up by the developer who works mostly with default values -- there is only so much one can test for.

**Comment by tgvaughan** [comment]
But StarBeastStartState shouldn't be able to set the value of popMean
outside of the bounds, should it?  At the moment there's no pressure on
developers to query getLower() or getUpper() at all so it's easy to forget
about them in operators and initializers.  If setValue were to raise a
special OOB exception, the compiler would force devs to provide a catch and
deal sensibly with this situation.

**Comment by rbouckaert** [comment]
I see, yes that makes sense!

**Comment by tgvaughan** [comment]
Occasionally I do. :-)

**Comment by tgvaughan** [comment]
Hrm, I guess it'd be difficult to do this in a backward-compatible way though.

**Comment by alexeid** [comment]
So how many ways will the 2.3 release break the core API? It would be nice if we had a way to answer this...

**Comment by tgvaughan** [comment]
@rbouckaert regarding Exception handling, I wasn't at all suggesting setValue raise an `Exception` - which I agree would be a terrible idea, but rather an instance of a specific OOB subclass.

**Comment by rbouckaert** [comment]
by 63888cb
