### ISSUE TITLE
Guess button

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#358]
The 'guess' button on the taxon set panel may not be intuitive, especially for people that put a lot of thought and care into setting up a file with taxon to species mappings.

Perhaps 'configure' would be a better label.

**Comment by tgvaughan** [comment]
It's probably important to emphasize that the function of this button is to automatically assign trait values based on taxon labels or an external file.  Something like "Automatically configure" or even "Load" would be better than "Guess".  (I'm also thinking about the other contexts in which this button appears.)
