### ISSUE TITLE
AppStore needs a friendlier command line interface

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#364]
Currently, command line users need to know the fully qualified class name of the package app they want to launch.  The following would be great:

* `appstore -help`
* `appstore -list [package]`
* `appstore <class|app_name>`

There's currently no actual "app_name" associated with package apps, but the description field seems like an appropriate surrogate.

**Comment by rbouckaert** [comment]
Like that idea. Typing 
  appstore "Path sampler"
is a lot more attractive than
  appstore beast.app.tools.PathSampler
Take care with spaces, and perhaps make it case unsensitive.
