### ISSUE TITLE
Entities in StateNode IDs

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#366]
Entities (like &amp;) do not get represented properly in the state file, which makes restoring from them impossible.

**Comment by tgvaughan** [comment]
For this reason  one of my toString() methods ends with this:
```java
// Unfortunately, we must behave differently if we're being
// called by toXML().
StackTraceElement[] ste = Thread.currentThread().getStackTrace();
if (ste[2].getMethodName().equals("toXML"))
    return sb.toString().replaceAll("&", "&amp;");
else
    return sb.toString();
```

**Comment by rbouckaert** [comment]
There are 4 more entities (' " < >) to deal with.

**Comment by rbouckaert** [comment]
By 47458b54060da057a002823d39bf9b03ee66ea3b
