### ISSUE TITLE
TreeParser fails to correctly parse node metadata

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#367]
TreeParser cannot handle metadata that include vectors such as those produced by TreeAnnotator.

**Comment by tgvaughan** [comment]
It also fails to strip the leading `&`.   The boundaries for nexus comments are `[&` and `]`, not `[` and `]`.

**Comment by tgvaughan** [comment]
This issue is closed by d2dcd1607b027f57444230d5e9cc807ddd1c626f as vectors no longer cause the parser to crash and leading '&'s are automatically stripped by the lexer.

**Comment by alexeid** [comment]
I know that some code around the place expected the ‘&’ in the names (maybe beast-graphics?), so this might break some stuff, but I definitely agree that the lexer should consumer the ‘&’ characters.

**Comment by tgvaughan** [comment]
If this becomes an issue we can update the production rule for node annotations.  Currently this is
```
meta: '[&' attrib (',' attrib)* ']' ;
```
but it could become
```
meta: '[' '&'? attrib (',' attrib)* ']';
```

**Comment by tgvaughan** [comment]
Woops, I misread you the first time.  You're saying that some code anticipates TreeParser not stripping the `&` and is forced to handle this itself?  I was thinking of the few places where tree strings do not actually include the `&` in the annotation, usually to avoid using XML entities.  Both situations may cause problems, but while the mine can be fixed by making the parser less strict (obeying what @lmaurits informed me is called [Postel's law](https://en.wikipedia.org/wiki/Robustness_principle)), I think yours can only be dealt with by "fixing" the downstream code... :-/
