### ISSUE TITLE
RPNCalculator and spaces

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#369]
RPNCalculator interprets spaces as separators, which causes problems when they occur in IDs.

E.g. "A_1 B_2 *" is fine, but "A  1 B 2 *" is not.

**Comment by tgvaughan** [comment]
Maybe the RPNCalculator lexer should handle strings and/or escaped spaces?

**Comment by tgvaughan** [comment]
Or maybe we should forbid spaces in IDs?  (Sounds like putting spaces in variable names.)

**Comment by jheled** [comment]
I had the same problem with Script, so I added the "argnames" mapping to
map the element to a name.

-Joseph

**Comment by rbouckaert** [comment]
RPNCalculator has a List<Parameter> input (should be List<Function>?), from which "argnames" can be derived. 
Processing the expression by testing whether it startsWith any of the parameter IDs may be sufficient to fix this.

**Comment by jheled** [comment]
not for "a 1" and "a 2", if I understand you correctly.

**Comment by rbouckaert** [comment]
What I meant is that currently the first step is splitting the expression by space. If the split component matches the start of an ID, look further whether the complete ID can be constructed, if necessary by adding more split components.

So "A 1 B 2 *" with IDs "A 1" and "B 2" will be split into ["A", "1", "B","2","*"] and "A" is prefix of "A 1", so looking to the next component shows it matches. This will work as long as none of the IDs are prefixes of any of the other IDs. Working with "A" and "A 1" will mess things up.

Hmm, perhaps qoutes are a better idea, but then we have to deal with qoutes in IDs (e.g. "Old man's beard") and require a bit more advanced machinery.

**Comment by jheled** [comment]
I opt for either "argnames" or "don't put spaces in ids you want to use
inside an RPN"

-Joseph

**Comment by tgvaughan** [comment]
@rbouckaert yikes!  Sounds like that strategy could lead to some horrendous parsing ambiguities....

**Comment by tgvaughan** [comment]
This problem reared its ugly head at the Taming the BEAST workshop when somebody was using their own data... :-/

**Comment by alexeid** [comment]
The problem is easy to workaround, but very hard for a user to diagnose which is why I think it should be high priority.

**Comment by tgvaughan** [comment]
I think the problem shouldn't be solved at the RPNCalculator level but at the BEAUti level when the partition labels are defined.  It's just a matter of sanitisation.
