### ISSUE TITLE
Maybe Node.getChildren() should return an unmodifiable view?

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#370]
This is what happens currently:
```java
public List<Node> getChildren() {
    final List<Node> copyOfChildren = new ArrayList<Node>();
    copyOfChildren.addAll(children);
    return copyOfChildren;
}
```
Instead, can we not simply use the following?
```java
public List<Node> getChildren() {
    return Collections.unmodifiableList(children);
}
```

**Comment by rbouckaert** [comment]
Does Collections.unmodifiableList return a mutable copy of the list? What if that caller of getChildren want to manipulate the list (not sure whether that makes a lot of sense, but it is allowed at the moment).

**Comment by jheled** [comment]
we should document exactly what is "allowed" and what is not, for the cases
where one can't enforce it with Java.

I think it should not be legal to change the children that way :)

Also, when I was doing code speed improvements I was amazed to find out how
much speed was gained by changing seemingly "innocent" calls that had
enough overhead.

Whatever we do, I think it is essential to have at least one "fast and
overhead free"  interface for traversing binary trees.

-Joseph

**Comment by jheled** [comment]
Seems like using unmodifiableList should not incur a performance hit.

http://stackoverflow.com/questions/6604529/is-there-any-performance-risk-to-collections-unmodifiablelist

**Comment by tgvaughan** [comment]
No, the view is "unmodifiable": http://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#unmodifiableList%28java.util.List%29.  The elements themselves are modifiable (hence this is not actually immutable).

Re performance, I think this is _more_ efficient than creating a whole new copy of the child list every time getChildren is called.  This simply returns a different view of the same list.

**Comment by tgvaughan** [comment]
@rbouckaert  modifying the list of returned children when those modifications aren't reflected in node.children is a pretty confusing way to code, don't you think?  I think it's more likely that an API user would expect 
```java
List<Node> kids = node.getChildren();
kids.remove(0);
```
to delete a child node.  Currently this is allowed, but it doesn't do what the programmer might expect (despite the javadoc).  Using an unmodifiable would cause this to raise an `UnsupportedOperationException`, alerting the programmer to their folly.

**Comment by tgvaughan** [comment]
Unfortunately `UnsupportedOperationException` is a `RuntimeException` so the compiler won't catch it, but at least it prevents code from becoming silently broken.

**Comment by tgvaughan** [comment]
Yikes, now some unit tests aren't passing.  Sorry for not checking that before committing...  Looking into this now.
