### ISSUE TITLE
Default memory allocation for TreeAnnotator

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#373]
With current day analyses, TreeAnnotator can easily run out of memory. Default allocation is 1GB, but could comfortably fit on modern computers with 4GB, so default memory allocation should be increased.

**Comment by tgvaughan** [comment]
Is it possible that TreeAnnotator's current memory usage is a bit wasteful?  For instance, is it necessary to hold all logged trees in memory simultaneously?  Unless it's way too slow, multiple passes through the log file might be a better option.
