### ISSUE TITLE
BEAST JRE discovery is fragile

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#376]
AppStore directly assembles a command to invoke the package app. This is quite fragile, as it a) requires the java executable to be in the user's PATH and b) assumes that this is the correct executable to use.

For instance, this was broken on my system (stock Debian) where java 7 is still the system java, but where I have installed java 8 separately. A standard solution is to provide a JAVA_HOME environment variable pointing to the root of the desired JRE. This was addressed in issue #375.

This solution only addresses the issue on Linux and potentially OS X and only in a relatively flimsy way. We should think about more general solutions to these issues. The most heavy-handed but probably the most robust would be to package the entire JRE with BEAST. This is about 60 MB, but that might be a small price to pay. (I believe this is what Geneious does.)

**Comment by rbouckaert** [comment]
Weka offers a choice of including a JVM or not (http://www.cs.waikato.ac.nz/ml/weka/downloading.html) which is 30MB difference for Java 7. Java 8 will probably a bit more. It probably solves a few hard to track problems (especially with OSX) trying to launch with other than Java 8 versions.

**Comment by alexeid** [comment]
Users in the USA and western Europe wouldn’t blink if the download was 100Mb in size. It is only internet-poor countries like NZ where download size matters a tiny bit. And within Universities NZ is fine as well.

**Comment by tgvaughan** [comment]
Regarding @rbouckaert's concern over dealing with multiple entry points when the JRE is bundled, maybe section 7.3.8 of [this page](https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html) is helpful.

**Comment by tgvaughan** [comment]
Doh - just noticed that "multiple entry points are supported only for Linux and Windows applications"...

**Comment by rbouckaert** [comment]
I think I got it sorted for OSX, so that will be enough. Don't think Linux requires a JRE to be bundled, just Windows and OSX.

**Comment by tgvaughan** [comment]
I'm not sure about your Linux statement - this is precisely where I've been having trouble! :-)

**Comment by rbouckaert** [comment]
The launcher mechanism captures whether Java 8 is used or not, and warns appropriately if it isn't. The v2.4.0 release does not have a version with Java bundled any more, since I hope that the launcher provides sufficient protection against incorrect java versions.
Perhaps this issue can be closed?

**Comment by tgvaughan** [comment]
The issue had to do with the AppStore failing to discover the correct version.  I can't remember, does this use the launcher?

**Comment by rbouckaert** [comment]
Yes it does, through beast.app.tools.AppStoreLauncher.

**Comment by rbouckaert** [comment]
I think this is no longer an issue, given that the way the applauncher works these days no longer requires building the command line string any longer.
