### ISSUE TITLE
Beast v2.0.2 / Reconstruction of ancestral state/ Improper handling of missing data?

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#38]
Hi guys,

First of all, congratulations to the fabulous work done with the new version of Beast... Every time I come back to analyses after a few months of field or lab work, I am amazed by new developments...

Just a comment, I tried to link a morphological character to a species tree (in a *Beast framework)... and it seems that Beauty always creates a new state for missing data (I code them using question marks)... I indeed get this:

``` xml
<userDataType codeMap="?=0,no=1,yes=2,? = 0 1 2 " codelength="-1" id="traitDataType.crenulated" spec="beast.evolution.datatype.UserDataType" states="3"/>
```

I tried to edit the xml by replacing the above code by:

``` xml
<userDataType codeMap="no=0, yes=1, ? = 0 1" codelength="-1" id="traitDataType.crenulated" spec="beast.evolution.datatype.UserDataType" states="2"/>
```

And I also updated dimensions in the substitution model...

But it generates an error from the Beast:
"Error 110 parsing the xml input file
validate and intialize error: Could not find code ? in codemap" 

Am I missing something?

Proper handling of missing data is important to me, because I often (need) exclude the outgroup state from the analysis...

Thanks in advance!
### Additional comments from GC issue

Sep 1, 2013
Project Member #1 dong.w.xie

it needs further investigation to see if this is duplicated to issue #37

**Comment by rbouckaert** [comment]
This used to be an issue in BEAST-classic, but is no longer a problem.
