### ISSUE TITLE
Rename AppStore.

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#389]
From Wikipedia:

```
An app store (or app marketplace) is a type of digital distribution
platform for mobile apps.
```

This doesn't describe the beast 2 AppStore, which is simply a program that launches available package apps.  It also personally makes me immediately think of Apple.  Can we please rename it to something else?  Maybe "PAL" for Package App Launcher? BeastPAL?

**Comment by alexeid** [comment]
App Launcher?

**Comment by rbouckaert** [comment]
Though I admit the current name is a bit unfortunate, I am not in favour of renaming bits and pieces regularly -- I still remember the add-on/package transition. There is as lot of work involved in updating all documentation (tutorials, website, blog posts, book, etc.) and does not give a solid impression of the software. If there is a good case to rename, perhaps we can keep the AppStore around as symlink to ease the transition (would work on mac & linux, not sure about windows).

**Comment by alexeid** [comment]
I don’t like the AppStore name. I think it is worth changing it. Names are important. We should talk about them before we make them up. I remember it took at least 2 sessions at the pub and 10 people to come up with the BEAST name, and there were many many worse ones along the way.

**Comment by tgvaughan** [comment]
Hi Remco, I definitely agree that renaming things is hard and painful.  How many uses of the AppStore are there at this point though?  Besides my own unpublished ACGAnnotator, there only appears to be the BEAST model spreadsheet app.

The reason I brought this up was that very soon I'm going to be directing people to open the [insert name here] and launch ACGAnnotator to perform an integral part of a bacter analysis.  I'm just trying to make sure this instruction will be as neat and confusion-free as possible.

Once these kinds of instructions are in place in tutorials and web pages it's going to be very painful and confusing to rename.  Don't we have a window of opportunity here?

**Comment by alexeid** [comment]
Tim: Why are you using the AppLauncher for ACGAnnotator anyway? I don’t even understand its purpose. We already have an app launcher, it is called the operating system :)

**Comment by walterxie** [comment]
The original idea is to find and launch every package from one place.

Walter

**Comment by alexeid** [comment]
Modern operating systems have facilities for finding apps. And the installation process presumably organises things in the file system in a sane way.

**Comment by tgvaughan** [comment]
Simply because BEAST 2 already has this neat way of bundling up package-specific apps.  This means that I don't have to write a wall of text on (or indeed even find out for myself) how to launch these apps under Windows, Linux or OS X.

Actually, it would be a lot more than a wall of text.  I'd need a launch script for Linux, some sort of packaged (and signed!) app for OS X, and who knows what for Windows...

The AppLauncher solution works really well.  I've improved the launcher by giving it a nice and friendly CLI.  Under Linux, a typical session looks like this:

```
$ appstore -help
AppStore: Run installed BEAST 2 package apps.

Usage:
        appstore
        appstore -help
        appstore -list [package_name]
        appstore <app_class_name|app_description>

$ appstore -list
Available package apps:

Package         | Class Name      | Description
----------------|-----------------|-----------------
bacter          | ACGAnnotator    | ACGAnnotator
BEASTLabs       | SpreadSheet     | BEAST model spreadsheet

$ appstore ACGAnnotator -help
ACGAnnotator - produces summaries of Bacter ACG log files.

Usage: appstore ACGAnnotator [-help | [options] logFile [outputFile]

Option                   Description
--------------------------------------------------------------
-help                    Display usage info.
-positions {mean,median} Choose position summary method.
                         (default mean)
-burnin percentage       Choose _percentage_ of log to discard
                         in order to remove burn-in period.
                         (Default 10%)
-threshold percentage    Choose minimum posterior probability
                         for including conversion in summary.
                         (Default 50%)
```

Of course this can also all be accomplished through the GUI.  Without any command line arguments, appstore presents:
![launcher](https://cloud.githubusercontent.com/assets/512538/8321271/d175f5d0-1a78-11e5-8251-7a482711fa2f.png)
and double-clicking ACGAnnotator brings up:
![annot](https://cloud.githubusercontent.com/assets/512538/8321291/0e01563e-1a79-11e5-88b0-918e4c9a69c1.png)

**Comment by alexeid** [comment]
Okay. I see how this can be useful. A slightly more parsimonious approach would be to have either the BEAST app or BEAUti app handle this job. It would also fix the name issue.

**Comment by tgvaughan** [comment]
Hey Alexei, I really like this idea.  I was thinking about this on the way to work this morning though and I came to the conclusion that it's not super-easy to get this to work except in the CLI case.  In the GUI case you you need some way for users to run the package app launcher instead of BEAST or BEAUti.  I suppose we could have the launcher run from a menu item inside BEAUti or from a button on BEAST's file selector, but to me this seems more awkward than just double-clicking an icon from the BEAST application directory.
