### ISSUE TITLE
BEAST 2.3.0 doesn't use Mac OS X look and feel...

### ISSUE THREAD

**Issue by alexeid** [CompEvol/beast2#395]
![screen shot 2015-07-22 at 3 48 06 pm](https://cloud.githubusercontent.com/assets/906825/8826772/1c20c3d2-3089-11e5-8312-8d733104c5a9.png)

Clean install of BEAST 2.3 on OS X Yosemite 10.10.4 give this look and feel...

**Comment by rbouckaert** [comment]
This is how it looks on OSX 10.9.5 -- pretty much the same, except window bar differs.

![beast2 1 3](https://cloud.githubusercontent.com/assets/3612959/9348763/aed6b53a-468f-11e5-8a6c-2258a01e2872.png)

BeastMain calls Utils.loadUIManager(), which is supposed to set up the look and feel. What do you think should be changed?

**Comment by rbouckaert** [comment]
On Linux we had

**Comment by alexeid** [comment]
Why re-opened?

**Comment by alexeid** [comment]
But you could try this for Linux, because it seems to be defaulting to Metal:

UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

**Comment by rbouckaert** [comment]
I trust that it looks good on Windows, but I think it is hard to argue the default look for Linux is preferable. So, why don't we have some special code for Linux, just like for OSX. Sophisticated users can always override it, of course.

**Comment by alexeid** [comment]
because linux has a thousand flavours and users with a thousand different ideas of what looks great. Did you try some code like this to see what options you have and what the "system" look and feel is for your Linux installation:

UIManager.LookAndFeelInfo[] lafs = UIManager.getInstalledLookAndFeels();
for (UIManager.LookAndFeelInfo laf : lafs) {
    System.out.println(laf);
}

try {            
    // set the System Look and Feel in the UIManager            
    javax.swing.SwingUtilities.invokeAndWait(new Runnable() {            
        public void run() {            
            try {            
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());            
            } catch (Exception e) {            
                e.printStackTrace();            
            }            
        }            
    });            
} catch (Exception e) {            
    e.printStackTrace();            
}

**Comment by tgvaughan** [comment]
Hi guys, rather than messing with the code can't we just add a switch like `-Dswing.defaultlaf=javax.swing.plaf.nimbus.NimbusLookAndFeel` to the Linux launch script if we feel that this is necessary?

**Comment by rbouckaert** [comment]
I think this is no longer an issue: loadUIManager sets Mac specific stuff when in OSX and the system look and feel otherwise.
