### ISSUE TITLE
BinaryCovarion implementation

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#398]
The BinaryCovarion implementation does not take hidden frequencies in account when setting up the rate matrix, only when getFrequencies() is called. As a result, the model is not reversible, unless hiddenFrequencies=(0.5, 0.5). The rate matrix then becomes

 *         a	the rate of the slow rate class
 *         1	the rate of the fast rate class
 *         p0	the equilibrium frequency of zero states
 *         p1	1 - p0, the equilibrium frequency of one states
 *         f0	the equilibrium frequency of slow rate class
 *         f1	1 - f0, the equilibrium frequency of fast rate class
 *         s	the rate of switching

 *         [ ---,   a*p1*f0    ,    s *f0  ,   0   ]
 *         [   a*p0 *f0   , ---- ,    0   ,   s*f0   ]
 *         [    s*f1      ,     0     ,  ---- ,  p1*f1   ]
 *         [    0      ,     s*f1     ,    p0 *f1 ,---]

instead of

 *         [ ---,   a*p1    ,    s   ,   0   ]
 *         [   a*p0    , ---- ,    0   ,   s   ]
 *         [    s      ,     0     ,  ---- ,  p1   ]
 *         [    0      ,     s     ,    p0  ,---]

Also, the model differs from Tuffley & Steel 1996, which uses two switch parameters instead of one, and uses switches between mutating and not mutation, instead of between fast and slow. The rate matrix

 *         [ ---,   a*p1*f0    ,    s *f0  ,   0   ]
 *         [   a*p0 *f0   , ---- ,    0   ,   s*f0   ]
 *         [    s*f1      ,     0     ,  ---- ,  0   ]
 *         [    0      ,     s*f1     ,    0   ,---]
where f0,f1 are determined by switch rates s0,s1
f0 = s1/(s0+s1) 
f1 = s0/(s0+s1)

Alternatively, using the original parameterisation using hidden frequencies and single switch parameter, we get (?needs verification)

 *         [ ---,   a*p1*f0    ,    s*f1 *f0  ,   0   ]
 *         [   a*p0 *f0   , ---- ,    0   ,   s*f1*f0   ]
 *         [    s*f0*f1      ,     0     ,  ---- ,  0   ]
 *         [    0      ,     s*f0*f1     ,    0   ,---]
where f0,f1 are determined by s1,s2
(s0+1)f0 = s1 
(s0+s1)f1 = s0
=>
s1/s0 = f1/f0
=>
s0 = s f1
s1 = s f0

**Comment by jheled** [comment]
As far as my tests reveal, this is the correct Q matrix. The diagonal is the -sum(rest of row) as usual.
Note: this is the "normalized" form, and should not be divided by the overall rate. 
Those rates qive a process with the following properties:

h0 slow states, h1 fast (h0+h1 = 1)
f0 zero states, f1 one states (f0+f1=1) 
The overall switching rate is S (and the expected time between switches is 1/S)
The overall mutation rate is (M * h0 + 1*h1) (and the expected time between switches is 1 over that)
The ratio between Slow and fast rates is M.



 [   -,        S/(2*h0), M/(2*f0),    0],
 [S/(2*h1),    -,         0,    1/(2*f0)],
 [M/(2*f1),    0 ,        -,    S/(2*h0)],
 [0,        1/(2*f1), S/(2*h1),   -]
