### ISSUE TITLE
update BEAUti and wiki to use term "Package"

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#40]
This is related to  issue 32 .

I have replaced most of "Add-on(s)" into "Plugin(s)" in wiki, except of 2 wiki pages that contain GUI screenshots and user guide: 
1) Writing an Add-on
2) Manage Add-ons

BEAUti 2 needs to be updated first, before these 2 pages can be re-written.

Walter
### Additional comments from GC issue

Sep 13, 2013
Project Member #1 alexei.drummond

I prefer "Package" to "Plugin". Package sounds like something you could write a paper about and be proud of (as with an R package).

Once we decide on the right name, it should be applied everywhere, not piecemeal.

Sep 22, 2013
Project Member #2 alexei.drummond

(No comment was entered for this change.)

**Comment by rbouckaert** [comment]
This seems a goot time to rename the AddOnManager to PackageManager for the v2.5.0 release.

**Comment by rbouckaert** [comment]
<code>BEAST_ADDON_PATH</code> is deprecated and you need to use <code>BEAST_PACKAGE_PATH</code> instead (though for a time both are recognised) in either environment variables or java properties.

In <code>version.xml</code> files for packages, the element <code>addonapp</code> should be replaced by <code>packageapp</code>, though the former will be recognised as long as there is no element of the latter (for now).

**Comment by rbouckaert** [comment]
By https://github.com/CompEvol/beast2/commit/ba18dcfa2662eb3f7c1d9a0263055cee47ab4210
