### ISSUE TITLE
partition names are not re-initialised after all alignments are removed

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#410]
BEAUti: 
1) load alignment(s);
2) remove all;
3) load it/them again;
keep repeat these, then the postfix number is adding up to the original name each time.

Same name should be used for the same alignment every time.

**Comment by rbouckaert** [comment]
0a6ce0107b9653ee4fbd2e8fc4fc8bcb0ca9bf32 also takes care of removing MRCAPriors when the tree the prior applies to is no longer estimated (e.g. because it was deleted)
