### ISSUE TITLE
NullPointerException by unlink trees after add TaxonSet to a tree

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#411]
BEAUti:
1) Load multi-alginment, link trees;
2) Goto "Priors", and add a taxon set;
3) Goto "Partitions", and unlink trees.

java.lang.NullPointerException
	at beast.app.beauti.BeautiDoc.renameId(BeautiDoc.java:1957)
	at beast.app.beauti.BeautiDoc.deepCopyPlugin(BeautiDoc.java:1813)
	at ....

**Comment by rbouckaert** [comment]
I cannot reproduce this, but perhaps one of the latest commits fixed this (f4e900c or c9d56aa77e)?

**Comment by walterxie** [comment]
cannot reproduce
