### ISSUE TITLE
jar files loaded that should be ignored

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#420]
To be investigated:

"Here are the details:

One of the BASTA versions that was being loaded is the local copy of the GitHub BASTA distribution, which is weird because it was a different path than the one in the tmp/beast.log
tmp/beast.log path:
/Applications/BEAST 2.3.0/BEAST.app/Contents/Java/launcher.jar
path of BASTA versions loaded:
/Users/username/basta-bayesian-structured-coalescent-approximation/version.xml"

**Comment by rbouckaert** [comment]
"But the much weirder thing is that the other version was loaded directly from the Trash! After I emptied the trash, the problem was gone."

**Comment by tgvaughan** [comment]
This is probably related to issue #95.  Working on a fix to that now.

**Comment by tgvaughan** [comment]
Probably closed by 9bf4fca.  Can somebody check?

**Comment by rbouckaert** [comment]
by  9bf4fca
