### ISSUE TITLE
Logcombiner should raise error on value that can't be a percentage.

### ISSUE THREAD

**Issue by SimonGreenhill** [CompEvol/beast2#422]
I was trying to combine some files, but kept getting an error about empty array sizes. I had been carefully entering the burnin value as "1000" (i.e. 1000 trees), and stupidly didn't read the little note that said "burnin (percentage)". 

To help attentionally challenged people like myself, logcombiner should raise an error if a non-percentage value is entered into burnin (i.e. anything outside [0.0 and 100.0]).

**Comment by tgvaughan** [comment]
Thanks, Simon. We need to improve error reportage across the board, actually.

BTW, in closing this issue I removed an event handler that was set up to fire whenever focus shifted away from a table cell being edited.  Leaving this in caused the FilesTableModel.setValueAt() event handler to be called twice, as bringing up an error dialog in the event handler causes the cell to lose focus.  Is this handler still necessary?
