### ISSUE TITLE
Random tree does not preserve taxa node numbers

### ISSUE THREAD

**Issue by jheled** [CompEvol/beast2#425]
Some code pre-compute stuff in initandvalidate, but later the tree is initialized and is replaced by another, and initandvalidate is not called again. Also on repeated calls it generated invalid node numbers

**Comment by tgvaughan** [comment]
This issue is referred to by commit 8d9a92ce4c2035849f841c70ff75ba57c54a965b.  Does this close the issue?

**Comment by rbouckaert** [comment]
Appears to be fixed now.
