### ISSUE TITLE
Refactoring of TreeParser

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#43]
TreeParser is rather too complex and has a very large number of interacting Inputs. It should be rationalised, perhaps by introducing a subclass. One key distinction is whether the labels in the Newick tree are considered to be node numbers of labels. For example, this could be separated into a superclass that only handles numbers and a subclass that handles labels.

TreeParser should also have an option for single-child nodes of either reading them in as single-child nodes (i.e. for purposes of beast-graphics or TreeStat2) or as two-child nodes with a zero branch to labelled child (i.e. for BEAST MCMC of sampled ancestor trees).

**Comment by tgvaughan** [comment]
Anyone interested in simplifying TreeParser might want to take a squiz at the above commit.  I know we've discussed the drawbacks of adding dependencies to beast before (the above requires a 370kb jar be added to lib/), but the advantages are:

* Parser generated from human-readable grammar
* Robust - e.g. no accidental parsing of additional close parens.
* Easy to modify.

The above commit (c7795cd) replaces only the parseNewick() method.  I think some of the other code could also be simplified by letting the parser handle things like meta-data strings.

I wouldn't at all suggest merging this commit with the master branch btw - it passes the unit tests, but there are enough things around that rely on details of the existing implementation that this sketch no-doubt misses.

**Comment by rbouckaert** [comment]
by d2dcd16
