### ISSUE TITLE
StarBeast and Standard template missing

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#435]
On Windows, with STACEY installed, the STACEY template shows up but Standard and StarBeast templates are missing from the File/Templates menu. They can be used by finding them through the File/Templates/Other menu. Below the BEAUti log after start up.

Loading package STACEY v1.0.4
Probing: stacey.jar Skip loading file:/C:/Users/Work/BEAST/2.3/STACEY/lib/stacey.jar: contains class stacey.BirthDeathCollapseModel that is already loaded
Loading template C:\Users\Work\AAA\biology\SoftWare\BEAST.v2.3.1\templates\Standard.xml
Investigating C:/Users/Work/AAA/biology/SoftWare/BEAST.v2.3.1
Processing C:\Users\Work\AAA\biology\SoftWare\BEAST.v2.3.1\templates\ClockModels.xml
Processing C:\Users\Work\AAA\biology\SoftWare\BEAST.v2.3.1\templates\ParametricDistributions.xml
Processing C:\Users\Work\AAA\biology\SoftWare\BEAST.v2.3.1\templates\StarBeast.xml
Processing C:\Users\Work\AAA\biology\SoftWare\BEAST.v2.3.1\templates\SubstModels.xml
Processing C:\Users\Work\AAA\biology\SoftWare\BEAST.v2.3.1\templates\TreePriors.xml
Investigating /C:/Users/Work/BEAST/2.3/STACEY
Processing C:\Users\Work\BEAST\2.3\STACEY\templates\STACEY.xml
Investigating .
Skipping C:\Users\Work\AAA\biology\SoftWare\BEAST.v2.3.1\.\templates\ClockModels.xml since ClockModels.xml is already processed
Skipping C:\Users\Work\AAA\biology\SoftWare\BEAST.v2.3.1\.\templates\ParametricDistributions.xml since ParametricDistributions.xml is already processed
Processing C:\Users\Work\AAA\biology\SoftWare\BEAST.v2.3.1\.\templates\Standard.xml
Skipping C:\Users\Work\AAA\biology\SoftWare\BEAST.v2.3.1\.\templates\StarBeast.xml since StarBeast.xml is already processed
Skipping C:\Users\Work\AAA\biology\SoftWare\BEAST.v2.3.1\.\templates\SubstModels.xml since SubstModels.xml is already processed
Skipping C:\Users\Work\AAA\biology\SoftWare\BEAST.v2.3.1\.\templates\TreePriors.xml since TreePriors.xml is already processed
Investigating /C:/Users/Work/AAA/biology/SoftWare/BEAST.v2.3.1
Skipping C:\Users\Work\AAA\biology\SoftWare\BEAST.v2.3.1\templates\ClockModels.xml since ClockModels.xml is already processed
Skipping C:\Users\Work\AAA\biology\SoftWare\BEAST.v2.3.1\templates\ParametricDistributions.xml since ParametricDistributions.xml is already processed
Skipping C:\Users\Work\AAA\biology\SoftWare\BEAST.v2.3.1\templates\StarBeast.xml since StarBeast.xml is already processed
Skipping C:\Users\Work\AAA\biology\SoftWare\BEAST.v2.3.1\templates\SubstModels.xml since SubstModels.xml is already processed
Skipping C:\Users\Work\AAA\biology\SoftWare\BEAST.v2.3.1\templates\TreePriors.xml since TreePriors.xml is already processed
connect => beast.app.beauti.BeautiConnector
subtemplate => beast.app.beauti.BeautiSubTemplate
Uniform => beast.math.distributions.Uniform
Normal => beast.math.distributions.Normal
OneOnX => beast.math.distributions.OneOnX
LogNormal => beast.math.distributions.LogNormalDistributionModel
Exponential => beast.math.distributions.Exponential
Gamma => beast.math.distributions.Gamma
Beta => beast.math.distributions.Beta
LaplaceDistribution => beast.math.distributions.LaplaceDistribution
InverseGamma => beast.math.distributions.InverseGamma
prior => beast.math.distributions.Prior
map
map
map
map
map
map
map
map
map
map
map
map
beauticonfig
fragment
run
===============================================================================
Citations for this model:

Bouckaert RR, Heled J, Kuehnert D, Vaughan TG, Wu C-H, Xie D, Suchard MA,
 Rambaut A, Drummond AJ (2014) BEAST 2: A software platform for Bayesian
 evolutionary analysis. PLoS Computational Biology 10(4): e1003537

===============================================================================
template item TreeOperators is ignored
PARTITIONS0:

[[], [], []]
InPosterior=posterior prior likelihood
Could not find plugin with id treeLikelihood.Species. Typo in template perhaps?

Validation message: At least one input of name 'xx' must be specified.
class beast.core.MCMC != class beast.core.Runnable
PARTITIONS0:

[[], [], []]

**Comment by tgvaughan** [comment]
Looks like the BEAST install directory was being included as a side-effect the behaviour that led to issue #95.

**Comment by tanja819** [comment]
What is the correct set up in IntelliJ to ensure that the standard templates are loaded? Tanja seems to be having the same problem which causes failures in a number of JUnit tests.

**Comment by rbouckaert** [comment]
You can set the "beast.install.dir" java directive (or environment variable) to the parent of the templates directory where the Standard.xml and StarBeast.xml files are (e.g. I have mine in /Users/remco/workspace/beast2) and they should be picked up from there. 

Not sure how to do this in Intellij but I suppose setting up the debugger to include something like -Dbeast.install.dir=/Users/remco/workspace/beast2 as java argument (note, not as argument to the java class, but directly to java) should achieve this.

**Comment by alexeid** [comment]
Maybe we need a single page somewhere that describes how to set up IntelliJ so that BEAUti and the JUnit tests run?

**Comment by tgvaughan** [comment]
I agree.  This information could even be in the README, which is the traditional place to put compilation information.  At least we could to link it from there.

Which unit tests are you seeing fail, @tanja819 ?  There are two options that I like to use when running from an IDE: -Dbeast.install.dir=PATH_TO_BEAST_CODE and -Dbeast.user.package.dir=NONE.  For the first of these I substitute the path to the root of the beast 2 directory (the parent directory of src/).  The second I leave as-is, which causes beast to ignore any packages I have installed on my machine.  (I don't want to be accidentally using a release version of some package.)
