### ISSUE TITLE
Line 308 of RandomTree breaks association between leaf ages and sequences.

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#438]
[This line](https://github.com/CompEvol/beast2/blob/95afe23ec5fde12919b98eb72ba91c00de15405f/src/beast/evolution/tree/RandomTree.java#L308) causes node heights to wind up associated with the wrong taxa. The way this happens is:

1. Taxon names are read in to RandomTree from the provided alignment. They are stored in an array. (I.e. they are ordered.)
1. Node attributes (e.g. height) are assigned in simulateTree() based on a provided TaxonSet, associating each node with the node.getNr()'th taxon in the array.
2. The coalescent tree is simulated.
3. The line above essentially randomizes the node numbers.
4. RandomTree calls Tree's initAndValidate() method which assigns taxon labels to nodes based on their (now arbitrary) node numbers.
5. TreeLikelihood associates sequences with leaves by reading the taxon label associated with each leaf and looking up the sequence linked to this label.

The following XML files demonstrate the problem.  (I've given them .txt extensions, as github doesn't allow files with .xml extensions to be attached to issues.)  These are modifications of [testCoalescent.xml](https://github.com/CompEvol/beast2/blob/95afe23ec5fde12919b98eb72ba91c00de15405f/examples/testCoalescent.xml) in which the sequences are given non-contemporaneous sampling times.  The first file uses ClusterTree to initialise the chain, while the second uses RandomTree.  Running these shows that the RandomTree example messes up the taxon<->sample time association.

[testCoalescent.xml.txt](https://github.com/CompEvol/beast2/files/29560/testCoalescent.xml.txt)
[testCoalescentRandomTree.xml.txt](https://github.com/CompEvol/beast2/files/29561/testCoalescentRandomTree.xml.txt)

While it's tempting to simply remove the offending code, that code is part of a commit aimed at addressing issue #425 that I don't fully understand.   I think this therefore needs the attention of @jheled.

**Comment by tgvaughan** [comment]
@jheled It seems the code we committed is failing unit tests all over the place.  Any clue what's going on?

**Comment by tgvaughan** [comment]
I've reverted the commit - we can fix it in the [RandomTree](https://github.com/CompEvol/beast2/tree/RandomTree) branch.

**Comment by tgvaughan** [comment]
Hrm, it seems we're not the only culprits - @rbouckaert's commit 5a39368c0a498e95e38b83a36b8550a00e97a549 causes the testTipDates2.xml not to run, thus failing `ExampleXmlParsingTest`.  Our commit was also causing `ExampleJSONParsingTest` to fail though.

**Comment by rbouckaert** [comment]
Tested and test files produce the same tree, which have labels at the height specified by the tree, so things seem to be fixed now.
