### ISSUE TITLE
Trouble loading primate-mtdna file into BEAUti for tutorial

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#439]
From beast-users Google groups:

Hi,

I am trying to work through the Divergence Dating tutorial for BEAST 2.0 using BEAST 2.3.1 in linux.  When I try to import the "primates-mtDNA.nex" file into BEAUti the file cannot load and I receive the error message "Error parsing imported file:
dr.evolution.io.importException:CharSet, g, unable to be parsed"

Does anyone know if it should be possible to import this and what the issue may be?

Thanks,
Megan

**Comment by tgvaughan** [comment]
@walterxie This was due to the user accidentally running BEAST 1 instead of BEAST 2.  I replied to their email on beast-users this morning describing the problem.
