### ISSUE TITLE
Devs need a way of explicitly setting beast install directory

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#448]
Programmers can already override the package install directories using the `beast.user.package.dir` and `beast.system.package.dir` system properties.  It would be useful to also have a property `beast.install.dir` for specifying the base installation directory.  This is useful when running BEAST from a programming environment.

**Comment by rbouckaert** [comment]
The current set-up requires me to set beast.install.dir in about a 100 different places if I do not want all packages in the parent of my beast2 directory to be picked up (or set an environment variable, which will make testing error prone). 
Ignoring the BEAST install dir when running as dev can be tested when BeastMain is not found in a jar file but in a directory and solve the above problem.
