### ISSUE TITLE
Nucleotide sequences for BEAST2

### ISSUE THREAD

**Issue by HK3008** [CompEvol/beast2#458]
![Uploading 1.jpg…]()
As  the picture, why the data "import alignment" was treated as "aminoacid" data by default, can not be changed to "nucleotide"? why there is no choice in "Data Type"  Pannel?

**Comment by rbouckaert** [comment]
Having a change datatype button sounds like a good idea.
Could you make the file available that you used to import into BEAUti (email to me or post somewhere)?

**Comment by HK3008** [comment]
Thank you so much for your help! I have changed the .fas sequences file to the .nex file, imported into BEAUti and then show it "nucleotide" data type successfully!
