### ISSUE TITLE
error report for BEAST2

### ISSUE THREAD

**Issue by HK3008** [CompEvol/beast2#462]
when i run the .xml file generated by BEAUti 2 wiht "Birth-Death model", the error reported as follow:
"fail to load BEAGLE library：no hmsbeagle-Jni  in java.library path"
what is the problem?

**Comment by rbouckaert** [comment]
To use the BEAGLE library you need to have it installed separately. It is not part of the BEAST distribution.

This kind of question is more appropriate for the beast users list https://groups.google.com/forum/#!forum/beast-users. The issues list is more appropriate for feature requests and bug reports.

**Comment by alexeid** [comment]
But should the error be reported at all, since most people won't know to independently install BEAGLE, and it doesn't prevent BEAST2 from operating if you don't.

**Comment by rbouckaert** [comment]
Default behaviour is to attempt to use BEAGLE, and if not successful use the java implementation instead. So a warning to indicate that the BEAGLE library was tried but failed seems appropriate.

The warning is produced by the BEAGLE library, so to change it the BEAGLE library needs changing (or some temporary stdout/stderr redirection could be done)...
