### ISSUE TITLE
JSON library license issue

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#463]
The JSON library used has a license that prevents BEAST to be made into a Debian package (https://wiki.debian.org/qa.debian.org/jsonevil). There are alternatives like json-simple (http://code.google.com/p/json-simple/) and others. Note that the original library was changed to facilitate error reporting (added getParent() method).

**Comment by rbouckaert** [comment]
While the JSON parser is updated, another few things to look at are
- use 'beast' as main tag instead of 'analysis'. At the moment, it is not clear at all that a JSON-BEAST file is indeed a BEAST file.
- process $(seed) and $(filebase) with random number seed and base of JSON file name in attributes.
- produce version number that equals BEAST major version number, instead of "2.0".
- improve parser exception handling; by making JSONParserException derive from XMLParserException allows more natural way of handling these exceptions in BeastMain. Replace any throw Exception with throw JSONParserException and encapsulate any Exceptions thrown by for instance Input.setValue in a JSONParserException.
- add support for annotated constructors.

**Comment by tgvaughan** [comment]
For those who didn't read the link, Debian (and others including - ironically? - Google) do not class the library as free software because it adds the following clause to the stock MIT license:

    The Software shall be used for Good, not Evil.

**Comment by tillea** [comment]
Hi folks,
thanks for tackling this issue in your tracker and with commits.  Do you have any time estimation for a solution of this issue?

**Comment by rbouckaert** [comment]
This will be available in the 2.4 release. There are a few more issues that need resolution for this  release, which I hope will be done in the next month or so. Aiming for a release early March.

**Comment by tillea** [comment]
On Thu, Jan 28, 2016 at 09:44:56AM -0800, Remco Bouckaert wrote:
> This will be available in the 2.4 release. There are a few more issues that need resolution for this  release, which I hope will be done in the next month or so. Aiming for a release early March.

Cool.  Thanks for the very helpful estimation and the good work on
Beast2

        Andreas.

-- 
http://fam-tille.de

**Comment by rbouckaert** [comment]
by fbf1b26
