### ISSUE TITLE
Package file multiple entry support

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#467]
Currently, each minor release has its own packages file maintained on CBAN. It would be a lot less work if there was only a single packages file with multiple entries for packages that only work with particular version of BEAST depending on 'atleast' and 'atmost' attributes to match versions.

The latest package appropriate for the users BEAST version should show up in the package manager dialog/listing. 

Packages that are not working with the current users release due to it being not up to date could be highlighted. Having an entry for the latest BEAST release so the package manager can notify the user to upgrade (related: #144) would be useful for this.

**Comment by tgvaughan** [comment]
This is in progress over in the [package_revamp](https://github.com/tgvaughan/beast2/tree/package_revamp) branch of my fork.
