### ISSUE TITLE
MerseneTwisterFast.nextPoisson(lambda) is slow for small lambda

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#469]
The current implementation uses a direct sampling method for lambda<12 that involves multiple calls to nextDouble(), which is expensive.  For tau-leaping simulations (the main application of nextPoisson) where lots of small steps are involved, this can noticeably slow things down.  I suggest we replace the existing small lambda method with an inverse CDF method.  This still involves a loop of n iterations (where n is the sampled integer) but only a single call to nextDouble().

**Comment by tgvaughan** [comment]
Hey @rbouckaert, any chance of including this in 2.3.3?

**Comment by rbouckaert** [comment]
Included in v2.3.3pre2

**Comment by tgvaughan** [comment]
Okay, this was a huge mistake.  I have workarounds in place for the workshop, but the change in return type makes this an API change that I should have been much more wary of than I was.  I recommend we revert this before 2.3.3 comes out.

**Comment by tgvaughan** [comment]
Revert the type signature change that is, not the algorithm change.
