### ISSUE TITLE
BEAST does not consistently return a non-zero exit status to the shell after terminating with an error

### ISSUE THREAD

**Issue by lmaurits** [CompEvol/beast2#470]
When used as a command line program, some errors (e.g. invalid command line arguments) will cause BEAST to "do the right thing" and return a non-zero exit status (1 in this case).  However, on different errors (e.g. XML parsing errors), BEAST will return a zero exit status, no different to if the analysis had run to completion with no problems.  This makes it very difficult for third-party programs which run BEAST to reliably determine whether or not an analysis ran successfully.

**Comment by tgvaughan** [comment]
It sounds like this might be related to the general problem of exception handling and error reporting.  Maybe we could group together these and other issues into a milestone for the next release?

**Comment by lmaurits** [comment]
I have already written a quick fix (added a handful of System.exit calls to BeastMain) which seems to fix all the instances of this behaviour which were causing me trouble right now, and was planning to push it once I get write access to the repo.  That said, this behaviour might still crop up in some other use cases, as there doesn't seem to be a particularly systematic approach to catching errors and exiting BEAST.  e.g. I've seen that a System.exit(0) can happen inside BeastMCMC.parseArgs, but most of the time exceptions bubble up and exiting happens inside BeastMain.  There could easily be other places that exits occur which I haven't found.  Some kind of general tidy up aimed at making error detection, reporting and handling more consistent and centralised (if that's the kind of thing you were suggesting) sounds like a good idea, and would make it easier to guarantee we always do the right thing with exit statuses.

**Comment by rbouckaert** [comment]
@tgvaughan  #473 should cover exception handling issues and #472 logging issues, and we can keep this for exit status issues.
