### ISSUE TITLE
EBSPAnalyser computes equal-tailed credible interval, not HPD as reported

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#481]
Equal-tailed intervals can be quite different to HPDs.

**Comment by alexeid** [comment]
We call that a CPD interval (central posterior density interval). Both HPD (highest posterior density) and CPD intervals are “credible intervals” in Bayesian parlance.

**Comment by tgvaughan** [comment]
Sure, but EBSPAnalyzer claims to compute HPDs when it doesn't.  Surely this is a (minor) bug?

**Comment by alexeid** [comment]
yep :)
