### ISSUE TITLE
Comment out debugging code with hardcoded /tmp/beast.log in BeastLauncher.java

### ISSUE THREAD

**Issue by moskalenko** [CompEvol/beast2#483]
We're getting beast2 run failures in a multi-user environment because of the uncommented debugging code left in a release package even though there is a note in BeastLauncher.java that says
"                // TODO remove following debugging code"

Here's a patch to comment it out.

diff --git a/src/beast/app/beastapp/BeastLauncher.java b/src/beast/app/beastapp/BeastLauncher.java
index c1eb812..e003507 100644
--- a/src/beast/app/beastapp/BeastLauncher.java
+++ b/src/beast/app/beastapp/BeastLauncher.java
@@ -41,6 +41,7 @@ public class BeastLauncher {
                launcherJar = URLDecoder.decode(launcherJar, "UTF-8");

                // TODO remove following debugging code
+               /*
                try {   
                        FileWriter outfile = new FileWriter("/tmp/beast.log");
                        outfile.write("jardir = " + launcherJar);
@@ -48,6 +49,7 @@ public class BeastLauncher {
                } catch (IOException e) {
                        e.printStackTrace();
                }
+               */

                Log.warning.println("jardir = " + launcherJar);
                File jarDir0 = new File(launcherJar).getParentFile();

**Comment by moskalenko** [comment]
I created a pull request for the removal of the debugging code in #484

**Comment by rbouckaert** [comment]
I merged the code.
Thanks for the fix!
Remco
