### ISSUE TITLE
BEAST fails to find installed libhmsbeagle.so (GNU/Linux)

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#487]
Using the shell script distributed with release 2.3.2 or pre-release 2.3.3 to run BEAST results in the standard "Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path", despite the fact that the JNI is clearly installed:

    $ locate libhmsbeagle-jni.so
    /usr/lib/x86_64-linux-gnu/jni/libhmsbeagle-jni.so

The problem seems to be the `-Djava.library.path=$BEAST_LIB:/usr/local/lib` option passed to the JVM by the `beast` script.  This actually runs roughshod over the system shared library search path, which is not as simple as `/usr/local/lib` or even `/usr/lib:/usr/local/lib`.  For instance, Debian (and Ubuntu) systems have multi-architecture support meaning that they divide /usr/lib into subdirectories containing 32bit, 64bit and potentially other varieties of shared libraries.

Removing this option from the script fixes the problem.  Why is it needed? Unless beagle is installed by hand, it should be in a standard location.  If it _is_ installed by hand, the path should probably be added to LD_LIBRARY_PATH in a non-destructive way, such as

    LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/new/path"

Beyond this, why is `$BEAST_LIB` included in the path list? There seem to only be jars in that directory - nothing that ld.so is interested in, right?

**Comment by rbouckaert** [comment]
This script was inherited from BEAST 1, which uses a native implementation of the TreeLikelihood distributed in $BEASTLIB. so that would explain why it is part of the LD_LIBRARY_PATH. It can be dropped for BEAST 2.

Note the script is shared with Mac, which appears to install in /usr/local/lib by default. After dropping the -Djava.library.path from the script ./bin/beast still picks up BEAGLE on my machine, so it looks like it can be dropped.

**Comment by tgvaughan** [comment]
It seems certain JREs only pick up the library paths specified in LD_LIBRARY_PATH, not those in /etc/ld.so.conf (which is the default location for system-wide configuration of these paths - LD_LIBRARY_PATH is usually empty by default).   This has caused some users to find that beast 2.4 does not find beagle, where as earlier versions did: they had it installed in /usr/local/lib (which was the only install location that would work in previous versions) but this is sometimes not autodetected now due to this JRE problem.

I suggest we add /usr/local/lib to LD_LIBRARY_PATH in the launch script.  This will still allow beast to find beagle when installed in other standard locations, but will ensure that the beast will continue to find beagle when installed in /usr/local/lib despite the JRE issue.
