### ISSUE TITLE
BEAUti uses explicit pixel dimensions to size components

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#492]
The primary culprits use the static fields `InputEditor.PREFERRED_SIZE` and `InputEditor.MAX_SIZE`.  These assume that 25 pixels is exactly how high a single-row component should be.  This isn't true in general, and is very wrong on high pixel density displays like retina.  It has caused problems in the past (e.g. #270 which has been specifically addressed) but will continue to persist as long as these fields are being used.  At some point we should remove these fields and replace any `setMaximumSize()` or `setPreferredSize()` calls this breaks with calls that do not use explicit sizes.

**Comment by alexeid** [comment]
I thought we had removed all the evil 25 pixel constants in a previous fix, because they are also very bad for Retina displays as the fields are so small you can’t use them. We should leave the pixel-size of components to the layout manager to optimise to the display device.

**Comment by tgvaughan** [comment]
So did I, but apparently the problem persists.
