### ISSUE TITLE
Setting up calibrations

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#494]
Setting up calibrations in BEAUti requires specifying taxon sets for each of the calibrations. If there are many nested calibrations this can be a nuisance. It would be useful to have a way to copy calibrations and their taxon sets (http://markmail.org/message/uv7ajs3aqlogsyfp).

Another possibility is to have calibrations specified in the NEXUS file, so that when BEAUti imports the alignment, it can import the accompanying calibrations as well. This is especially useful for databases that maintain both sequence and calibration information and can export NEXUS. NEXUS has the option to specify taxon sets using the sets-block, e.g. like so:

begin set;
taxset germanic = english dutch german;
taxset romance = spanish italic rumanian;
end;

Unfortunately, there does not seem to be a way to specify distributions over taxon sets in NEXUS. MrBayes offers the following commands, which would go in a mrbayes block:
      calibrate <node_name> = fixed(<age>)                                       
      calibrate <node_name> = uniform(<min_age>,<max_age>)                       
      calibrate <node_name> = offsetexponential(<min_age>,<mean_age>)            
      calibrate <node_name> = truncatednormal(<min_age>,<mean_age>,<stdev>)      
      calibrate <node_name> = lognormal(<mean_age>,<stdev>)                      
      calibrate <node_name> = offsetlognormal(<min_age>,<mean_age>,<stdev>)      
      calibrate <node_name> = gamma(<mean_age>,<stdev>)                          
      calibrate <node_name> = offsetgamma(<min_age>,<mean_age>,<stdev>)          
so we could introduce a beast block with a similar format but that fit our distributions better: there is no truncated normal in BEAST, but there are quite a few not listed above.

**Comment by alexeid** [comment]
I would not be keen to introduce a BEAST block into Nexus. Let's keep nexus as an existing format we support. So supporting the reading of the existing MrBayes commands makes a lot of sense.

**Comment by SimonGreenhill** [comment]
Having just set up an analysis with many calibrations, even just getting BEAUTi to define the clades for you consistently would save a lot of time (e.g. if cladeA has 100 taxa in it, it's a pain to check that I've correctly added 100 taxa each and every time).

**Comment by rbouckaert** [comment]
@SimonGreenhill  How do you typically store the information of which taxa goes in which clade? If there would be a good file format, it would be worth creating import support for that.

**Comment by SimonGreenhill** [comment]
Stored usually in my brain or in text format. I like the nexus sets block suggestion.

**Comment by rbouckaert** [comment]
The SIB (stored in brain) format is currently not supported.

**Comment by rbouckaert** [comment]
by 006d4037cd3c9e05ae0d02df28fcf6f034b0a338

**Comment by SimonGreenhill** [comment]
Awesome, thanks Remco, this will make life much much easier
