### ISSUE TITLE
TreeParser aborts on trees with multifurcations

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#495]
The earlier incarnation of TreeParser accepted nodes with >2 children by creating a ladder of dummy nodes.  The current version parses such trees just fine, but aborts with an error during AST traversal if such a node is found.  This is an error, as users need to be able to specify starting trees that have these multifurcations.

The second error is that the TreeParser test suite does not contain a test for this behaviour.

**Comment by rbouckaert** [comment]
Most of BEAST assumes binary trees. So, I think that failing on a non-binary tree, or converting a non binary tree to a binary tree should be the default behaviour. A flag could be added to leave the non binary tree untouched.

**Comment by tgvaughan** [comment]
To be clear, I'm not suggesting TreeParser ever create trees containing nodes with out-degree>2.  I'm just saying that it should follow the old TreeParser's behaviour which was to coerce these trees into binary trees by adding dummy internal nodes. (Which is what now happens following commit 69135da.)

This was an oversight on my part - I instinctively added the exception because I've always thought of beast as dealing only with binary trees, which it does, but that's not to say that sometimes we don't need to be able to parse them! :-)

**Comment by rbouckaert** [comment]
Good to see we have the old behaviour back.
Wouldn't it be nice to support non binary trees as well, leaving the current behaviour as is, but -- conditioned on a flag being set -- generating non binary trees?

**Comment by tgvaughan** [comment]
Yes it would, and it would be as easy as skipping the coercion if that flag was set. (It already generates non-binary trees - it modifies them after the fact.)

**Comment by SimonGreenhill** [comment]
Thanks for this -- allowing non-binary trees makes it much much easier to specify a starting tree (i.e. the user can just define the nodes that matter, rather than everything).

**Comment by tgvaughan** [comment]
@SimonGreenhill don't thank me - I'm the one who broke it! :-/

**Comment by walterxie** [comment]
@tgvaughan 
I tried to add this flag, but it looks the node height cannot be calculated correctly for multifurcations:

The original tree:
(A:0.1,B:0.2,(C:0.3,D:0.4):0.5)
but after parser:
(A:0.1,B:0.2,(C:0.2,D:0.09999999999999998):-0.3)
