### ISSUE TITLE
StarBeastStartState and calibrations

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#503]
When there are many calibrations and another prior than the Calibrated Yule Prior is used the calibrations appear to be ignored and the analysis does not start.

A warning should be produced to indicate that it is unwise to combine calibrations with any tree prior but the Calibrated Yule.

Calibrations should be taken in account, even when the Calibrated Yule Prior is not used -- when there are many calibrations, the Calibrated Yule is not practical and another prior must be used (e.g. as posted here: https://groups.google.com/forum/#!topic/beast-users/zc10a6d_aYE)

**Comment by alexeid** [comment]
Remco,

Why do you say this? Heled and Drummond (2012) explicitly describe both approaches to calibration (classic approach with simple multiplication and “Calibrated” approach). Why do you say that the classic approach should not be used any more? Its more important that the user knows which one they are doing, isn’t it? With too many calibrations it is computationally restrictive to use the “calibrated” approach, so the classic approach is the only option (unless they use the fossilised birth-death process which is of course better than both the other alternatives).

https://sysbio.oxfordjournals.org/content/61/1/138.full <https://sysbio.oxfordjournals.org/content/61/1/138.full>

Alexei

**Comment by jheled** [comment]
I agree with Alexei. The user should know the consequences of his choices,
that is all.

-Joseph

**Comment by rbouckaert** [comment]
Not saying that the classic approach should not be used, but that the user should be warned if it isn't -- I think we are all in agreement here.

At the moment, the analysis may or may not start using the classic approach when there are calibrations are used, since calibrations appear to be ignored setting up the species tree.

**Comment by rbouckaert** [comment]
by c00b8398e8c3e3936ac2779a9229eebcccaad5fc
