### ISSUE TITLE
Hidden inputs confuse Input.determineClass()

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#526]
Prior to 2.4 the following was possible:

```java
public class A extends BEASTObject {
    public Input<T> anInput = new Input<>("input", "");
    // ...
}

public class B extends A {
    public Input<S> anInput = new Input<>("input", "");
    // ...
}
```

While this might seem perverse, MASTER uses this to allow `Trajectory` simulations to use the "output" element to specify trajectory-specific outputs and `InheritanceTrajectory` simulations (which extend `Trajectory`) to specify tree/network specific outputs.  The changes that have been made to `Input.determineClass()` mean that this is no longer possible.

**Comment by tgvaughan** [comment]
Actually, the problem isn't really to do with hidden fields - it's to do with "hidden" _inputs_.

**Comment by alexeid** [comment]
Seems reasonable to me to allow that.

**Comment by rbouckaert** [comment]
The problem with having an input with the same name is that correct interpretation relies on the order in which members are discovered by introspection. It assumes that the Inputs of the derived class come before that of the super class, but I am not sure it is guaranteed to happen that way by different JDK implementations.

Also, the super class cannot see the Input of the derived class, so any reference to it need to be carefully managed by the derived class. I have seen cases where this did not happen carefully enough and cause problems.

So, you might be able to fix Input.determineClass() for this (e.g. explicitly setting the Input type in the c'tor, so it will never be called) I would not encourage using such construction -- there is in fact a unit test that checks Input names are different.

**Comment by tgvaughan** [comment]
Hrm.  I guess the only option then is to have a single input in `A` that accepts a type that is a superclass of both T and S and do the actual type checking manually.
