### ISSUE TITLE
Setting up a DeltaExchangeOperator test is non-trivial

### ISSUE THREAD

**Issue by Anaphory** [CompEvol/beast2#532]
I am trying to fix a bug in the `DeltaExchangeOperator` and realised that there is no test for that operator. So I assumed that the most simple test I could imagine would be along the following lines.

	public void testCanOperate() {
		RealParameter parameter = new RealParameter(new Double[] {1., 1., 1., 1.});
		DeltaExchangeOperator d = new DeltaExchangeOperator();
		// An invalid operator should either fail in initByName or make valid proposals
		try {
			d.initByName("parameter", parameter);
		} catch (RuntimeException e) {
			return;
		}
		d.proposal();		
	}

This test does not check correctness or anything, it just assumes that either `initByName` fails or the operator is functional and can propose state changes. Yet this test fails with a `java.lang.NullPointerException`, in `RealParameter.startEditing()` below `proposal`.

Should it be more complicated than this to set up an operator test?

**Comment by rbouckaert** [comment]
Setting up such a test is not trivial since operators have non-trivial functionality --  you need at least a State to which the parameter is attached to run an operator. Have a look at the other operator tests (in particular UniformIntegerOperatorTest) to see what is involved in setting up such a test.

**Comment by rbouckaert** [comment]
related #112

**Comment by Anaphory** [comment]
In that case, can we have an OperatorTest class that provides the necessary environment (a state node etc.), and includes methods testing

1. whether in that particular environment and for each test case the `initAndValidate` runs through
2. whether if the `initAndValidate` runs through, `proposal` can be called without error
3. operator after-proposal parameter validity (checking upper, lower, etc. for each state)? – Given that every operator needs to make sure to follow these constraints by itself, they should be automatically tested for each.

The class should make it easy to add more tests.

**Comment by rbouckaert** [comment]
I encourage anything to increase the test coverage, so if you can develop a class that does sanity checks like making sure `initAndValidate` and `proposal` do not crash that would be great!

You think this can be generalised to work with any operator? If so, it should probably go in the `test.beast.integration` package together with the other integration tests, and discover Operator classes through `AddOnManager.find`. 

If not, it would already be great to have these tests added to the `test.beast.operator` package.

**Comment by Anaphory** [comment]
I don't think it could be generalized to work with `AddOnManager.find`, because the test needs to know what the operator works on and there might be restrictions beyond just the type of inputs it takes, like the operand adding up to 1, being positive, etc., that could not be determined through introspection.

**Comment by rbouckaert** [comment]
by 508e8a12e4412d040a867ad49615682cfa69d369
