### ISSUE TITLE
BEAUTI (v.2.4.0) can't start AutoPartition template (or import/read it)

### ISSUE THREAD

**Issue by aersoares81** [CompEvol/beast2#547]
How to replicate: Open BEAUTI, and on the menu go to File / Template / AutoPartition. Nothing happens. If you try to load the example RBS.xml file, BEAUTI gives Error 1006, with Error detected about here: <beast><mergewith>.
If one try to just drag and drop the RBS.xml file, BEAUTI hangs.

**Comment by rbouckaert** [comment]
by https://github.com/BEAST2-Dev/rb-beast/commit/cfb6533099f0855cd2ce86478d3a33d88b4bb3ea
