### ISSUE TITLE
Strange empty column in the last column of log

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#556]
In BEAST log, each row also has an extra "tab" in the end, which causes an empty column, if you load it to R.

**Comment by tgvaughan** [comment]
While testCoalescent.xml does produce trailing tabs in the log file in BEAST 2.4.2, R 3.3.0 doesn't seem to produce an extra column when this is read into a dataframe unless you explicitly ask to use `\t` as the field separator:
```R
> df <- read.table("test.1463545347761.log", header=T)
> names(df)
[1] "Sample"         "coalescent"     "treeLikelihood" "popSize"       
[5] "hky.kappa"      "posterior"     
> dim(df)
[1] 101   6
> df2 <- read.table("test.1463545347761.log", header=T, sep='\t')
> dim(df2)
[1] 101   7
> names(df2)
[1] "Sample"         "coalescent"     "treeLikelihood" "popSize"       
[5] "hky.kappa"      "posterior"      "X"      
```

**Comment by walterxie** [comment]
Thanks, Tim, but my point is why we need this extra "tab"?

Cheers,
Walter

**Comment by alexeid** [comment]
I agree it would be nice to suppress the final unnecessary tab character.
