### ISSUE TITLE
MCMC contains commented-out debugging code

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#566]
This is extremely useful code that I (and no doubt many others) uncomment on a regular basis during the process of tracking down subtle state caching or operator bugs.

It [looks] (http://stackoverflow.com/questions/1813853/ifdef-ifndef-in-java?lq=1) as though we can place these debug lines within if statements dependent on a static final variable without any performance penalty: they're then optimized out at compile time.

I vote for doing this - it cuts down on the amount of code in comments and makes it easier to switch on the debugging information (change one boolean value instead of hunting through MCMC.java looking for the appropriate lines to uncomment).

**Comment by tgvaughan** [comment]
Looking at the disassembled class file it is clear that the if statements are optimized out at compile time: setting `printDebugInfo` to false is therefore equivalent to commenting out the print statements.

**Comment by rbouckaert** [comment]
First reaction: oh no, another MCMC update!
Seriously: nicely done, very useful indeed.

**Comment by tgvaughan** [comment]
Ironically I thought of this _because_ of our discussions about MCMC update frequency. :-)
