### ISSUE TITLE
BEAUti support for tip date sampling

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#567]
The current support in the tip dates tab is limited to a single calibration and seems broken.

There is support for adding priors on tips (using the tipsonly flag on MRCAPrior), but what is missing is adding operators. Perhaps the easiest way to support this is to add tip sampling operators for any MRCAPrior that has the tipsonly flag set to true, and remove these operators when tipsonly=false, which allows users to change their minds.

**Comment by rbouckaert** [comment]
related/duplicate of #41

**Comment by tgvaughan** [comment]
This came up in the workshop.  Maybe we should relabel this a bug?  BEAUti gives every indication of allowing this, but the resulting XML doesn't include the tip dates sampling operator - even though one is created and a connection rule exists for one.

**Comment by alexeid** [comment]
There were at least 4 independent requests for this during the Taming the BEAST website. I know it is already possible in the XML (see http://beast2.org/2015/06/09/sampling-tip-dates/) but this blog post also describes how to do it in BEAUti, which is not working. I think we need to write a tutorial and test for this.
