### ISSUE TITLE
Same seed, different BEAST runs, different traces

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#568]
This happens when running from the command line vs running in an IDE. Though not incorrect, it makes debugging very hard, especially the incorrectly calculated likelihood bugs. It is probably caused by the use of HashSets and HashMaps, which generate maps based on the location of an object in memory (among other things), and since IDEs manage the memory of programs when debugging this may explain the differences in traces. Perhaps, replacing them with TreeSets and TreeMap may solve this.

**Comment by tgvaughan** [comment]
I've come up against this kind of thing in MASTER.  I guess it comes down to a question of whether any efficiency gain from using a hash table is significant enough to warrant such fragile reproducibility.

**Comment by jheled** [comment]
Probably a nightmare, but the best would be to have this under control of a flag when there is an efficiency issue. Off (default) - fast and non-reproducible. On: possibly slower but reproducible.

**Comment by rbouckaert** [comment]
LinkedHashSet maintains insertion order, and performs only slightly worse than HashSet, while TreeSet takes much more time (http://www.programcreek.com/wp-content/uploads/2013/03/hashset-treeset-linkedhashset1.png), so it is probably a better choice than TreeSet if we only want to guarantee consistent ordering across runs.

**Comment by rbouckaert** [comment]
There are a few other places where HashSets are used, but the RandomTree appears the one that affects the starting state. There is a small performance difference between HashSet and LinkedHashSet (mainly at creation time), but that is worth the added replicability. Will close this for now, until it is proven other bits cause irreproducability under different launch scenarios.
