### ISSUE TITLE
Add DOI and/or URL and/or citation for each package in package manager for better package discovery

### ISSUE THREAD

**Issue by alexeid** [CompEvol/beast2#574]
In the package manager it should be possible to get a link to a paper and/or a URL and/or a DOI describing the package in general and the exact version installed.

**Comment by rbouckaert** [comment]
There are Citation annotations that contain publication info + DOIs already, so perhaps this information can be picked up from these annotations.

What do we do for packages that are the host of multiple publications? Packages can be organised to be unique to publications, but that could result in very fragmented packages.

And what about those having their publication spread over multiple packages (like BFD, BFD*, sampled ancestors)?

Having a URL pointing to package documention sounds really useful.
