### ISSUE TITLE
Gamma distribution parameterisation

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#575]
There are at least 4 possible parameterisations of the gamma distribution
* shape/scale
* shape/rate
* shape/mean
* shape with mean = 1.0
but we only support shape/scale in beast core (there is a version with mean=1 in BEASTLabs).
One way to implement this, and offer a simple interface in BEAUti is to add an enumeration input with each of these four parameterisation options. Since the parameters are called alpha (=shape) and beta, we can use beta for the second parameter -- scale, rate or mean -- (if any).

**Comment by jheled** [comment]
At least according to Wikipedia, {alpha,beta} is {shape,rate}. I think we should name the parameters as they are : shape, rate, mean and scale, and allow only meaningful combinations.

**Comment by rbouckaert** [comment]
That would require BEAUti to have its own interface: first, a way to specify which parameterisation is chosen, then one to bring up (or enable) only those parameters that are relevant.
