### ISSUE TITLE
Logger.openLogFile() occasionally fails with null pointer exception

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#578]
This has come up a few times today at the TTB workshop with users on OS X.  A fix seems to be to tell BEAST to overwrite log files (on the command line or from the launch window), but this problem seems to occur even when no previous log file exists. I haven't been able to reproduce it myself on Linux.

**Comment by rbouckaert** [comment]
This will be hard to fix since it is difficult to reproduce: I am using OS X CLI regularly and have never seen this happening. Is there a pattern in the type of Java versions (minor versions) installed on the computers where this happens?

**Comment by tgvaughan** [comment]
Not that I noticed... :-/
