### ISSUE TITLE
Package manager should provide a link to tutorials for each package.

### ISSUE THREAD

**Issue by alexeid** [CompEvol/beast2#585]
This may be more to do with developing standard practice in combination with #574. If a URL is provided as per #574, then this boils down to encouraging every package to provide on the first page of the package URL a link to a tutorial. We should implement this for the standard packages.

**Comment by tgvaughan** [comment]
I completely agree that this should be linked to #574.  We need a direct route from each package to documentation provided by the package authors.  This would solve a massive problem: there is currently no way for users to find documentation.  We have this horribly fragmented situation where some packages have web pages, some have no web page, some have a tutorial listed on the beast2 web page, others have no tutorials, some use a github or google code or bitbucket repository as their web page...  It's a mess!  By strongly encouraging the provision of a URL and some additional metadata (eg package abstract or tutorial URL) we bring into existence a single official port of call for every package, a natural place for documentation to reside.

**Comment by Graham853** [comment]
I thought the standard place for package documentation was the 'doc' directory in the package itself (see pp208-9 in the BEAST book). If the package manager had a way to open this directory for each installed package, wouldn't that be enough? (Apart from encouraging package authors to put something in it.)

**Comment by tgvaughan** [comment]
This issue is addressed in c5db0dc in that a URL pointing to a project web page is made available.  This is where tutorials should reside.
