### ISSUE TITLE
Add support for multi-type branches in SequenceSimulator

### ISSUE THREAD

**Issue by z3nabi** [CompEvol/beast2#588]
For a structured coalescent model, one can obtain a tree like the following:

((1:0.5,2:0.3):0.4,(3:1.2):0.5);

The branch leading towards taxon 3 is divided into two parts with a migration event in the middle. I don't know if this strictly follows the Newick format, but MASTER produces such output and FigTree and Icytree can read it. However, when feeding it into the SequenceSimulator to simulate under a non-structured model it fails with a rather cryptic error message:

`Fatal exception: null
java.lang.NullPointerException
	at beast.app.seqgen.SequenceSimulator.getTransitionProbabilities(Unknown Source)
	at beast.app.seqgen.SequenceSimulator.traverse(Unknown Source)
	at beast.app.seqgen.SequenceSimulator.traverse(Unknown Source)
	at beast.app.seqgen.SequenceSimulator.simulate(Unknown Source)
	at beast.app.seqgen.SequenceSimulator.run(Unknown Source)
	at beast.app.BeastMCMC.run(Unknown Source)
	at beast.app.beastapp.BeastMain.<init>(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)
	at beast.app.beastapp.BeastLauncher.main(Unknown Source)
Fatal exception: null
`

The behaviour I would expect is that it treats the concatenated branch as a single one of length 1.7.

Here is the corresponding XML file: [seqGen.txt](https://github.com/CompEvol/beast2/files/345794/seqGen.txt)

Cheers,
Simon

**Comment by tgvaughan** [comment]
Hi Simon, thanks for this.  Newick definitely supports non-binary trees, and this should be possible.

**Comment by tgvaughan** [comment]
Hi again Simon, looking at the SequenceSimulator source it seems that there is no easy fix to this on that side: SequenceSimulator uses the same methods that the tree likelihood uses to compute transition probabilities, and those do not currently cope with non-binary trees.  (One could argue about whether this is itself a problem, but changing this is something that can't be done lightly, as the likelihood engine is one of the most tightly optimized parts of beast.)

The fix would therefore be to strip out the internal nodes and simulate sequences down this modified tree.  I could easily add this capability into sequence simulator, but doing so would violate the DRY principle of programming as I've already implemented this in a number of places - including the MASTER package you mentioned.

As described in the [Outputs section of the MASTER manual](https://github.com/CompEvol/MASTER/wiki/output#newickoutput), you can generate these modified trees by using an output like this:
```xml
<output spec='NewickOutput' fileName='binary_only.newick'
            collapseSingleChildNodes='true'/>
```
(You can have as many outputs as you like, so you can also record the full tree if you want.)

The tree stored in `binary_only.newick` should be compatible with SequenceSimulator.
