### ISSUE TITLE
Reusing TaxonSets in MRCAPriors results in duplicate log column headers

### ISSUE THREAD

**Issue by lmaurits** [CompEvol/beast2#592]
The column name for a log entry corresponding to an MRCAPrior is derived from the ID of the underlying TaxonSet:

`out.print("mrcatime(" + taxonsetInput.get().getID() + ")\t");`

If an analysis has two MRCAPriors which use the same TaxonSet (one with useOriginate=true and one with useOriginate=false), which is a legitimate if perhaps uncommon thing to do, then both priors are logged in columns with identical headers.  It is possible to disambiguate, since the originate is necessarily older than the MRCA, but it would be nice if this were handled more gracefully.

We could use column names of "mrcatime(originate(" + taxonsetInput.get().getID() + "))" when useOriginate=true, maybe?  The downside is that analyses with only one MRCAPrior for a TaxonSet with useOriginate=true will then see a change in their logfiles which would likely break compatibility with postanalysis scripts.

**Comment by rbouckaert** [comment]
Commit cf90d47 solves this particular problem, but not the general problem that logs can contain duplicate entries in general (e.g. because items are duplicated in the log).
