### ISSUE TITLE
Unset tip dates aren't set to zero, even though the log suggest so.

### ISSUE THREAD

**Issue by Anaphory** [CompEvol/beast2#593]
When specifying the tip date only for taxa where it deviates from `0`, for example like this

      <tree id="Tree.t:tree" name="stateNode">
        <taxonset id="taxa" spec="TaxonSet">
          <plate range="aas,abf,abg,aiw,kbt" var="language">
            <taxon id="$(language)" />
          </plate>
        </taxonset>
        <trait id="datetrait" spec="beast.evolution.tree.TraitSet" taxa="@taxa" traitname="date">aiw = 678.5</trait>
      </tree>

the command line output suggests that unspecified taxa dates are set to `0`.

    WARNING: no trait specified for aas
    WARNING: no trait specified for abf
    WARNING: no trait specified for abg
    WARNING: no trait specified for kbt
    aas = null (678.5)
    abf = null (678.5)
    abg = null (678.5)
    aiw = 678.5 (0.0)
    kbt = null (678.5)

The resulting starting tree does however not reflect that. (`aiw` is No. 4)

    tree STATE_0 = ((1:0.15022881455374845,3:0.15022881455374845):1.113315594243755,((2:0.10233223884870135,4:0.10233223884870135):0.12112865206483753,5:0.22346089091353888):1.0400835178839645):0.0;

The issue does not appear when one of the date values is set to 0.

    <trait id="datetrait" spec="beast.evolution.tree.TraitSet" taxa="@taxa" traitname="date">aas = 0, aiw = 678.5</trait>
gives

    tree STATE_0 = (1:1.5892932771955657,((2:0.2409011782476321,5:0.2409011782476321):0.49172897855666586,(3:0.3615691598075393,4:0.3615691598075393):0.3710609969967587):679.3566631203913):0.0;

This points to an error coming from the cropping of tip heights according to the min and max of all given root heights, where it should crop according to the min resp. max of *all* root heights instead, including those that are set to 0 implicitly.

**Comment by Anaphory** [comment]
Ah, no. Actually, the error is in combination of `initAndValidate()` with `getValue(String taxonName)`:

`initAndValidate` does not add unspecified taxa to `map`, but moves the `0` of the date axis.
`getValue` can therefore not find a taxon that was unspecified in the definition, and returns the new `0`, which is the minimum or maximum (depending on forwards or backwards dates) of all *specified* dates.

There are three ways around this issue.
1. Leaving a trait unspecified could be a fatal error instead of a warning. In particular there should not be an `info` output suggesting that gaps were filled nicely in this case.
2. The fallback return value of `getValue` becomes `minValue` or `maxValue` (depending on `traitNameInput`).
3. Unspecified taxa are added to the map.

The last one sounds like the least surprising and least intrusive solution.

**Comment by rbouckaert** [comment]
Thanks for the fix & the accompanying junit test!
