### ISSUE TITLE
Parsing MultiTypeTree trait from file does not work as indicated

### ISSUE THREAD

**Issue by z3nabi** [CompEvol/beast2#595]
The MultiTypeTree template in BEAUti allows Tip locations to be read from a file. Next to that dialog one can click on a button with a "?" and gets some info how this file should be formatted. It says there that it should have a header. However, it seems that for this case the header is misinterpreted as another type specification. Removing the header then produces the expected result. Either the message or the read-in behavior should be adjusted.

**Comment by tgvaughan** [comment]
Sorry for the delay on this.  It seems this is the result of a commit made earlier this year (00f99dbc5abeb8000a9218bb374238283bf99a20) in response to issue #247.  As a result,
beast treats any header of the form `the\theader` as a trait assignment `the=header`. Any ideas @rbouckaert? Given that the earlier behaviour was actually just to strip out the header, can't we just remove any mention of a header from the help dialog and instead state that all lines should be of the format `taxon\ttraitvalue`?  This is what is now happening, after all.

**Comment by tgvaughan** [comment]
Thanks, would have done it myself but didn't know anything about the background behind the old message.
