### ISSUE TITLE
3 warnings compiling beast 2.4.3pre in IntelliJ

### ISSUE THREAD

**Issue by zhangchicool** [CompEvol/beast2#606]
Information:Using javac 1.8.0_66 to compile java sources
Information:09/08/2016, 11:38 - Compilation completed successfully with 3 warnings in 18s 62ms
~/BEAST2/beast2/src/beast/evolution/tree/TraitSet.java
Warning:(188, 49) java: parse(java.lang.String) in java.util.Date has been deprecated
~/BEAST2/beast2/src/test/beast/core/BEASTInterfaceTest.java
Warning:(73, 43) java: getCitation() in beast.core.BEASTInterface has been deprecated
~/BEAST2/beast2/src/beast/app/beauti/TipDatesInputEditor.java
Warning:(307, 33) java: parse(java.lang.String) in java.util.Date has been deprecated
~/BEAST2/beast2/src/beast/app/beauti/MRCAPriorInputEditor.java
Information:java: Some input files use unchecked or unsafe operations.
Information:java: Recompile with -Xlint:unchecked for details.

**Comment by rbouckaert** [comment]
The Date.parse is used since it is more powerful than the recommended alternatives.
The call to the deprecated getCitation method is from a test, so is safe to be left.
