### ISSUE TITLE
TreeParser ignores meta data arrays

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#607]
This causes problems for TreeAnnotator when annotating a tree with phylogeographical location information. TreeAnnotator uses TreeSetParser, which is marginally faster but uses a lot more memory. In low-mem mode, TreeAnnotator uses TreeParser, but then it ignores the location attribute, to it won't be able to annotate phylogeography analysis trees.

Fix: make TreeParser process vector metadata.

**Comment by tgvaughan** [comment]
Sorry for the clutter - there's actually only one commit there, the others were broken commits to my fork.
