### ISSUE TITLE
XML output of nodes in alphabetical order would be helpful

### ISSUE THREAD

**Issue by SimonGreenhill** [CompEvol/beast2#611]
It would be helpful if the ordering within specific XML nodes (<state>, <log> etc) was ordered alphabetically or by type. 

For example, I've got one 'Chang-style' analysis which has many partitions, each with a mutation rate and a treelikelihood:

```
        .... many lines omitted...
       <log idref="mutationRate.s:short_u"/>
        <log idref="treeLikelihood.all"/>
        <log idref="mutationRate.s:all"/>
        <log idref="bcov_alpha.s:all"/>
        <log idref="bcov_s.s:all"/>
        <log idref="frequencies.s:all"/>
        <log idref="hiddenfrequencies.s:all"/>
        ... many more mutationRates and TreeLikelihoods.
```

This makes it hard to check what things are being logged, whereas if all mutationRates and treeLikelihoods were grouped together then I could skim through those to find the other parameters. 

This is especially helpful for e.g. the <state> section as there are initialisation and parameterisation settings that can easily be missed.

**Comment by rbouckaert** [comment]
@SimonGreenhill this is related to BEAUti, which is indeed agnostic about the order in which list input (like log on the Logger). A quick fix is to set the sort attribute on the logger to sort="smart" or sort="alphabetic", run the analysis to the point it creates a log file and open the file in tracer. You could also copy and past the log entries in a spreadsheet, sort them and paste them back.

**Comment by rbouckaert** [comment]
In BEAUti in the MCMC panel, for the logger of interest, you can select "alphabetic" for the "Sort" entry. I assume that fixes the issue, but let me know if I misunderstood.
