### ISSUE TITLE
BEAUTI fails to load if it can't find `templates/Standard.xml` in the current directory

### ISSUE THREAD

**Issue by jonchang** [CompEvol/beast2#612]
While writing a Homebrew formula to install BEAST2 (see Homebrew/homebrew-science#4225), I've been having trouble getting BEAUTI to start.

By default, BEAUTI will search the current directory for the file `templates/Standard.xml` when the `-template` argument is not passed to it on the command line; however, this doesn't work for Homebrew installs since the current directory is not where the template XML files are located. (We install BEAST2 to a "Cellar" directory, e.g., `/usr/local/Cellar/beast2/2.4.3/` which is then symlinked into the path, e.g., `/usr/local/bin`).

To fix this, I think modifying [BeautiDoc.java](https://github.com/CompEvol/beast2/blob/29098b9176d2bb2fbb541249a5c21ef2c0a52961/src/beast/app/beauti/BeautiDoc.java#L84) is the answer, but I haven't been able to get it to work. It seems like there's already some infrastructure to search the Java classpath for templates but I'm having trouble getting it to cooperate. Any insight would be appreciated.

**Comment by rbouckaert** [comment]
Thanks for working on a Homebrew formula! 

The first thing BEAST (or BEAUti) tries to do is install itself as a package in `~/Library/Application Support/BEAST/2.4/BEAST`, where it copies the jar files and templates to (see [BeastLauncher](https://github.com/CompEvol/beast2/blob/master/src/beast/app/beastapp/BeastLauncher.java), the class that is used by every application in BEAST to get started). If no arguments are given to BEAUti, it will try to find a package directory containing `template/Standard.xml`, so if the file is copied to the package directory it should load it from there. Can you verify that the template directory in `~/Library/Application Support/BEAST/2.4/BEAST` exists after starting BEAST (or BEAUti)? If not, there may be an issues with BeastLauncher.

**Comment by jonchang** [comment]
Setting `-Dbeast.user.package.dir` on the command line seems to work. Thanks for the pointer!
