### ISSUE TITLE
beauti2.2 crashes when importing alignment

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#616]
We should have an error message rather than a crash.

Alexei

---

From: Todd Knutson 
Date: 13 September 2016 at 5:20:37 AM NZST
To: beast-users beast-users@googlegroups.com
Subject: Re: [FORGED] beauti2.2 crashes when importing alignment
Reply-To: beast-users@googlegroups.com

Hi all, 

I just wanted to mention that I was having a similar problem: Beauti crashing when trying to import a nexus file. I did not immediately realize that my nexus file had the wrong datatype listed in the file header. Mine listed "datatype=DNA", when I was providing amino acid sequences. Thus, simply editing the nexus file to "datatype=protein" solved my Beauti crash problem. This now seems obvious, but I just wanted to post here in case anyone else had similar issue.

Thanks,
Todd

**Comment by walterxie** [comment]
Similar to Todd's post...

I was configuring 14 different files in BEAUTi (12 individual genes, one concatenated dataset, one *BEAST species tree). Only one file (one of the 12 individual genes) was causing the problem of crashing BEAUTi when loaded. I had been using .fasta format for my alignments and after multiple attempts, I switched that one alignment to a .nexus file and it loaded fine.

This seems like an obvious thing to try, but like above felt I should post it here, especially since I didn't see anyone mention using a .fasta file above. I generally prefer .fasta for programs like this because it does not require syntax at the top (ergo, fewer mistakes for me to make).

Cheers,
-John

**Comment by rbouckaert** [comment]
This appears to be caused by the System.exit() call in Alignment. It should throw an exception instead.
