### ISSUE TITLE
RPNcalculator numbers multidimensional parameters starting from 0 in logs

### ISSUE THREAD

**Issue by gavryushkina** [CompEvol/beast2#617]
Although the normal logger numbers starting with 1. Thus in a BDSKY analysis the log file will have:

diversificationRate1
diversificationRate2

and 

birth0
birth1

which is confusing. RPNcalculator should number parameters starting from 1 in logs.

**Comment by rbouckaert** [comment]
Parameters indeed are logged starting with 1 while RPNCalculator (and others, like Script in BEASTLabs) start with 0, which is not consistent. Changing the behaviour means we need a major release.
@gavryushkina does this impacts post processing scripts for BDSKY?
