### ISSUE TITLE
Beauti 2.4.3 freezes on Mac Sierra

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#629]
Hi all,
Im trying to open Beauti 2.4.3 on a recent updated IMac Sierra and it freezes, does anyone is having the same issue?

Thanks
Jose

**Comment by walterxie** [comment]
All applications except DensiTree have the same problem in Mac Sierra, but they are able to run under IDE. The initial investigation shows ANT has version specified code, which may affect BEAST 2 applications launching in Sierra, or even Java 1.8?

        <javac source="1.6"
               target="1.6"
               bootclasspath='/opt/jdk1.6.0_45/jre/lib/rt.jar'
               srcdir="${src}"
               destdir="${build}"
               classpathref="classpath"
               fork="true"
               memoryinitialsize="256m"
               memorymaximumsize="1024m"
               includeAntRuntime='false'>
            <include name="beast/**/*Launcher.java" />
            <include name="beast/**/Utils6.java" />
            <include name="beast/**/BEASTVersion.java" />
            <include name="beast/**/Version.java" />
        </javac>

**Comment by walterxie** [comment]
The problem was not solved after test.  I discovered this problem was caused by not recognised credential for all BEAST apps. To prove it, I manually added a credential to a BEAST app, and then the problem disappeared.

**Comment by walterxie** [comment]
The further investigation showed some root certificates in Mac OS El Capitan 10.11 were removed from macOS Sierra 10.12 . See "Changes to Trusted Root Certificates in Mac OS Sierra and iOS 10", https://www.thesslstore.com/blog/macos-trusted-root-certificates/

**Comment by rbouckaert** [comment]
Looks like releasing from a Sierra machine solves the problem, at least on that same Sierra machine. Needs further testing on another Sierra machine, and non-Sierra machines.

**Comment by walterxie** [comment]
Working on Yosemite 10.10.5

**Comment by afrittspenniman** [comment]
Hi Walter. You said "I manually added a credential to a BEAST app." Can you explain how to do that please? Thanks!

**Comment by walterxie** [comment]
I used "xattr -d -r com.apple.quarantine"

**Comment by alexeid** [comment]
Can we re-release 2.4.3 so that it works on Sierra?

**Comment by alexeid** [comment]
Done — now available as 
https://github.com/CompEvol/beast2/releases/download/v2.4.3/BEAST.v2.4.3Sierra.dmg <https://github.com/CompEvol/beast2/releases/download/v2.4.3/BEAST.v2.4.3Sierra.dmg>
Works on my freshly updated laptop, but that is also the one I used to release from.

**Comment by walterxie** [comment]
All pre2.4.4 apps work on Mac Yosemite 10.10.5.

**Comment by rbouckaert** [comment]
The v2.4.3/BEAST.v2.4.3Sierra.dmg file is now rename https://github.com/CompEvol/beast2/releases/download/v2.4.3/BEAST.v2.4.3.dmg so all links point to the version released under Sierra.
