### ISSUE TITLE
logP being positive infinity

### ISSUE THREAD

**Issue by zhangchicool** [CompEvol/beast2#632]
In rare cases, the tree log likelihood becomes positive infinity, e.g., `if (Double.isInfinite(logP)) return logP`.
Then logAlpha in [MCMC.java](https://github.com/CompEvol/beast2/blob/master/src/beast/core/MCMC.java) is positive infinity too, causing the move being accepted and ending up with log likelihood (prior) being Infinity.
Should logAlpha check this (e.g. [line 436 of MCMC.java](https://github.com/CompEvol/beast2/blob/9a5c80e4ff6d45af908b324c4f7392a01b6dea47/src/beast/core/MCMC.java#L436)), so that the move can be rejected properly?

**Comment by tgvaughan** [comment]
Hi Chi, when does the tree likelihood become infinitiy?  I know Gibbs operators return a HR of +infinity to force an accept, but an infinite likelihood sounds like a bug.

**Comment by rbouckaert** [comment]
Some substitution models can suffer from numeric instability resulting in infinite log likelihoods. I have found bugs in substitution models before by tracing positive infinite likelihoods.

If we fix this, TreeLikelihood is the place to do this, not MCMC (for Gibbs operators, as @tgvaughan  pointed out).

**Comment by zhangchicool** [comment]
I am experiencing this problem when running the skyline fossilized birth-death model (bdsky), and when psi is extremely large, the logp returned is positive infinity.  I agree that we should improve numerical instability in the tree likelihood calculation.  But to prevent really rare cases, should we return Double.NEGATIVE_INFINITY instead of just logP, when logP is infinite?

**Comment by alexeid** [comment]
I think if you want to hack a fix you should hack the class that is broken in BDSKY, and not a core class like MCMC.

**Comment by zhangchicool** [comment]
Hi all, I've done the fix in bdsky. Feel free to close this issue.
