### ISSUE TITLE
TreeParser can't handle metadata keys containing colons

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#640]
For instance, the current grammar rejects the following:

    (A[&my:key=value]:1, B:1);

**Comment by rbouckaert** [comment]
Have you had a look at the [diff](https://github.com/CompEvol/beast2/commit/d2f5497d323d99b01a05e4946d216fa752c0f763)? And that for just adding colon parsing in attribute names?

**Comment by jheled** [comment]
You should exclude generated files, obviously.

**Comment by rbouckaert** [comment]
Agreed -- how do you do that though?

**Comment by jheled** [comment]
I meant "exclude from consideration" when looking at diff size :)

**Comment by tgvaughan** [comment]
Yeah, it sucks having machine-generated .java files in the repository.  Ideally these would be generated at build time.  There was also a class rename involved in the commit, so that shows up in a couple of places in the diff too.

Even without those though, supporting colons in metatdata did require a big change: the lexer is now "modal" in the sense that it has a within-metadata mode and an outside-metadata mode.  ANTLR easily supports this, but requires separate lexer and parser rules files in this case. So while before we had a single Newick.g4 file we now have NewickLexer.g4 and NewickParser.g4.  (In some way this makes NewickParser a bit easier to read anyway.)  The other side-effect is that tokens such as ',' which appear in both modes have to now be specified using their formal names (COMMA).  This is vaguely annoying as it makes the parser rules a bit less visually attractive, but it's necessary.
