### ISSUE TITLE
Future-proof Newick grammar

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#641]
The existing grammar defines a set of characters that are permitted in *unquoted* node labels. Remco suggested replacing this with a much smaller list of expressly forbidden characters.  I think this is a great idea (should have been that way in the first place!).

**Comment by alexeid** [comment]
Do we have a set of Newick files that we have run into trouble with in the past that we test the grammar with in a unit test?

**Comment by tgvaughan** [comment]
I've added the occasional modification to the existing unit tests to include things like colon characters in metadata labels, but we don't have a comprehensive suite, no.  Great idea.
