### ISSUE TITLE
Can't set up discrete traits in BEAUti Partition

### ISSUE THREAD

**Issue by ceya** [CompEvol/beast2#664]
I'm using Window GUI and want to set up discrete trait for nexus alignment file. When I click the "+" button the pop-up window asks for  an alignment input. Does anyone know what went wrong?

**Comment by rbouckaert** [comment]
Discrete traits are supported by the BEAST_CLASSIC package, so you need to install the BEAST_CLASSIC package (easiest done via the menu File/Manage packages in BEAUti) before you can add discrete traits.
There is a tutorial here: https://github.com/BEAST2-Dev/beast-classic/releases/download/v1.3.0/ARv2.4.1.pdf that explains things in more detail.
