### ISSUE TITLE
missing values in tip date calibration

### ISSUE THREAD

**Issue by ceya** [CompEvol/beast2#669]
Hi, I only have the date info for about half of my tip taxa, will BEAST be able to estimate the divergence correctly? And how should the missing values be indicated? Thanks!

Brooke

**Comment by rbouckaert** [comment]
Hi Brooke,
When you say that date info is missing, there still must be some wide age range in which the sample is taken, so you could use a wide prior to capture that information. It depends on how strong the data and how accurate priors for the known tips are whether dates for these tips can be estimated with any kind of accuracy, so you just need to try and see what comes out.

By the way, this kind of question is more appropriate for the [beast-user mailing list](https://groups.google.com/forum/#!forum/beast-users). This issues list are for registering bugs and code enhancements.
