### ISSUE TITLE
Viewing integer alignments in Beauti

### ISSUE THREAD

**Issue by arjun-1** [CompEvol/beast2#674]
Some DataTypes, such as StandardData and IntegerData, separate their states by comma when represented String form. In fact, all DataTypes based on the Base class, for which codeMap == null do this by default.

In AlignmentViewer.java, the method updateTableData does not take care of this case. Instead, it implicitly assumes a String where each character represents a state. Some add-ons however, such as BEASTvntr, represent the String form of their state as comma separated values, which causes the alignment to be improperly displayed.

I have already implemented a quick [fix](https://github.com/CompEvol/beast2/compare/master...arjun-1:master) in my own fork.

**Comment by rbouckaert** [comment]
closed by 0c273149ff6627b0bc37d874be58dfdeb2f12f86
