### ISSUE TITLE
Stack size error

### ISSUE THREAD

**Issue by ViralExanthemata** [CompEvol/beast2#676]
For about one week I cannot run BEAST.

I used the parameters that Veronika and I had worked out the the Taming the BEAST workshop. It worked for 5 different alignments of WGS.
Now I want to perform analysis for a smaller region of the same pathogen but a different outbreak. I also need to include outgroups.
At the first attempt to run BEAST, the error is about tree height. I changed the starting value for origin in BEAUti (as I had not closed the file yet).
Running the corrected file, the error is stack size # (various numbers: 3, 10, 11, and many more) (screenshot attached).

Additionally, BEAUti acts funny. When setting up BEASTModelTest, strict clock, and BirthDeathSkylineSerial, the prior window shows parameters without descriptor (screenshot attached).
I get the expected window after switching back and forth between the prior models. It remains to be determined if this contributes to the error.

[major difference in BEAUti file.pdf](https://github.com/CompEvol/beast2/files/836074/major.difference.in.BEAUti.file.pdf)
[parameters without descriptors.pdf](https://github.com/CompEvol/beast2/files/836073/parameters.without.descriptors.pdf)

and BEAST output:
Random number seed: 1489260057713

JN635404.MVi/Virginia.USA/15.09_2009-04-06_2009.2630: 1180 4
JN635407.MVi/Texas.USA/4.07_2007-01-22_2007.0603: 1180 4
MVs/AbreuLima.PE.BRA/19.13_2013-05-06_2013.3425: 1180 4
MVs/AbreuLima.PE.BRA/49.13/2_2013-12-01_2013.9151: 1180 4
MVs/Alianca.PE.BRA/28.13/2_2013-07-09_2013.5178: 1180 4
MVs/Camaragibe.PE.BRA/18.13/5_2013-05-02_2013.3315: 1180 4
MVs/Caucaia.CE.BRA/48.14/3_2014-11-29_2014.9096: 1180 4
MVs/Forquilha.CE.BRA/31.14_2014-07-31_2014.5780: 1180 4
MVs/Forquilha.CE.BRA/32.14/2_D8_2014-08-09_2014.6027: 1180 4
MVs/Fortaleza.CE.BRA/50.14/4_2014-12-08_2014.9343: 1180 4
MVs/Fortaleza.CE.BRA/53.14/2_2015-01-01_2015.0: 1180 4
MVs/Fortazela.CE.BRA/21.14_2014-05-21_2014.3836: 1180 4
MVs/Goiana.PE.BRA/45.13/6_2013-11-25_2013.8986: 1180 4
MVs/Goiana.PE.BRA/50.13/3_2013-12-09_2013.9397: 1180 4
MVs/Goiana.PE.BRA/50.13/5_2013-12-10_2013.9429: 1180 4
MVs/Groairas.CE.BRA/44.14_2014-10-30_2014.8274: 1180 4
MVs/Maracanau.CE.BRA/53.14/4_2014-12-29_2014.9918: 1180 4
MVs/Olinda.PE.BRA/13.13_2013-04-03_2013.2521: 1180 4
MVs/Paulista.PE.BRA/16.13/4_2013-04-16_2013.2877: 1180 4
MVs/Recife.PE.BRA/47.13/2_2013-11-19_2013.8822: 1180 4
MVs/SenadorSa.CE.BRA/46.14_2014-11-11_2014.8603: 1180 4
MVs/Trairi.CE.BRA/5.14/11_2014-01-27_2014.0712: 1180 4
MVs/Uruburetama.CE.BRA/8.14/2_2014-02-22_2014.1425: 1180 4
MVs/VitSntAntao.PE.BRA/17.13/2_2013-04-28_2013.3206: 1180 4
Alignment(24 strains)
  24 taxa
  1180 sites
  51 patterns

JN635404.MVi/Virginia.USA/15.09_2009-04-06_2009.2630 = 2009.263 (5.73700000000008)
JN635407.MVi/Texas.USA/4.07_2007-01-22_2007.0603 = 2007.0603 (7.9396999999999025)
MVs/AbreuLima.PE.BRA/19.13_2013-05-06_2013.3425 = 2013.3425 (1.6575000000000273)
MVs/AbreuLima.PE.BRA/49.13/2_2013-12-01_2013.9151 = 2013.9151 (1.0849000000000615)
MVs/Alianca.PE.BRA/28.13/2_2013-07-09_2013.5178 = 2013.5178 (1.4821999999999207)
MVs/Camaragibe.PE.BRA/18.13/5_2013-05-02_2013.3315 = 2013.3315 (1.6684999999999945)
MVs/Caucaia.CE.BRA/48.14/3_2014-11-29_2014.9096 = 2014.9096 (0.09040000000004511)
MVs/Forquilha.CE.BRA/31.14_2014-07-31_2014.5780 = 2014.578 (0.42200000000002547)
MVs/Forquilha.CE.BRA/32.14/2_D8_2014-08-09_2014.6027 = 2014.6027 (0.3973000000000866)
MVs/Fortaleza.CE.BRA/50.14/4_2014-12-08_2014.9343 = 2014.9343 (0.06570000000010623)
MVs/Fortaleza.CE.BRA/53.14/2_2015-01-01_2015.0 = 2015.0 (0.0)
MVs/Fortazela.CE.BRA/21.14_2014-05-21_2014.3836 = 2014.3836 (0.6164000000001124)
MVs/Goiana.PE.BRA/45.13/6_2013-11-25_2013.8986 = 2013.8986 (1.1014000000000124)
MVs/Goiana.PE.BRA/50.13/3_2013-12-09_2013.9397 = 2013.9397 (1.0603000000000975)
MVs/Goiana.PE.BRA/50.13/5_2013-12-10_2013.9429 = 2013.9429 (1.0570999999999913)
MVs/Groairas.CE.BRA/44.14_2014-10-30_2014.8274 = 2014.8274 (0.17260000000010223)
MVs/Maracanau.CE.BRA/53.14/4_2014-12-29_2014.9918 = 2014.9918 (0.008199999999987995)
MVs/Olinda.PE.BRA/13.13_2013-04-03_2013.2521 = 2013.2521 (1.7479000000000724)
MVs/Paulista.PE.BRA/16.13/4_2013-04-16_2013.2877 = 2013.2877 (1.7122999999999138)
MVs/Recife.PE.BRA/47.13/2_2013-11-19_2013.8822 = 2013.8822 (1.1177999999999884)
MVs/SenadorSa.CE.BRA/46.14_2014-11-11_2014.8603 = 2014.8603 (0.13969999999994798)
MVs/Trairi.CE.BRA/5.14/11_2014-01-27_2014.0712 = 2014.0712 (0.9287999999999101)
MVs/Uruburetama.CE.BRA/8.14/2_2014-02-22_2014.1425 = 2014.1425 (0.8575000000000728)
MVs/VitSntAntao.PE.BRA/17.13/2_2013-04-28_2013.3206 = 2013.3206 (1.679399999999987)
Starting frequencies: [0.2952683615819209, 0.39413841807909605, 0.2028954802259887, 0.10769774011299435]
TreeLikelihood(treeLikelihood.24 strains0) uses BeerLikelihoodCore4
  Alignment(24 strains): [taxa, patterns, sites] = [24, 51, 1180]
Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path
with (Math) { function f(BMT_ProportionInvariable, hasInvariableSites) { return BMT_ProportionInvariable * hasInvariableSites;}
}
with (Math) { function f(BMT_gammaShape, hasGammaRates) { return BMT_gammaShape * hasGammaRates;}
}

Error 110 parsing the xml input file

validate and intialize error: Error in expression: Stack size 3 ( != 1 ) at end of expression evaluation

Error detected about here:
  <beast>
      <run id='mcmc' spec='MCMC'>
          <logger id='tracelog'>
              <log id='birth.t:24 strains' spec='beast.math.statistic.RPNcalculator'>

java.lang.RuntimeException: Error in expression: Stack size 3 ( != 1 ) at end of expression evaluation
	at beast.math.statistic.RPNcalculator.initAndValidate(Unknown Source)
	at beast.util.XMLParser.initBEASTObjects(Unknown Source)
	at beast.util.XMLParser.parse(Unknown Source)
	at beast.util.XMLParser.parseFile(Unknown Source)
	at beast.app.BeastMCMC.parseArgs(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)
	at beast.app.beastapp.BeastLauncher.main(Unknown Source)

**Comment by rbouckaert** [comment]
Hi Helene,

At first glance, this looks like a problem with the RPNcalculator, which can happen when there are spaces or other special characters in variable names (see #369). When that happens, the RPN calculator throws an exception and this may also explain the weird behaviour of BEAUti.

Is it possible that you used quite different names for the alignment that contain spaces?

If not, would you mind emailing the XML so I can investigate what is going wrong?
Cheers,
Remco

**Comment by ViralExanthemata** [comment]
Hello Remco,

I have shortened the name (and there are no spaces in the name), but the error remains.
Attached please find a small data set. Hopefully it is not going to be too complicated.
Please treat the data confidentially.

Cheers,

Helene

**Comment by rbouckaert** [comment]
It was indeed a space in the file name “24 strains” that caused the hiccup. Replacing every “24 strains” with “24_strains” solves the problem (though #369 is still open).

**Comment by ViralExanthemata** [comment]
Thank you.
I was looking for spaces in the strain names and overlooked the file name.
