### ISSUE TITLE
povitive priors lead to likelyhood < posterior

### ISSUE THREAD

**Issue by ViralExanthemata** [CompEvol/beast2#680]
Please comment on this scenario. What could have happened?

V. pointed out to me that this should not happen.
She explains it as follows: "The values of posterior, prior and likelihood are the log (probability) of a given state. Since the probability is never larger than one, in fact it always has to be between 0 and 1, then the log of that should always be below zero, thus negative."
This makes totally sense to me. 

Example: My alignment contains many identical nucleotide sequences (viral isolates from cases in outbreak). My supervisor believes that I need to keep them all in, while I wanted to explore what difference it makes to remove identical sequences. My major concern were the the non-sense trees resulting from MCMC runs.

- 22 unique strains from one outbreak with 2 outgroups (these oldest samples are present in all alignments and date 8.3 and 6.1 years before the present). --> mean tree height 10.7 years, mean origin 11.1 years
- adding 27 additional unique strains from other outbreaks to the existing alignment --> mean tree height 9.7 years, origin 10 years
- adding all strains to the alignment (total no 166, of which 115 are non-unique strains) --> mean tree height drops to 8.5 years, origin 8.7 years. This is the first time that I have a positive prior.
 
Therefore I revisited the xml file and fixed the normal distribution of becomingUninfectiousRate to log normal. (idea from http://www.beast2.org/tag/prior/). But prior remains positive.
This does not make a difference though for the normal distribution for the first 2 alignment files. Their prior is negative. 

Please advise.

**Comment by tgvaughan** [comment]
It is perfectly acceptable to have positive values for the prior, likelihood and posterior values that BEAST records in its log files.  All of these are in general probability _densities_, not probabilities, so the only constraint is that they are positive.  Thus the log of each of these can fall anywhere at all on the real number line, i.e. -Inf < log(p) < +Inf, where p is the prior/likelihood/posterior.  (Strictly speaking, log densities can actually have a value of -Inf, but this should never appear in the output as BEAST will never accept states that have a probability of zero.)

**Comment by ViralExanthemata** [comment]
Thank you.

**Comment by tgvaughan** [comment]
Definitely add all of the strains, identical or not.  I don't know specifically why the tree height posterior behaves this way as a function of your data, but it's an error to filter the samples according to sequence.  For example, removing all the duplicates will cause the model to overestimate the population size or clock rate: you're essentially saying that your population is more genetically diverse than it actually is.

**Comment by tgvaughan** [comment]
Btw, it's best to post questions like this to the beast-users mailing list.  These issues are primarily for reporting bugs and requesting features.
