### ISSUE TITLE
Proposal ratio in the scale operator

### ISSUE THREAD

**Issue by zhangchicool** [CompEvol/beast2#682]
I have a concern about the proposal ratio in the scale operator.

To scale a single parameter _t_ (e.g. the root height) with a scaler _c_,  so that _t_' = _t_ _c_, the proposal ratio should be _c_ [1]. But it seems 1/_c_ in the code.

To scale _m_ variables with the same scaler _c_ (e.g. all node heights or a vector), the proposal ratio should be _c_^_m_ [1]. But it seems _c_^(_m_ - 2) in the code.

Please correct me if I am wrong :P

[1] Section 7.2.5 in Yang, Z. 2014. Molecular Evolution: A Statistical Approach. Oxford University Press.

**Comment by jheled** [comment]
It all depends how 'c' is sampled. This is the right HR for this specific operator. There are proofs, but no simple ones. You can convince yourself your suggested HR is wrong by modifying the code and running just the prior.

Stranger things have been spotted in the skies, but not by reliable witnesses (misquoting Douglas Adams)

**Comment by alexeid** [comment]
As Joseph points out, there are various alternatives on the distribution to draw ‘c’ from, and in general they will give rise to different HR. In BEAST2 for the operators I believe you are talking about ‘c’ is drawn from a uniform distribution between b and 1/b, where 0 < b < 1. I guess that the HR you are quoting from Zheng Yang’s book assume that ‘c’ is drawn from a different distribution.

**Comment by zhangchicool** [comment]
Not surprising I am wrong. I didn't seriously consider how _c_ is drawn...

**Comment by lmaurits** [comment]
Why _do_ we sample 'c' from this particular and, to my intuition, at least unusual distribution of U(b,1/b)?  Yang's ratios of c and c^m seem "nicer" than 1/c and c^{m-2}.  I presume the BEAST way of doing things makes something else I haven't considered nicer to compensate?

**Comment by alexeid** [comment]
I vaguely recall trying to assess which is more efficient under different scenarios but I don’t think I got very far.. If one where provably more efficient for something like a lognormal target in n dimensions then I would chose that one :)
