### ISSUE TITLE
RealParameter::scale should return number of elements scaled

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#686]
Correct me if I'm wrong, but I'm almost certain that if x is a RealParameter, x.scale(0.8) should return the number of elements actually affected by the scaling operation.  At the moment, scale() just returns the total number of elements.  This distinction is important when elements of the RealParameter are zero.  If a parameter has n elements of which only m are non-zero, the HR for the scale move with randomly chosen scale factor f should be f^(m-2), not f^(n-2), since there are only m degrees of freedom.  As the UpDownOperator uses the return value of RealParameter::scale to compute the HR for that move, it will be wrong when applied to parameters with one or more zero-valued elements.

**Comment by tgvaughan** [comment]
[Here's](https://github.com/CompEvol/beast2/files/940436/testUpDown.xml.txt) an example XML.  IMO this should produce a uniform distribution on x1.  With the addition of the UpDownOperator (which in this case only has x as the single `up` parameter), it doesn't.

**Comment by alexeid** [comment]
I agree with you.

**Comment by rbouckaert** [comment]
Yes, that makes sense.

**Comment by tgvaughan** [comment]
Grey is sampled posterior from test XML before change to scale() return value, blue is result from same XML after change:
![density_compare](https://cloud.githubusercontent.com/assets/512538/25252906/dc8ce00c-2672-11e7-97f8-40f86af67977.png)
