### ISSUE TITLE
Deprecate Node::getLeft, getRight, setLeft, setRight

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#690]
Seeing as Nodes can technically have any number of children and we already have an API that exposes this, and seeing that the listed methods are themselves implemented in terms of this API, it is probably time to start formally phasing them out.  If we don't deprecate them they will continue to be used by package authors, who do would not otherwise know that we are trying to shift away from the binary assumption.

**Comment by rbouckaert** [comment]
Agreed
