### ISSUE TITLE
TreeAnnotator with CA option only sets CA height, not other CA attributes.

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#691]
As pointed out by Mike [here](http://markmail.org/message/53dxgyz5vc3x3xvq?q=beast-users+list:com%2Egooglegroups%2Ebeast-users+date:201704+Common+Ancestor), when annotating a tree with the common ancestor option (the default) node heights get set using Common Ancestor heights, but all other attributes (height, length, etc) and their 95%HPDs are set from the clade's attribute. This can lead to big differences in interval and CA node height. Perhaps all attributes should be calculated from the set of nodes that are CA nodes instead of the clade.

**Comment by alexeid** [comment]
agreed.

**Comment by rbouckaert** [comment]
Not sure how to deal with branch lengths, and their 95%HPDs: there will be many zeros from trees that have topologies different from the annotated tree topology, so many branch lengths will get a 95%HPD with zero as lower bound.

Say, we have three trees:
((A:1,B:1):1,C:2)
((A:1.1,B:1.1):1.1,C:2.2)
(A:2,(B:1,C:1):2)

So, the most common topology is ((A,B),C) and 
for (A,B) we have heights 1, 1.2, and 2, with mean height 1.4
for (A,B,C) we have heights 2 2.1, and 2 with mean height 2.03
The difference is 1, 0.9, 0 so the mean length is 0.63 and 95% HPD [0.0, 1.0].

**Comment by rbouckaert** [comment]
Commit 1ff38d2 added CAheight_mean, CAheight_95%_HPD, CAheight_median and CAheight_range attributes to the tree (only when CA heights are used), but left the height, height_95%_HPD, height_median and height_range attributes. All other attributes (length, geographical position, etc) are still calculated from the MRCA clade.
