### ISSUE TITLE
*BEAST + phylogeography has taxa missing

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#7]
### What steps will reproduce the problem?
1. start *BEAST analysis
2. add phylogeography trait
### What is the expected output? What do you see instead?

Expected to be able to specify location for taxa.
There is only a single dummy taxon.
Needs to make all taxa in species tree available.

**Comment by rbouckaert** [comment]
If no taxon set is defined for the species tree, the phylogeography trait has no taxa to specify locations for. I don't think it is reasonable for the geography model to guess these taxa. If between step 1 and 2 the taxon set is specified in the taxonset panel, this is no problem any more.
