### ISSUE TITLE
Beauti clock model cloning problem (STACEY, StarBeast v1)

### ISSUE THREAD

**Issue by Graham853** [CompEvol/beast2#701]
Start Beauti 2.4.6 (also 2.4.5)
Choose STACEY or StarBeast template
Load 26.nex, 29.nex, 47.nex
Clock Model, change 26 to relaxed log normal
Select all, clone from 26
Save. 
The XML won't run in BEAST.

Error 110 parsing the xml input file

validate and intialize error: Operator updown.all.Species.29 has a statenode clockRate.c:29 in its inputs that is missing from the state.

**Comment by rbouckaert** [comment]
The up-down operator is cloned from the catch-all generic up-down operator, but that should not happen. This can be prevented somewhat inelegantly by adding in a connector rule to disconnect any accidentally cloned up-down operator.
