### ISSUE TITLE
Name of getAllChildNodes() in Node is confusing

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#703]
The function `List<Node> getAllChildNodes()` in `Node` returns all child nodes including this node. Very confusing, but only update the JavaDoc.

**Comment by alexeid** [comment]
That seems like an error. If it is not, then the name of the method should change, or it should be deprecated and a new method with an appropriate name should be added.

**Comment by walterxie** [comment]
@rbouckaert @tgvaughan 
I checked the core and several common packages, this method `getAllChildNodes()` is never used. Just curios, do you use it or know any package use it?

**Comment by rbouckaert** [comment]
It is used in Babel and Bacter.
