### ISSUE TITLE
allow multifurcating tree 

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#704]
@alexeid @rbouckaert @tgvaughan 
The current implementation of Node and Tree limited to binary tree only #690. Replacing `getLeft() getRight()` to `getChildren()` shouldn't be difficult to most methods, such as the change of #371. 

I create a branch CompEvol/beast2/multifurcating for our collaboration to solve this issue. My first commit includes adding a `binarize` flag mentioned in #495, and updating `toNewick()`. A simple test `testMultifurcatingTree()` is also created to show the existing problems.

**Comment by walterxie** [comment]
One current problem is :

Expected :(A:0.1,B:0.2,(C:0.3,D:0.4):0.5);
Actual   :(A:0.1,B:0.2,(C:0.2,D:0.09999999999999998):-0.3);

The topology is imported and printed correctly, but the node height calculated from branch length is wrong. This is caused by using `getLeft() getRight()` in both `convertLengthToHeight()` and `offset()`.

**Comment by walterxie** [comment]
The parser is nearly working for multifurcating tree except of one small problem on the precision of decimals on branch lengths:

Expected :(A:0.1,B:0.2,(C:0.3,D:0.4):0.5);
Actual   :(A:0.09999999999999998,B:0.20000000000000007,(C:0.30000000000000004,D:0.4):0.5):0.0;

**Comment by tgvaughan** [comment]
Hi Walter, looks like we've doubled up on this a bit.  The above commit (not yet merged) provides (1) TreeParser support for reading in non-binary trees, (2) full Node support for writing out non-binary trees via the various Newick generation methods, and (3) unit tests for the additional functionality in the TreeParser and Node classes.

I haven't encountered any of the rounding error problems you're seeing, bug I can't say why.  You might want to glance over the code in the commit to see if we've done something differently.

**Comment by walterxie** [comment]
Unit tests are passed
