### ISSUE TITLE
Wrong user-locale settings will confuse the nexus output

### ISSUE THREAD

**Issue by LinguList** [CompEvol/beast2#708]
I don't regularly use java programs, and somehow, my Linux machine uses the German locale when writing beast output. This is deleterious for the nexus, as dots will be rendered as commata.

After changing the beast-shell-file from

```shell
  $JAVA -Xms64m -Xmx4g -cp "$BEAST_LIB/launcher.jar" beast.app.beastapp.BeastLauncher $*
```
to 
```shell
  $JAVA -Duser.language=en -Xms64m -Xmx4g -cp "$BEAST_LIB/launcher.jar" beast.app.beastapp.BeastLauncher $*
```
everything worked fine.

You may consider adding this as a default?

**Comment by LinguList** [comment]
Just to make this more clear: all instances, where you'd use a "." to indicate floating point numbers, will be written with a comma, which destroys the nexus format...

**Comment by tgvaughan** [comment]
Hi @LinguList, thanks for the bug report and for the suggested fix.  I think this is possibly something that we should fix at a lower level though, either by hard-coding the locale (maybe heavy-handed but the BEAST UIs don't make any serious attempt at localization anyway - hard-coded strings galore) or by forcing the format of floating points in the NEXUS output at the float serialization level.

**Comment by rbouckaert** [comment]
@tgvaughan: saw your comment while committing the heavy handed hard coding of locales. Recently, I saw a glitch where text on a dialog was replaced by some Chinese font, which should be fixed by this as well.
