### ISSUE TITLE
Dead links on beast.bio.ed.ac.u

### ISSUE THREAD

**Issue by richelbilderbeek** [CompEvol/beast2#718]
I wanted to report two dead links on [beast.bio.ed.ac.uk](beast.bio.ed.ac.uk). 

 * Go to [http://beast.bio.ed.ac.uk/faq#What_do_all_the_parameters_do.2Fmean.3F](http://beast.bio.ed.ac.uk/faq#What_do_all_the_parameters_do.2Fmean.3F)
 * click on the hyperlink to [http://beast.bio.ed.ac.uk/Parameters](http://beast.bio.ed.ac.uk/Parameters) 
 * find a 'Page not found' error.

![broken_url](https://user-images.githubusercontent.com/2098230/28358895-db255d86-6c70-11e7-813f-fc0f3512409c.png)

Same for [http://beast.bio.ed.ac.uk/faq#Optimizing_operators](http://beast.bio.ed.ac.uk/faq#Optimizing_operators) and clicking on hyperlink to [http://beast.bio.ed.ac.uk/Increasing_ESSs](http://beast.bio.ed.ac.uk/Increasing_ESSs)

Keep up the good work!

**Comment by rambaut** [comment]
This website is being replaced by a new one covering BEAST v1.X material. Currently at https://github.com/beast-dev/doc (with front facing at http://beast-dev.github.io/doc/ ).
