### ISSUE TITLE
Incorrect warning message?

### ISSUE THREAD

**Issue by gaberoo** [CompEvol/beast2#723]
Hi guys,

I've been playing around with BEAST2—I know, took me long enough. I get this warning message when I launch, even though I specify a BD tree prior... not sure if this is some sort of orphaned code. I'd just thought I'd let you know.

```
1043 = 2014 (1.0)                      
1044 = 2014 (1.0)                      
1045 = 2014 (1.0)                      
1046 = 2014 (1.0)                      
1047 = 2014 (1.0)                      
1048 = 2014 (1.0)                      
WARNING: Yule Model cannot handle dated tips. Use for example a coalescent prior instead.                                                                    
  Using BEAGLE version: 2.1.2 resource 0: CPU                                 
    with instance flags:  PRECISION_DOUBLE COMPUTATION_SYNCH EIGEN_REAL SCALING_MANUAL SCALERS_RAW VECTOR_SSE THREADING_NONE PROCESSOR_CPU FRAMEWORK_CPU     
  Ignoring ambiguities in tree likelihood.                                    
  Ignoring character uncertainty in tree likelihood.                          
  With 21993 unique site patterns.     
  Using rescaling scheme : dynamic     
===============================================================================                                                                              
Citations for this model:              

Bouckaert RR, Heled J, Kuehnert D, Vaughan TG, Wu C-H, Xie D, Suchard MA,     
  Rambaut A, Drummond AJ (2014) BEAST 2: A software platform for Bayesian     
  evolutionary analysis. PLoS Computational Biology 10(4): e1003537           

Gernhard 2008. The conditioned reconstructed process. Journal of Theoretical Biology Volume 253, Issue 4, 21 August 2008, Pages 769-778                      

Hasegawa M, Kishino H, Yano T (1985) Dating the human-ape splitting by a      
  molecular clock of mitochondrial DNA. Journal of Molecular Evolution        
  22:160-174.                          

===============================================================================                                                                              
Start likelihood: -741453.3704905291   
Writing file dropped_UW1_80.log        
Writing file dropped_UW1_80.trees      
         Sample      posterior ESS(posterior)     likelihood          prior   
              0   -741453.3704              N   -741407.8131       -45.5573 --
           1000   -366844.9593         2.0      -366853.4935         8.5341 --
           2000   -314793.7560         3.0      -314775.5386       -18.2173 --
```

**Comment by SimonGreenhill** [comment]
This is because the [BirthDeathGernhard08](https://github.com/CompEvol/beast2/blob/c87b363a2b53ddb32b9b4d7d58648efdf15a4004/src/beast/evolution/speciation/BirthDeathGernhard08Model.java#L57) model extends from YuleModel. It confused me too. Thought I created an issue for it then, but can't see it anywhere.

**Comment by denisekuehnert** [comment]
The warning is justified because the BirthDeathGernhard08
<https://github.com/CompEvol/beast2/blob/c87b363a2b53ddb32b9b4d7d58648efdf15a4004/src/beast/evolution/speciation/BirthDeathGernhard08Model.java#L57>
doesn't
allow serial sampling. In the likelihood calculation it assumes all samples
have the same height (0.0), which is wrong for your data set as far as I
can see.

2017-08-17 21:13 GMT+02:00 Simon J Greenhill <notifications@github.com>:

**Comment by tgvaughan** [comment]
@denisekuehnert Good point.  The error is still confusing though, because it uses the wrong name for the model.  We should update this in the Yule class.

**Comment by tgvaughan** [comment]
The above commit (which should read "Improved NON-ulatrametric tree error message"...) just makes the error message a bit more generic.  There's a separate issue that BEAUti displays no warning when the birth death tree prior is selected.  (BEAUti warns the user when the Yule model is selected for a non-ultrametric tree.

**Comment by tgvaughan** [comment]
Thoughts about a better warning/error system for these kinds of problems are welcome over at issue #727.
