### ISSUE TITLE
The "-prefix" option doesn't work as expected in BEAST v2.4.7

### ISSUE THREAD

**Issue by yjx1217** [CompEvol/beast2#725]
Hello,

When I run beast2 with the "-prefix option" like "beast -threads 6 -seed 123456 -overwrite -prefix test test.xml", I got the following error:

Start likelihood: -49423.200573270544 
File error: test/1.log (No such file or directory)
java.lang.RuntimeException: An error was encounted. Terminating BEAST
	at beast.app.util.ErrorLogHandler.publish(Unknown Source)
	at java.util.logging.Logger.log(Logger.java:738)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.log(Logger.java:788)
	at java.util.logging.Logger.severe(Logger.java:1464)
	at beast.app.beastapp.BeastMain.<init>(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)
	at beast.app.beastapp.BeastLauncher.main(Unknown Source)

It is fine if I just run "beast -threads 6 -seed 123456 -overwrite test.xml" without the "-prefix" function.

Also, is it possible to remove some priors under the Priors tab of BEAUti? I think this will be useful if the users added some priors first but later changed their minds. 

Best,
Jia-Xing

Best,
Jia-Xing

**Comment by tgvaughan** [comment]
Hi Jia-Xing, it sounds like this is a badly named option and that it's actually asking for the path to a location where log files will be saved, which is consistent with the error that your "test" directory doesn't exist.

Internally, what you provide as the argument to -prefix _is_ just prepended to the output filename, but a literal forward-slash is inserted between the prefix and suffix.  I expect that this would produce an error on a Windows machine even if the directory existed.  I therefore think the most parsimonious course is to just remove the forward-slash delimiter, which means that the existing command line option will behave as advertised and the OS-dependence will be removed.  (The other  alternative would be to rename the option and use the proper methods to build the final path.)
