### ISSUE TITLE
BEAUti displays no warning when BD prior is selected for non-ultrametric trees.

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#726]
A little red "x" appears when the Yule prior is selected for such a tree:
<img width="1017" alt="screen shot 2017-08-18 at 11 34 58" src="https://user-images.githubusercontent.com/512538/29453301-65463418-8409-11e7-9d10-a0141f7fb7fe.png">

Nothing happens when the BD prior is selected:
<img width="1017" alt="screen shot 2017-08-18 at 11 35 26" src="https://user-images.githubusercontent.com/512538/29453323-7cd87d20-8409-11e7-9351-44f099c92fa7.png">

Both situations produce a warning on the console when the XML is actually run.

**Comment by alexeid** [comment]
If an X appears shouldn’t the XML fail to be produced? Or terminate with an error rather than a warning? Applying such models to non-ultrametric trees is completely meaningless...

**Comment by tgvaughan** [comment]
Hey Alexei, I definitely agree.  That should be a separate issue though, right?  This is just the smaller issue that the existing warning mechanism has some problems.

**Comment by tgvaughan** [comment]
Argh, silly me - after half an hour of hunting it turns out that the little "x" actually is there, it's just that selecting the BD model causes the width of the input pane to overflow the width of the enclosing jscrollpane, meaning that you need to scroll horizontally to see the "x".  The error is definitely too subtle, but my original complaint was invalid.

**Comment by tgvaughan** [comment]
Closing this issue but opening a new one (#727) to discuss better handling of this situation.
