### ISSUE TITLE
"Show list of available BEAGLE resources and Quit" does not work on BEAST 2.4.7 on Mac OS

### ISSUE THREAD

**Issue by laduplessis** [CompEvol/beast2#733]
I've tried this on Sierra and El Capitan on different computers. In both cases BEAST 2.4.7 simply quits when I tick the check box. (BEAST 2.4.7 works and BEAGLE is installed and accessible).

**Comment by tgvaughan** [comment]
When run from the terminal (using `beast -options`), information about BEAGLE resources are sent to standard out, so maybe this is expected behaviour?

**Comment by tgvaughan** [comment]
Although of course this info should be displayed in the pop-up console window if this is available, which it now does.
