### ISSUE TITLE
BEAUti substModelTemplates broken (affect BEAST vntr)

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#738]
This is related to the issue reported https://groups.google.com/forum/#!topic/beast-users/Z80FqmIAltM.

The substitution model in XML was overwritten by JukesCantor:
`<substModel` id="JC69.s:comas2009_VNTR" `spec="JukesCantor"/>`
and the other 4 parameters (biasMagnitude, focalPoint, g, oneOnA1) were missing as well.

The "Site Model" panel in BEAUti had wrong "substitution model" panel when it was loaded at the 1st time, the screen shot was attached. 
![screen shot 2017-10-19 at 3 53 03 pm](https://user-images.githubusercontent.com/5743014/31752349-e3d5bcd2-b4e6-11e7-89fb-0318d0baff44.png)

But if I chose another substitution model and chose back to "Sainudiin", everything seemed to behave normally inlcuding XML.

@rbouckaert I checked the template, and it looked fine, so it seemed something were broken in substModelTemplates merge point.

**Comment by rbouckaert** [comment]
Fixed by 35e4e96d806e4102d90138d840b1d7558f081528
