### ISSUE TITLE
DataType getStatesForCode(int state) returns null

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#739]
This problem was discovered by using `InterData` in Sasha's MM package, where  `dataType.getStatesForCode(k)` would throw null exception because `mapCodeToStateSet` was null if data type was integer.
https://groups.google.com/forum/#!topic/beast-users/lDo2a2g5A6c

@alexeid @rbouckaert 
I suggest to add a validation in `getStatesForCode` as below, and implement `mapCodeToStateSet` in `InterData`. 

```
public int[] getStatesForCode(int state) {
     if (mapCodeToStateSet == null)
// then illegal
     return mapCodeToStateSet[state];
}
```

**Comment by alexeid** [comment]
This code snippet is broken. It will produce a NullPointerException when mapCodeToStateSet is null and has no return value otherwise. It shouldn't even compile. Am I missing something?

**Comment by walterxie** [comment]
That was my lazy typing to save time, and the comment was the code to be implemented. The full version can be:

```
public int[] getStatesForCode(int state) {
      if (mapCodeToStateSet==null)
                throw new IllegalArgumentException("mapCodeToStateSet cannot be null !");
// anything else ?
      return mapCodeToStateSet[state];
}
```

**Comment by tgvaughan** [comment]
Hi Walter, is there even a distinction between "state" and "code" for integer data?  I would have thought the thing to do here would be to have getStatesForCode return something sensible for IntegerData, maybe by overriding `getStatesForCode` in the IntegerData class to be something like:

```java
public int[] getStatesForCode(int state) {
    return new int[]{state};
}
```

Of course, all of that allocation seems a bit messy...

Actually given that there's no default value for the `mapCodeToStateSet` field, maybe  it makes sense to instead instead have the following implementation in DataType.Base:

```java
public int[] getStatesForCode(int state) {
    return mapCodeToStateSet == null
               ? new int[]{state}
               : mapCodeToStateSet[state];
}
```

**Comment by alexeid** [comment]
Like

**Comment by walterxie** [comment]
Hi, Tim, just have a quick chat with Remco. If the assumption is no "code map" for integer data, then your code is perfect. 

I wonder (not for this issue but generally) whether anyone wants to map multiple sets of integer data to something?

**Comment by walterxie** [comment]
@gavryushkina 
Hi, Sasha, 
If I replace `getStatesForCode(int state)` to the above code, BEAUti works with your integer example data set [M3982asInt.nex](https://github.com/CompEvol/morph-models/blob/master/examples/nexus/M3982asInt.nex), but XML fails to run in BEAST.
I could not find the example XML using integer data type in MM. But I guess the `totalcount="4"` is a problem. 

Are you happy I update `getStatesForCode(int state)` and close this issue?

```xml
<data id="M3982asInt" dataType="integer">
                        <sequence id="seq_Anolis_acutus" taxon="Anolis_acutus" totalcount="4" value="002102113450710001234567"/>
...
```

**Comment by gavryushkina** [comment]
Hi Walter, 

I would also add gaps and/or missing char. Also It was not me who made this example and the integer datatype. Probably, it was Remco or Joseph. May be confirm with them too.

**Comment by walterxie** [comment]
@alexeid @tgvaughan @gavryushkina @rbouckaert 
Hi, all,
After my investigation, we are not ready to support "integer" data type in Sasha's MM package. I am going to commit the above code and remove the example data set M3982asInt.nex, after Remco agreed. I will also make a clarification shortly in the user forum that MM only takes "standard" data type.

Cheers,
Walter

**Comment by alexeid** [comment]
Must be pretty simple to fix it? Why don’t we do that?
