### ISSUE TITLE
Tip Dates tab goes blank

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#742]
From beast-users mailing list:

I'm running into an issue importing dates to BEAUTI. I can successfully import from a tab-delimited text file but this only works for half of the samples? I can't find any formatting error in the text file. Any help would be fantastic! Thank you!

Link to original post: https://groups.google.com/forum/#!topic/beast-users/6b8RJzxmOcI

Files referenced in post:
  * [sample_alignment.fa](https://github.com/CompEvol/beast2/files/1485893/sample_alignment.fa.txt)
  * [date_trait.txt](https://github.com/CompEvol/beast2/files/1485894/date_trait.txt)

**Comment by tgvaughan** [comment]
The issue title is different from the report, but I can reproduce the "going blank" thing with the release version.  This this has been brought up in another issue #728 regarding recovering from errors in BEAUti.  In the development version the "going blank" thing doesn't happen anymore, but there is a residual problem in reading the formatted dates from this file - which we should definitely solve.

**Comment by walterxie** [comment]
Yes, it is solved.
