### ISSUE TITLE
End likelihood is different between using and not using BEAGLE 

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#748]
End likelihood is different between using and not using BEAGLE. 

As you can see, the "Start likelihood" is slight different in the beginning. My sense is the code below in line 96 `BeagleTreeLikelihood::initAndValidate` made the difference:
```java
if (forceJava) {
    return;
}
```

To replicate, change the `chainLength="1"` in either testRNA.xml or testGTR.xml, and fix the seed to something like 777:

===========================
testRNA.xml, BEAGLE CPU:

Start likelihood: -10081.09510401371

Filter 2-457,660-896
12 taxa
693 sites
361 patterns
  Using BEAGLE version: 2.1.2 resource 0: CPU
    with instance flags:  PRECISION_DOUBLE COMPUTATION_SYNCH EIGEN_REAL SCALING_MANUAL SCALERS_RAW VECTOR_SSE THREADING_NONE PROCESSOR_CPU FRAMEWORK_CPU
Filter 1,458-659,897-898
12 taxa
205 sites
79 patterns
  Using BEAGLE version: 2.1.2 resource 0: CPU
    with instance flags:  PRECISION_DOUBLE COMPUTATION_SYNCH EIGEN_REAL SCALING_MANUAL SCALERS_RAW VECTOR_SSE THREADING_NONE PROCESSOR_CPU FRAMEWORK_CPU

End likelihood: -9781.006799392306

===========================
testRNA.xml, no BEAGLE:

Start likelihood: -10081.095104013712 

Filter 2-457,660-896
12 taxa
693 sites
361 patterns
TreeLikelihood(treeLikelihood.coding) uses BeerLikelihoodCore4
  FilteredAlignment(coding): [taxa, patterns, sites] = [12, 361, 693]
Filter 1,458-659,897-898
12 taxa
205 sites
79 patterns
TreeLikelihood(treeLikelihood.noncoding) uses BeerLikelihoodCore4
  FilteredAlignment(noncoding): [taxa, patterns, sites] = [12, 79, 205]

End likelihood: -9781.00679939231  

===========================
testGTR.xml, BEAGLE CPU:
Start likelihood: -10081.09510401371 
End likelihood: -9781.006799392306

testGTR.xml, no BEAGLE:
Start likelihood: -10081.095104013712 
End likelihood: -9781.00679939231

@alexeid @rbouckaert @tgvaughan

**Comment by rbouckaert** [comment]
I think the problem you observed is due to the MCMC loop being run once when you set chainLength to 1. Use a different seed where the first proposal is rejected (e.g. 1516070127131 with testRNA.xml seems to work) and I get exactly the same start and end likelihood because the first proposal is rejected and start and end state are the same.

**Comment by rbouckaert** [comment]
I misunderstood: both end likelihoods differ. But the difference is between
-9781.006799392306 and
-9781.00679939231
that is
       0.000000000004 + 4e-12
which is at machine precision, probably due to the order in which Java and BEAGLE performs floating point calculations.

Anyway, it is nothing to worry about, in my opinion.

**Comment by tgvaughan** [comment]
I agree, this is not an issue. We also have a unit test now that checks for differences between the two likelihood calculations.  This difference is below the tolerance for that test.
