### ISSUE TITLE
Package manager should make project links compulsory 

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#754]
@alexeid @rbouckaert @tgvaughan 
When you open Package Manager in BEAST 2.4.x, there are 1/3 of listed packages no link, which means users cannot find the information about those packages. I think all packages have to provide either a publication link or a tutorial link (Github looks fine to me), if we are going to promote them from  our software. I recommend to make at least name, link and detail (3) columns to be compulsory. If any package does not have these, then Package Manager should not show it.

It is a good chance for BEAST 2.5.x to fix this issue. What do you think?

**Comment by alexeid** [comment]
sounds good to me.

**Comment by rbouckaert** [comment]
Perhaps the package url could be the re-interpreted and used as default?
E.g. for url="https://github.com/BEAST2-Dev/bdsky/releases/download/1.3.2/BDSKY.addon.1.3.2.zip" we have projectURL="https://github.com/BEAST2-Dev/bdsky/"

**Comment by tgvaughan** [comment]
I was hoping to just embarrass package authors into adding links, but it seems this isn't working.  Making it mandatory is a nice idea, although I'd prefer not infer URLs if at all possible.  Actually, I'd personally be inclined to _forbid_ github.com pages (as opposed to github hosted websites) as source code repositories are not generally friendly sources of information for users, and we want the system to encourage authors to provide proper documentation.

**Comment by walterxie** [comment]
@alexeid @rbouckaert @tgvaughan 
I made this important change to Package Manager just now. If any package were not providing the valid URL, the Package Manager wouldn't display it any more. I also manually completed all `projectURL` in `packages.xml`, and Remco seemed fixing `packages-extra.xml` today. So, we have the same starting point now.

@tgvaughan 
I do not like to make this being auto-detected, I think package developers should take it into account before releasing their packages.

@rbouckaert 
Are you going to release this in 2.5.0? If yes, then we need to make an announcement somewhere, beast-dev or user-group?

**Comment by tgvaughan** [comment]
Any chance this can be made optional for packages that are not in the "blessed" CBAN repository?  Otherwise we prevent people from using experimental packages in third-party repositories, as those packages rarely have (non-github) project pages.  It's still nice in these situations to be able to say "this model is highly experimental, but if you still want to give it a try just add the following third party package repository (TPPR :-) ) and click install.
