### ISSUE TITLE
Bundle jre with release 2.4.8

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#755]
Since BEAST 2.4.* works only with Java 8, and now Java 9 is getting widely used, it would be good to have releases with the jre bundled so users can just download BEAST without having to install java. 

There are entries in the `build.xml` file suggesting how to do this. Unfortunately, for the case of OS X at least, that does not actually work. A workaround is for the BeastLauncher (which requires Java 6 or higher to be available, but does work with Java 9) to check that a jre is bundled, and launch a separate process with the java from that jre. This should be for the v2_4_7 branch.

**Comment by walterxie** [comment]
If a JRE is bundled, you might have to consider the situation when the bundled JRE is conflict to the local default JRE/JDK.

**Comment by tgvaughan** [comment]
Great idea, this will definitely solve a lot of problems - past, present and future.

**Comment by tgvaughan** [comment]
Although hopefully this doesn't make things harder for cluster users.

**Comment by rbouckaert** [comment]
There will be ant tasks for both non-bundled and bundled versions, so I don't think this will be a problem for cluster users if they stick with the non-bundled versions.

**Comment by rbouckaert** [comment]
Fixed by  6fe0b20
