### ISSUE TITLE
User-configurable command line parameter specification

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#756]
I frequently find myself in a situation where I need to run a number of analyses (usually on a cluster) that differ only in the value of some parameter.  My usual solution is to create a "template" beast input file where the parameter value in question is replaced by something like %BETA%, and then use sed or m4 or whatever to replace this by a specific value.  This is fine, but given that we already have string substitutions as part of the XML parsing phase (eg $(seed) and $(filebase)), it would be easy to add some general purpose substitutions such as $(arg1), $(arg2), etc and introduce a new beast command line option like -args [val1 [val2 [...]]] to supply values for these substitutions.

I know this feature would only target a small subset of users, and that in a sense it goes against the philosophy of having a static XML containing all information used to run it, but I think that the pattern I described common enough that a solution like this might make life easier for quite a few people.

Any thoughts?

**Comment by rambaut** [comment]
See BEASTGen (although called 'BEAST'Gen it is a general-purpose utility for creating phylogenetic input files from templates:

https://github.com/beast-dev/beast-mcmc/tree/master/release_beastgen/common

Might spin this out into a separate repo...

**Comment by tgvaughan** [comment]
Thanks Andrew, I'll have a look.

**Comment by rbouckaert** [comment]
@tgvaughan Looks like BEASTGen is exactly what you describe, except BEASTGen produces an extra XML file, while your proposal would run BEAST without intermediate XML. Does that seem like a workable compromise?

@rambaut I would appreciate it if you can separate it out into a repo: it would be trivial to wrap it into a BEAST 2 package, so it can be more widely advertised and is easier to find for users.

**Comment by tgvaughan** [comment]
@rbouckaert Perhaps, although like I said: given the presence of the existing substitution mechanism it'd be nice to be able to avoid having a separate parsing step.  This wasn't exactly my problem, it's super easy to do simple substitutions using m4/sed, but it's really nice to not have to - even automatically - create a distinct file for each parameter combination.

**Comment by rbouckaert** [comment]
How about using BEASTGen's interface: <code>-D "chain_length=10000000,log_every=1000"</code>? That will fit well with BeastMain's argument handling, and makes for flexible XML.  Of course <code>-args</code> instead of <code>-D</code> would be fine too.

**Comment by rbouckaert** [comment]
As you said, all the machinery is there so it was not hard at all.

Just to clarify what is implemented: there is now a <code>-D</code> option for BEAST that takes as argument a comma separated string with name-value pairs, e.g. <code>-D "chain_length=10000000,log_every=1000"</code>. Every occurrence of <code>$(name)</code> will be replaced by <code>value</code> in the XML in a pre-processing step, so for instance <code>$(chain_length)</code> will be replaced by <code>10000000</code> and <code>$(log_every)</code> with <code>1000</code> in the example above.
