### ISSUE TITLE
Operator p(m) weights reported incorrectly 

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#758]
Operator p(m) weights were being reported incorrectly in operator report when subschedules were used. 

Add the following xml to testHKY.xml to test:

```xml
<operatorschedule id="operatorSchedule" spec="OperatorSchedule">
    <!-- assign 50% of total weight to operators that apply to the tree operations -->
    <subschedule id="operatorTrees" spec="OperatorSchedule" weight="50" weightIsPercentage="true" operatorPattern="^.*tree.*">
        <subschedule id="operatorTreeScale" spec="OperatorSchedule" weight="50" weightIsPercentage="true" operatorPattern="^.*treeScale.*"/>
    </subschedule>
</operatorschedule>
```

After using "subschedule", the `totalWeight` in `OperatorSchedule` is not the local `totalWeight` in `OperatorSchedule.reweightOperators()`.

**Comment by walterxie** [comment]
@rbouckaert @alexeid 
Alexei tried to fix it by allowing to setWeight in the method `reweightOperators()` but it only worked for one "subschedule" and failed for nested "subschedule"s.

The alternative solution is to record the scale factor between the `totalWeight` in `OperatorSchedule` and the local `totalWeight` in `OperatorSchedule.reweightOperators()`, so that the correct `totalWeight` can be used in `String prettyPrintOperator(...)` to print the report.

**Comment by rbouckaert** [comment]
It probably makes sense to put this in a separate test XML file -- say testOperatorSchedule.xml -- so it is easier to find if you are interested in operator schedules. The file testHKY.xml is just the minimal case to get a phylogenetic analysis going, not a place to add bells and whistles.

**Comment by walterxie** [comment]
I added https://github.com/CompEvol/beast2/blob/master/examples/testOpSubSchedule.xml in https://github.com/CompEvol/beast2/commit/957c98f9b4075b7c41e97cc817775d34f8296921. But not sure why build was failed. It looks like a Travis bug https://github.com/travis-ci/travis-ci/issues/9112?

**Comment by alexeid** [comment]
thanks for fix, sorry about that.

**Comment by tgvaughan** [comment]
@alexeid no worries, I love mysteries :-)
