### ISSUE TITLE
Degrees of freedom in ScaleOperator and UpDownOperator

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#761]
There are a couple of minor limitations in the existing scale operators relating to DoF calculations:

1. When applied to trees, ScaleOperator uses a Hastings ratio that assumes each internal node height adds one DoF, with a special exception being made for zero-length edges above leaf nodes.  This is fine, but I wonder whether it might be better to simply subtract the _total_ number of zero length edges here, as this would also properly account for internal zero-length edges.

2. When applied to parameters with the scaleAll, the ScaleOperator currently does not account for zeros in the parameter, meaning that the HR will be wrong in this case.  (This is a bug.)

3. While the UpDownOperator _does_ account for zeros in parameters, neither it nor ScaleOperator correctly handle parameters with elements having the same value.  This is the same as the issue with ScaleOperator applied to nodes having the same age.  Elements with the same value as other elements do not contribute an additional DoF, meaning the HR will be wrong if the current operators are applied to such parameters.

1 and 3 aren't really issues to anybody not developing new models, but it would be great to have the existing set of scaling operators be a bit more robust/future-proof in this regard.

**Comment by alexeid** [comment]
Tim,

I understand when a parent-daughter pair of nodes have the same age, they they are effectively one node and one degree of freedom. But is it always the case that two parameters that happen to have the same value only add one degree of freedom? What if the two parameters represented two nodes ages on different sides of the tree. I assume you would say that the only way they could be the same is if they are logically connected in the model in some way? Otherwise if they were conditionally independent random variables they would (almost) never have the same value. Is that the reasoning?

Alexei

**Comment by tgvaughan** [comment]
Hi Alexei, yes that's the reasoning.  I guess this is complicated slightly by the non-zero possibility of two values having the same IEEE 754 floating point values, but true independent real random variables should never have exactly the same value unless there is a model-specific reason for this to occur.
For nodes on different sides of the tree, this could be a correlated birth event (I'm sure you know that certain Lambda-coalescent models allow for this).

At the moment I really only care about the tree scaling (1) because it would dramatically simplify the beauti integration for [a polytomy sampler I've implemented](http://github.com/tgvaughan/pitchfork) by allowing the up/down operators provided by the substitution model templates to be immediately compatible.  (In the same way that the SA-specific modifications made possible the beauti integration of that model.)  But I was hoping that maybe we could anticipate some similar problems before they arise, and address them all in a slightly more general way.

Feel free to just close the issue though :-) I definitely don't want to encourage package-specific modifications to the core, unless they are (at least potentially) more generally useful.

**Comment by alexeid** [comment]
Thanks for elaboration. I agree with you. The non-zero probability you speak of is vanishingly small apart from for certain types of initialisation, so far enough after burn-in the assumption is extremely accurate. I would go with your suggested fix if it can be implemented efficiently. But I am worried that it won’t be possible to do more efficiently than a sort, which would be very problematic for large problems.

**Comment by rbouckaert** [comment]
Hi Tim, Since there is no reason not to implement issue 1, and it helps with pitchfork, I say go for it.

**Comment by tgvaughan** [comment]
Thanks Remco, and I agree Alexei - a sort would be problematic.  So instead I will go with just (1) generalizing UpDown to skip zero-length internal nodes and (2) fixing the parameter scaling issue in ScaleOperator when scaleAll is turned on (to bring it in line with the behaviour of UpDown).  I'll leave the rest alnoe for now.

**Comment by tgvaughan** [comment]
Addressed 1, fixed 2, wontfix 3.

**Comment by tgvaughan** [comment]
Actually @rbouckaert : the most computationally efficient way to address the zero-length internal edge problem was to have Node::scale return the DoF count for the corresponding subtree.  Although this doen't affect how Node::scale is used, this changes the type signature of the method so it's still an API change.  I'm hoping this is okay given the major version bump?
