### ISSUE TITLE
empty list should be invalid to be a value in Input.setValue(…) 

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#773]
In Java, when you get(0) from an empty list, it would throw java.lang.IndexOutOfBoundsException:
https://stackoverflow.com/questions/14636204/when-using-get0-on-an-empty-list-i-get-an-out-of-bounds-exception-and-not

If an empty list is passed to setValue(…) in Input.java, where “((List<?>) value).get(0)” in line 435 will throw the exception. 

@alexeid @rbouckaert @tgvaughan 
We should make the empty list invalid to be a value in Input.setValue(…).

**Comment by walterxie** [comment]
add validation to stop to use the empty list in line 431 c2cf688

**Comment by walterxie** [comment]
Unit tests are passed in my Mac, but failed in Travis using Docker with a JVM issue:

    [junit] # A fatal error has been detected by the Java Runtime Environment:
    [junit] #
    [junit] #  SIGSEGV (0xb) at pc=0x00007f675368341a, pid=675, tid=0x00007f67543fb700
    [junit] #
    [junit] # JRE version: OpenJDK Runtime Environment (8.0_162-b12) (build 1.8.0_162-8u162-b12-1~deb9u1-b12)
    [junit] # Java VM: OpenJDK 64-Bit Server VM (25.162-b12 mixed mode linux-amd64 compressed oops)
    [junit] # Problematic frame:
    [junit] # C  [libc.so.6+0x8441a]
    [junit] #
    [junit] # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
    [junit] #
    [junit] # An error report file with more information is saved as:
    [junit] # /root/beast2/hs_err_pid675.log
    [junit] #
    [junit] # If you would like to submit a bug report, please visit:
    [junit] #   http://bugreport.java.com/bugreport/crash.jsp
    [junit] # The crash happened outside the Java Virtual Machine in native code.
    [junit] # See problematic frame for where to report the bug.
    [junit] #
    [junit] Running test.beast.integration.ExampleJSONParsingTest
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec
    [junit] Test test.beast.integration.ExampleJSONParsingTest FAILED (crashed)
    [junit] Running test.beast.integration.ExampleXmlParsingTest

**Comment by walterxie** [comment]
change to java:8-jre 5b065e6bde5250cf65e6349284cb563be0a62b6c, but /bin/sh: 1: git: not found

**Comment by walterxie** [comment]
After reverting my change to 11251e6ab0cf2622e40672c6b5d07e2f88257012, it has the same JVM error, which confirms docker openJDK issue.

**Comment by walterxie** [comment]
Running Oracle Java on Docker? You're Breaking the Law. https://blog.takipi.com/running-java-on-docker-youre-breaking-the-law/

What !?

**Comment by walterxie** [comment]
It is not BEAST problem. Move to Docker openJDK 8 issue #774

**Comment by rbouckaert** [comment]
Why is this throwing an exception, instead of just leaving the state of the list input unaltered?
