### ISSUE TITLE
Docker openJDK 8 issue

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#774]
`test.beast.integration.ExampleJSONParsingTest` and `test.beast.integration.ExampleXmlParsingTest` are failed because of JVM issue: 

    [junit] Running test.beast.integration.DocumentationTest
    [junit] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.881 sec
    [junit] Running test.beast.integration.ExampleJSONParsingTest
    [junit] #
    [junit] # A fatal error has been detected by the Java Runtime Environment:
    [junit] #
    [junit] #  SIGSEGV (0xb) at pc=0x00007f176472741a, pid=122, tid=0x00007f176549f700
    [junit] #
    [junit] # JRE version: OpenJDK Runtime Environment (8.0_162-b12) (build 1.8.0_162-8u162-b12-1~deb9u1-b12)
    [junit] # Java VM: OpenJDK 64-Bit Server VM (25.162-b12 mixed mode linux-amd64 compressed oops)
    [junit] # Problematic frame:
    [junit] # C  [libc.so.6+0x8441a]
    [junit] #
    [junit] # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
    [junit] #
    [junit] # An error report file with more information is saved as:
    [junit] # /root/beast2/hs_err_pid122.log
    [junit] #
    [junit] # If you would like to submit a bug report, please visit:
    [junit] #   http://bugreport.java.com/bugreport/crash.jsp
    [junit] # The crash happened outside the Java Virtual Machine in native code.
    [junit] # See problematic frame for where to report the bug.

**Comment by walterxie** [comment]
I do not think it is the BEAST code problem, the tests are passed in my Mac.

<img width="360" alt="screen shot 2018-04-24 at 5 02 37 pm" src="https://user-images.githubusercontent.com/5743014/39167089-59bf1884-47e1-11e8-90c9-05c6944fb070.png">

I also tried to increase the JVM memory, but it did not fix the problem. 

I forked the code https://github.com/walterxie/beast2, and error can be seen https://travis-ci.org/walterxie/beast2

**Comment by tgvaughan** [comment]
This wasn't a JDK problem, just an issue with the library search path.
