### ISSUE TITLE
CUDA error: "Out of memory" from file <GPUInterfaceCUDA.cpp>, line 269

### ISSUE THREAD

**Issue by zhaojunpeng1991** [CompEvol/beast2#782]
When I using the GPU to run beast, it run err.
The err is CUDA error: "Out of memory" from file <GPUInterfaceCUDA.cpp>, line 269.

I want to know how to use many GPUs to run one beast ?

"beast -beagle_GPU speNet-MNRCpst.xml 1>logs 2>errs"

**Comment by rbouckaert** [comment]
With `beast -beagle_info` information about what resources BEAGLE supports is printed out (with resource numbers).

If the alignment is too large to fit a single GPU, you can try to split it in different partitions.

The `-beagle_order` option allows you to choose the order in which partitions are spread over the different GPUs and CPUs. For example `beast -beagle_order 1,2,0,0,0 speNet-MNRCpst.xml` would put the first partition on resource 1, the second on resource 2, the third, fourth and fifth on resource 0 (typically the CPU) and any higher numbered partitions on 1, 2, 0, 0 and 0 (in that order) again. You have to experiment to see what combination fits on the resources you have available.
