### ISSUE TITLE
Sharp spikes in posterior trace random local clock

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#785]
From user forum:

Dear all,

I have a strange posterior trace in a Random Local Clock analysis with one locus (Beast2).

There are very sharp peaks in the posterior (up to 10000 log units) (and in the likelihood trace as well).

Regardless of how badly my operators might be tuned, how far from convergence I am and the prior settings, I do not understand how this is possible:

While it is possible that in one move the chain moves to a much higher posterior (up the spike), It is my understanding that moves with such a remarkable decrease of posterior (down the spike) should be very unlikely to be accepted.

The spikes do not correlate with any major change in the mean clock rate, height of the tree or population size  

And the same dataset analyzed under a strict or a relaxed exponential clock does not show this behavior.

Any hints on what is happening?

Thanks a lot

Fabrizio

<img width="460" alt="screen shot 2018-06-05 at 10 20 11 am" src="https://user-images.githubusercontent.com/5743014/40945281-3854be4c-68ac-11e8-8cd8-fdb126bfabc4.png">

**Comment by rbouckaert** [comment]
Is this replicable?

**Comment by walterxie** [comment]
Yes. It is not always happened, but it seems there is a certain condition in operators to trigger it. I managed to replicate this problem using seed 5010.

<img width="787" alt="screen shot 2018-06-05 at 11 28 37 am" src="https://user-images.githubusercontent.com/5743014/40946798-a954467e-68b3-11e8-9ebf-6da73525aff9.png">

**Comment by tgvaughan** [comment]
Is there a test input file associated with this issue? If not we won't be able to reproduce.

**Comment by walterxie** [comment]
@tgvaughan 
I am investigating at the moment. I will email you separately if you are interested.

**Comment by tgvaughan** [comment]
Is this using BEAGLE or the native likelihood code?

**Comment by tgvaughan** [comment]
Okay, I think I've managed to reproduce the issue in [this minimal example](https://github.com/CompEvol/beast2/files/2080308/rlc_problem.xml.txt) by taking the original (private) XML kindly provided by the author of the post, stripping out all the data (sequences and dates) and replacing it with an artificial alignment of 3 very short sequences.  The problem appears very quickly (running at 4s/Msamples):

![screen shot 2018-06-07 at 2 06 53 pm](https://user-images.githubusercontent.com/512538/41098551-16c400b0-6a5c-11e8-9474-ce99571517a8.png)

A couple of observations:

1. I can only reproduce this with BEAGLE enabled.
2. The example uses FilteredAlignment, so the example represents 12 SNPs with a total alignment length of ~4e6.  Using smaller values for the constantSiteWeights input (i.e. shorter total alignment lengths) seems to stop the problem appearing.

Sounds like this might be a numerical issue.

**Comment by walterxie** [comment]
I think I find the bug:
It seems when the "correction" is trigger in the MCMC class, the posterior is logged before the value is corrected. I listed two examples below. For example, 891000 was rejected, the 1st acceptance is 890973. When 891000 logged, it should log "-5545472.672374763" (not -5545342.63678185).  

The current log file is:
890000	-5545478.479248722
891000	-5545342.63678185 (should be -5545472.672374763)
892000	-5545472.437449116

I have to go, but will continue on Monday.

Cheers,
Walter

################ seed 5010 ###############

890898 SubtreeSlide(CoalescentConstantSubtreeSlide.t:data):-0.22245733812451363 -5545474.818831889 -5545474.596374551 accept
890904 ScaleOperator(ClockRateScaler.c:data):131.11405962387397 -5545344.2578321155 -5545474.818831889 accept
890973 ScaleOperator(PopSizeScaler.t:data):0.4634494428975051 -5545342.63678185 -5545344.2578321155 accept
... reject
891000 SubtreeSlide(CoalescentConstantSubtreeSlide.t:data):-130.2208491396159 -5545472.8576309895 -5545342.63678185 reject
P(posterior) = -5545472.672374763 (was -5545342.63678185)  **
	P(prior) = 49.69622680941946 (was 49.69622680941946)
		P(CoalescentConstant.t:data) = -4.805632420125249 (was -4.805632420125249)
		P(RRateChangesPrior.c:data) = -2.791759469228055 (was -2.791759469228055)
		P(RRatesPrior.c:sdata) = 59.99729392117876 (was 59.99729392117876)
		P(KappaPrior.s:data) = -1.4679482906070658 (was -1.4679482906070658)
		P(PopSizePrior.t:data) = -1.2357269317989314 (was -0.0781261090787678)  **
	P(likelihood) = -5545522.368601572 (was -5545392.333008659)  **
		P(treeLikelihood.data) = -5545522.368601572 (was -5545392.333008659)  **

Likelihood incorrectly calculated: -5545342.63678185 != -5545472.672374763(130.0355929126963) Operator: beast.evolution.operators.SubtreeSlide

891001 SubtreeSlide(CoalescentConstantSubtreeSlide.t:data):-0.27792717702686787 -5545472.95030194 -5545472.672374763 accept

### summary of posterior
890898	-5545474.596374551
890904	-5545474.818831889	
890973	-5545344.2578321155
891000	-5545342.63678185 rejected (was -5545342.63678185)
891001	-5545472.672374763 

### current log file
890000	-5545478.479248722
891000	-5545342.63678185 (should be -5545472.672374763)
892000	-5545472.437449116


9530944 ScaleOperator(ClockRateScaler.c:data):1.4621214444314528 -5545262.62568272 -5545263.337998295 accept
9530967 ScaleOperator(ClockRateScaler.c:data):0.002894996944935574 -5545262.624261908 -5545262.62568272 accept
9530980 ScaleOperator(PopSizeScaler.t:data):0.5175528614770832 -5545262.2935554385 -5545262.624261908 accept
...
9531000 SubtreeSlide(CoalescentConstantSubtreeSlide.t:data): direct reject
P(posterior) = -5545433.553045537 (was -5545262.2935554385)  **
	P(prior) = 89.99314351883947 (was 89.99314351883947)
		P(CoalescentConstant.t:data) = 15.391872568990564 (was 15.391872568990564)
		P(RRateChangesPrior.c:data) = -1.0 (was -1.0)
		P(RRatesPrior.c:sdata) = 69.3104811936808 (was 69.3104811936808)
		P(KappaPrior.s:data) = -2.0794241311890023 (was -2.0794241311890023)
		P(PopSizePrior.t:data) = 8.370213887357103 (was 8.370213887357103)
	P(likelihood) = -5545523.546189056 (was -5545352.286698957)  **
		P(treeLikelihood.data) = -5545523.546189056 (was -5545352.286698957)  **

Likelihood incorrectly calculated: -5545262.2935554385 != -5545433.553045537(171.25949009880424) Operator: beast.evolution.operators.SubtreeSlide

9531009 BitFlipOperator(IndicatorsBitFlip.c:data):-1.3868073475638274 -5545433.553558524 -5545433.553045537 accept
9531016 BitFlipOperator(IndicatorsBitFlip.c:data):1.3868073475638274 -5545433.553045537 -5545433.553558524 accept

### summary of posterior
9530944	-5545263.337998295
9530967	-5545262.62568272
9530980	-5545262.624261908
9531000	-5545433.553045537 (was -5545262.2935554385)
9531009	-5545433.553558524

### current log file
9530000	-5545430.063779781
9531000	-5545262.2935554385 (should be -5545433.553045537)
9532000	-5545434.466494479

**Comment by walterxie** [comment]
Hi Tim. The summary of posteriors above was using your minimal example. I think the BEAGLE numerical difference to Java likelihood calculation made the rising interval, and my summary above showed how this peak was "recovered" by the "correction" code in line 411 `oldLogLikelihood = state.robustlyCalcPosterior(posterior);`, which was falling interval. 

The "correction" mechanism that I meant is the code inside `MCMC.doLoop()`:  
In the line 386 `if` statement, the code checks whether the posterior is correctly calculated, If the current posterior (`originalLogP`) is too different (`isTooDifferent`) to `logLikelihood` (`state.robustlyCalcPosterior(posterior)`) , then it corrects it using the posterior "robustly" re-calculated from the `state` in line 411.

There are 2 separated issues here: 
1. The BEAGLE numerical difference to Java likelihood calculation (which I have not solved yet) causing the significant rising; 
2. The "correction" recovering the jump causing falling. Is this appropriate while the error message is printed but the analysis still continues after correction? If the correction is trusted, then we can simply log it in the log file because it is used by the next state anyway, otherwise it is another bug (should be exception?).

**Comment by walterxie** [comment]
@tgvaughan This test shows the BEAGLE numerical difference to Java likelihood calculation, where the starting point is the state having a problem running your XML. I will see whether I can narrow down the problem further.

**Comment by walterxie** [comment]
I committed my code to https://github.com/BEAST2-Dev/BEASTLabs/blob/master/src/test/beast/evolution/likelihood/TreeLikelihoodRLCTestDraft.java.
My simple code only checks the certain state, which is not equivalent to BEAST 2 `MCMC`. It looked given the same state but different values, there were no significant difference (>1e-6) between two calculations each time. I wonder if there is a code accumulating this difference during MCMC.
