### ISSUE TITLE
make XML reference manual online

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#790]
We need an automatically-generated XML reference manual online.

**Comment by walterxie** [comment]
From Remco:
beast.app.DocMaker goes a long way to doing just that — the only thing missing is a way to put the HTML output online — it could benefit from some style improvements.

**Comment by walterxie** [comment]
The current code creates empty html pages when the page is failed during the creation, where most of them are **abstract** classes. I modify the script to remove the failed page from the list, which is shown below, so that those empty html pages are not created. 

```Java
    public DocMaker() {
...
//        for (String beastObjectName : m_beastObjectNames) {
        Iterator<String> iter = m_beastObjectNames.iterator();
        while (iter.hasNext()) {
            String beastObjectName = iter.next();
            try {
                Class<?> _class = Class.forName(beastObjectName);
                BEASTObject beastObject = (BEASTObject) _class.newInstance();
...
            } catch (Exception e) {
                Log.err.println(beastObjectName + " not documented (or abstract class) :" + e.getMessage());
                rmFailedPageFromBeastObjectNames(beastObjectName, iter);
            }
        }
    } // c'tor

    // if the page creation is failed, it should not have html
    private void rmFailedPageFromBeastObjectNames(String beastObjectName, Iterator<String> iter) {
        iter.remove();
        Log.err.println("Remove " + beastObjectName + " from the list of BEAST objects");
    }
```

**Comment by walterxie** [comment]
I add a front page for users. Is there any volunteer to have a look the site and give some comments?

http://www.beast2.org/xml/

**Comment by rbouckaert** [comment]
Somehow, the link on the front page to http://www.w3schools.com/xml/ gives a blank screen in Firefox. Reloading does not fix it. In Safari, clicking the link does not produces any result. For both browsers, right click, open link in new tab does produce the expected page.
