### ISSUE TITLE
StateNode subclasses and implementations of StateNode::restore

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#794]
Every concrete `StateNode` subclass implements the `restore()` method.  Along with restoring the portion of the state associated with the subclass, the method is responsible for resetting the `hasStartedEditing` flag to false.  This flag is internal to the StateNode class and is a crucial part of the StateNode and CalculationNode update mechanism.  If the flag is not reset, this mechanism is broken and the usual "error calculating likelihood" messages are produced.

I'd argue that as this flag is set by methods implemented directly in StateNode, it should also be reset at the StateNode level rather than at the concrete subclass level.  The current situation leaks internal bookkeeping details to developers, resulting in state caching problems that can be very difficult to diagnose.

It would be very easy to provide a concrete and final method (`restoreSateNode()`?) in StateNode to simply reset the `hasStartedEditing` flag and then call the abstract `restore()` method.  This wouldn't change the existing API but would remove the requirement that implementations of `restore()` reset this flag.  (Although of course they're still welcome to, it just becomes a redundant operation.)

**Comment by tgvaughan** [comment]
@rbouckaert feel free to revert if you disagree.

**Comment by alexeid** [comment]
Sounds like a good idea to me. There will be better encapsulation of core behaviour and one less trap for developers. If I understand it will require some very small changes in the way the core calls restore methods on StateNodes (i.e. the core code will call restoreStateNode() method instead of restore() method), but it will require no changes to existing implementations of StateNodes, which is a good thing.

**Comment by tgvaughan** [comment]
@alexeid That's right: the proposed fix (commit b45831f) includes a one-line change to the restore code in State, but does not affect the methods overridden by implementations of StateNode.  The only impact is that the `hasStartedEditing=false` statements in those implementations are now redundant.
