### ISSUE TITLE
Default values for user-defined variables

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#795]
One  issue with the existing user-defined variable system is that XMLs that make use of such variables cannot be run without the variables being specified on the command line.  Allowing default values to be specified in the XML would make it possible to include some flexibility in the XML without making the standard analysis harder to run.

On the other hand, removing this "cost" for adding variables could make their use more popular: maybe we don't actually want this.  After all, these variables mean that the information required to repeat an analysis is no longer entirely contained in the XML file...

Assuming we did implmement this, a nice syntax for specifying default values could be `$(myvar=default_val)`.  I'm not sure how we'd handle multiple occurrences of the same variable.  I'd probably vote for allowing a maximum of one of these occurrences to include a default value (produce an error if multiple are found) and using that default for all occurrences.  (Allowing different occurrences to have distinct default values seems wrong: a single variable name should be bound to a single value when we only have one scope.)

**Comment by tgvaughan** [comment]
In case anybody stumbles across this and wonders why it no longer works, support for this was been removed as part of an extensive number of changes belonging to commit 56bdc7a.

**Comment by rbouckaert** [comment]
Oops, that needs reinstating -- I reopened the issue.

**Comment by tgvaughan** [comment]
@rbouckaert Thanks - I would have just replaced it, but didn't want to assume that there wasn't a good reason (parsing performance?) for removing it.

**Comment by rbouckaert** [comment]
Sorry, I accidentally overlooked it when working on the parameter annotation issue. I cannot see any reason for not reinstating this (parsing performance is not really an issue, given it is a one-off activity only for starting an analysis). 
Unfortunately, there was no unit test to warn about it, so perhaps adding one to keep this feature alive would be helpful. Simply testing whether any object parser with an id of the form `$(myvar=default_val)`, then checking whether it actually id equals `default_value` could be a simple test for this.
