### ISSUE TITLE
Problem with $JAVA_HOME on Mac

### ISSUE THREAD

**Issue by rmarquezp** [CompEvol/beast2#799]
The Oracle update for Java 1.8 gets intslled in 
/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

on some macs. 

Setting the JAVA_HOME variable to this location creates problems when running BEAST apps (e.g. beauti and beast itself) because of the white space in the Internet Plug-ins folder, which leasd to the message: 

"BEAST 2.5.0/bin/beauti: line 32: /Library/Internet: No such file or directory"

When trying to run apps. 

I was able to fix this by adding quotes around the $JAVA variable at the end of the launcher scripts, e.g.:

"$JAVA" -Dlauncher.wait.for.exit=true -Xms256m -Xmx4g -Djava.library.path="$BEAST_LIB" -Duser.language=en -cp "$BEAST_LIB/launcher.jar" beast.app.beauti.BeautiLauncher -capture $*

Thanks!

**Comment by tgvaughan** [comment]
Thanks Roberto!
