### ISSUE TITLE
BEAUti: lack of prior for estimated frequencies

### ISSUE THREAD

**Issue by adamallo** [CompEvol/beast2#803]
BEAUti does not populate a _Prior_ option for the equilibrium frequencies when these are estimated in the analysis. I think the default value for this _Prior_ in previous BEAST versions was U[0,1], so basically, the current version of BEAUti is forcing users to use this default. However, it looks weird that a member of the _State_ does not have its counterpart in the _Prior_, and it does not give users the flexibility of using the distribution they want.

**Comment by rbouckaert** [comment]
Good point -- not sure why it took us so long to fix this.
