### ISSUE TITLE
Detect or compare the Java major number from a Java version string

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#806]
There is a demand for developers to detect or compare the Java version by a Java version string, such as #805. I then add a new JavaVersion class for this purpose.

**Comment by rbouckaert** [comment]
Can't you just add this as a beast.app.utils.Utils method?

**Comment by walterxie** [comment]
It will be more than 100 lines. I think it'd better to be separated.

**Comment by alexeid** [comment]
How about remove the weird and unnecessary main method from beast.app.util.Utils and add the new method into there?

**Comment by rbouckaert** [comment]
@alexeid that weird method is used to detect whether CUDA with BEAGLE is installed on OS X -- it fails by killing the process, which is detected by the BeastLauncher. Better keep it in place (and add a comment why it is there).

**Comment by alexeid** [comment]
Why an undocumented main? That seems unnecessarily obscure. Surely it should be a documented method called from some other standard main?

**Comment by walterxie** [comment]
I documented in the above commit.

**Comment by rbouckaert** [comment]
Utils6 cannot depend on Utils, since Utils6 is Java 6 compatible for the launcher to check the Java version is at least 8, but Utils has some dependency on Java 8 so cannot be merged with Utils6.
Perhaps the java version stuff could be in Utils6?

**Comment by walterxie** [comment]
The Java version stuff is moved to `Utils6 `, and I also documented "Utils6 cannot depend on Utils".
