### ISSUE TITLE
javaVersionCheck not working for Java 1.6

### ISSUE THREAD

**Issue by chennyhui** [CompEvol/beast2#811]
I have a Mac running El Capitan with a non-CUDA compatible GPU. I tried to run BEAUTi 2.5.1 today and I got the following message:

![error message](https://user-images.githubusercontent.com/1514484/45805900-517c2c80-bcf2-11e8-84d1-fb3447f98f3e.png)

None of the aforementioned folders exist. When I do a search for NVIDIA and CUDA, some folders belonging to python Anaconda packages pop up, but conda seems to think I don't have CUDA installed. Would appreciate any help to get BEAUTi running!

**Comment by rbouckaert** [comment]
The CUDA check tries to start a program that uses BEAGLE if available, and when it fails pops up this message, so perhaps there is something else preventing a tree likelihood calculation, and this is one of the things supposed to be fixed by the v2.5.1 release.

Can you start BEAST from a terminal, like so:

    java -jar /Applications/BEAST\ 2.5.1/lib/beast.jar /Applications/BEAST\ 2.5.1/examples/testHKY.xml

and tell whether BEAST starts, or if it fails, what the terminal output is? 

A quick work-around for now is to use BEAST v2.5.0, which does not suffer from this problem -- it will still show in BEAUti that you are using v2.5.1, but the v2.5.0 launcher should not stop on the CUDA test.

**Comment by chennyhui** [comment]
From the terminal, BEAST v2.5.1 failed to start, with the following error message:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: beast/app/beastapp/BeastMain : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```
When I ran `java -version` it told me I had 1.6.0_65 even though I have the Java 8 JRE, so I downloaded and installed the JDK and that solved the problem. BEAUTi and BEAST v2.5.1 run fine now.

**Comment by rbouckaert** [comment]
Thanks for reporting this. It appears that the java version check is broken; this particular situation should have been captured before the CUDA check is performed. Anyway, glad to see things are working now.

**Comment by walterxie** [comment]
@rbouckaert 
I think there is a bug in the line 195 in Utils6, where "true" makes the directories checking alway being true. 		

```
                  if (new File("/Library/Frameworks/CUDA.framework").exists() ||
					new File("/Developer/NVIDIA").exists() ||
					new File("/usr/local/cuda").exists() || true) {
```

**Comment by rbouckaert** [comment]
@walterxie  that indeed causes some redundant tests when CUDA is not installed, though these should not have been harmful.

However, testCudaStatusOnMac() is only triggered after javaVersionCheck() is called. chennyhui should have gotten a message saying that no Java 8 (or later) version is available and it should never have reached the testCudaStatusOnMac() call.

**Comment by walterxie** [comment]
The issue here is not testCudaStatusOnMac(), so that I change the title to avoid the confusion.

**Comment by walterxie** [comment]
The javaVersionCheck() worked and the error message dialog popped up:

`$ java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)
`

<img width="300" alt="screen shot 2019-01-07 at 12 27 39 pm" src="https://user-images.githubusercontent.com/5743014/50744075-31ae4b80-1284-11e9-8ddf-241ec4d24c77.png">

**Comment by rbouckaert** [comment]
This still appears to be a problem: when a JRE is installed, the default is still Java 6, and the CUDA check fails because it requires Java 8 to get started. Perhaps launching java with "-version" and parsing the output will be more robust.

**Comment by rbouckaert** [comment]
Since the solution of branch issue834 (see #834) does not require launching processes with Java any more, checking the java version with "java -version" is no longer required.
