### ISSUE TITLE
BEAST 2 parses charset differently to BEAST 1 

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#820]
As a user reported, BEAUti 2.5.1 did not parse `charset` correctly if using `,` (worked in BEAUti 1.10) to separate multiple sets of positions. For example,

`charset gene4_1_gene5_1_gene6_1=3113-4470\3, 4471-5366\3, 5367-6380\3;`

The reason is that BEAST 2's NEXUS parser uses white space. For example,

`charset gene4_1_gene5_1_gene6_1=3113-4470\3 4471-5366\3 5367-6380\3;`

**Comment by walterxie** [comment]
The code to replace `,` to ` ` is added and tested to maintain the same behaviour of BEAUti 1 for this issue.

**Comment by tgvaughan** [comment]
Take care: if this is true, the BEAST 1.10 behaviour is out of spec.  From Maddison, Swofford, and Maddison: "The description of a set of objects  (taxa, characters, trees) is a list. Elements in the list are separated by  whitespace."

As long as we read but don't produce such files, we're part of the solution.

**Comment by walterxie** [comment]
Thank you for the information. I read the (original paper)[https://academic.oup.com/sysbio/article/46/4/590/1629695]. In the section `CODONS Block`, there is an example using comma:

```
CODONPOSSET * coding=
     N:1-10,
     1:11-.\3,
     2:12-. \3, 
     3:13-A3;
```

I guess this is why BEAST 1 parser uses comma for codon positions.
