### ISSUE TITLE
Node.getMetaData(key) fails silently when key does not exist.

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#828]
The current implementation of `Node.getMetaData` is:

```java
    public Object getMetaData(final String pattern) {
        if (pattern.equals(TraitSet.DATE_TRAIT) ||
                pattern.equals(TraitSet.DATE_FORWARD_TRAIT) ||
                pattern.equals(TraitSet.DATE_BACKWARD_TRAIT)) {
            return height;
        } else {
            final Object d = metaData.get(pattern);
            if (d != null) return d;
        }
        return 0;
    }
```

Is there a good reason that this method returns 0 if the pattern isn't found?  I would have thought returning null would be the best option (i.e. the bare result of metaData.get()).  The problem with the current behaviour is that 0 is a perfectly reasonable value for the metadata to take, so it becomes impossible to distingish between a key with value 0 and a key that doesn't exist.

(Context: I have BDMM unit tests that should have been failing but were passing because of this.)

**Comment by alexeid** [comment]
I agree with this and I have been tripped up with this several times. I would *really* prefer it returned a null! I looked at changing it before, but I remember that I found some existing code couldn’t handle getting nulls from this method.

**Comment by rbouckaert** [comment]
There used to be a reason for this, but it clearly makes sense to change this behaviour asap.
