### ISSUE TITLE
bModelTest error, need help

### ISSUE THREAD

**Issue by fengyuchengdu** [CompEvol/beast2#830]
I could successfully run bModelTest on example dataset obtained from https://github.com/taming-the-beast/Substitution-model-averaging/raw/master/data/primate-mtDNA.nex, however when I ran that using my own data, it stopped after sample 0 and threw out "java.lang.ProcessImpl$ProcessPipeInputStream@6e0e048a", no matter what seed I used.

Could you please help me out? thanks much.

the entire screen log is shown below
Picked up _JAVA_OPTIONS: -Xms2g -Xmx26g
[/home/linuxbrew/.linuxbrew/Cellar/jdk/9.0.4/bin/java, -Xms8g, -Xms256m, -Djava.library.path=/home/ubuntu/lib:/home/ubuntu/data/fengyu_beast/modeltest:/usr/local/lib:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib, -cp, ::/home/ubuntu/.beast/2.5/BEASTLabs/lib/BEASTlabs.addon.jar:/home/ubuntu/.beast/2.5/BEAST/lib/beast.src.jar:/home/ubuntu/.beast/2.5/BEAST/lib/beast.jar:/home/ubuntu/.beast/2.5/BDSKY/lib/BDSSM.addon.jar:/home/ubuntu/.beast/2.5/bModelTest/lib/bModelTest.addon.jar, beast.app.beastapp.BeastMain, -seed, 12199766, -threads, 4, -beagle_double, -beagle_CPU, -overwrite, modeltest_good.xml]
Picked up _JAVA_OPTIONS: -Xms2g -Xmx26g

                        BEAST v2.5.1, 2002-2018
             Bayesian Evolutionary Analysis Sampling Trees
                       Designed and developed by
 Remco Bouckaert, Alexei J. Drummond, Andrew Rambaut & Marc A. Suchard
                                    
                     Department of Computer Science
                         University of Auckland
                        remco@cs.auckland.ac.nz
                        alexei@cs.auckland.ac.nz
                                    
                   Institute of Evolutionary Biology
                        University of Edinburgh
                           a.rambaut@ed.ac.uk
                                    
                    David Geffen School of Medicine
                 University of California, Los Angeles
                           msuchard@ucla.edu
                                    
                      Downloads, Help & Resources:
                           http://beast2.org/
                                    
  Source code distributed under the GNU Lesser General Public License:
                   http://github.com/CompEvol/beast2
                                    
                           BEAST developers:
   Alex Alekseyenko, Trevor Bedford, Erik Bloomquist, Joseph Heled, 
 Sebastian Hoehna, Denise Kuehnert, Philippe Lemey, Wai Lok Sibon Li, 
Gerton Lunter, Sidney Markowitz, Vladimir Minin, Michael Defoin Platel, 
          Oliver Pybus, Tim Vaughan, Chieh-Hsi Wu, Walter Xie
                                    
                               Thanks to:
          Roald Forsberg, Beth Shapiro and Korbinian Strimmer

Random number seed: 12199766

File: modeltest_good.xml seed: 12199766 threads: 4
Alignment(selected_ST11_for_beast_short)
  362 taxa
  5632871 sites
  21425 patterns

Setting transitions rate prior to log-normal(1, 1.25)
Filter 1-1408217
362 taxa
1408217 sites
8756 patterns
  Using BEAGLE version: 3.1.2 resource 0: CPU
    with instance flags:  PRECISION_DOUBLE COMPUTATION_SYNCH EIGEN_REAL SCALING_MANUAL SCALERS_RAW VECTOR_SSE THREADING_NONE PROCESSOR_CPU FRAMEWORK_CPU
  Ignoring ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 8756 unique site patterns.
  Using rescaling scheme : dynamic
Filter 1408218-2816434
362 taxa
1408217 sites
6225 patterns
  Using BEAGLE version: 3.1.2 resource 0: CPU
    with instance flags:  PRECISION_DOUBLE COMPUTATION_SYNCH EIGEN_REAL SCALING_MANUAL SCALERS_RAW VECTOR_SSE THREADING_NONE PROCESSOR_CPU FRAMEWORK_CPU
  Ignoring ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 6225 unique site patterns.
  Using rescaling scheme : dynamic
Filter 2816435-4224651
362 taxa
1408217 sites
4548 patterns
  Using BEAGLE version: 3.1.2 resource 0: CPU
    with instance flags:  PRECISION_DOUBLE COMPUTATION_SYNCH EIGEN_REAL SCALING_MANUAL SCALERS_RAW VECTOR_SSE THREADING_NONE PROCESSOR_CPU FRAMEWORK_CPU
  Ignoring ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 4548 unique site patterns.
  Using rescaling scheme : dynamic
Filter 4224652-5632871
362 taxa
1408220 sites
4216 patterns
  Using BEAGLE version: 3.1.2 resource 0: CPU
    with instance flags:  PRECISION_DOUBLE COMPUTATION_SYNCH EIGEN_REAL SCALING_MANUAL SCALERS_RAW VECTOR_SSE THREADING_NONE PROCESSOR_CPU FRAMEWORK_CPU
  Ignoring ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 4216 unique site patterns.
  Using rescaling scheme : dynamic
with (Math) { function f(BMT_ProportionInvariable, hasInvariableSites) { return BMT_ProportionInvariable * hasInvariableSites;}
}
with (Math) { function f(BMT_gammaShape, hasGammaRates) { return BMT_gammaShape * hasGammaRates;}
}
===============================================================================
Citations for this model:

Bouckaert RR, Heled J, Kuehnert D, Vaughan TG, Wu C-H, Xie D, Suchard MA,
  Rambaut A, Drummond AJ (2014) BEAST 2: A software platform for Bayesian
  evolutionary analysis. PLoS Computational Biology 10(4): e1003537

Bouckaert RR, Drummond AJ. bModelTest: Bayesian phylogenetic site model averaging and model comparison. BMC evolutionary biology. 2017 Dec;17(1):42.

===============================================================================
Start likelihood: -1.814301382099224E7 
Writing file modeltest.log
Writing file modeltest.trees
         Sample      posterior ESS(posterior)     likelihood          prior
              0 -1.814301382E7              N -1.814299292E7       -20.8955 --
java.lang.ProcessImpl$ProcessPipeInputStream@6e0e048a

**Comment by rbouckaert** [comment]
This is puzzling: can you still run the XML from the tutorial?

If so, could you make the XML available that causes this problem, so I can investigate what is going wrong (by for example emailing the file)?

**Comment by alexeid** [comment]
Something to do with 1.4 million sites and very small likelihoods I would guess...

**Comment by rbouckaert** [comment]
Initially, I thought this could indicate a memory issue: the alignment alone is just over 2GB, though it was run with java options -Xms2g -Xmx26g, which allows for 12 times the alignment size, and though `Alignment`, and `FilteredAlignment` do some duplication, I would not expect it to be 12 times. Also, there are just 21425 patterns, so partials for the `TreeLikelihood` do not take up a lot of space.

The initial state has a finite likelihood and the first state appears to be logged, which suggests there is no file issue, since the files appear to be successfully created.

The error message points to`java.lang.ProcessImpl$ProcessPipeInputStream`, which has me puzzled.

**Comment by rbouckaert** [comment]
The proposed solution in branch issue834 does away with launching processes, so any `ProcessImpl$ProcessPipeInputStream` issue should be solved that way.
