### ISSUE TITLE
BeastLauncher does not pass -Xssn to BeastMain

### ISSUE THREAD

**Issue by brj1** [CompEvol/beast2#831]
In the spirit of #784 I recently ran into an issue where I had to increase the thread stack size (-Xssn) to get beast2 to stop running out of stack space and subsequently crashing. Where the -Xmsn and -Xmsxn get pass through BeastLauncher when BeastMain is called, -Xssn does not.

I found a solution to my problem by running BeastMain directly, but it'd be nicer to just be able to run the bin/beast 'binary' instead.

**Comment by rbouckaert** [comment]
Good point. Should be fixed in the next release.
