### ISSUE TITLE
tutorial of heatmapmaker

### ISSUE THREAD

**Issue by carolynzy** [CompEvol/beast2#835]
I'm using HeatMapMaker with GEO-SPHERE package, beast version 2.5.1 and GEO_SPHERE version 1.2.0. 
I couldn't find instructions for these parameters in HeatMapMaker: Jitter, Repeat, Mask, clade, and Root only.
Do I missed something in the tutorial? It seems the software has been updated but the tutorial is not. 
I want to change the color range for the dots, which represents their age. How should I do that?
Many thanks for this wonderful tool! I really enjoyed using it very much.

**Comment by rbouckaert** [comment]
@carolynzy to find out what these items mean, you can hover over the field in the HeatMapMaker GUI, or from a terminal call applauncher HeatMapMaker -help, which shows (among other entries):
* jitter <integer>	jitter applied to dot locations (in pixels)
* mask <filename>	image file with a mask: dots will not be shown outside mask
* repeats <integer>	number of times a dot should be drawn
* rootOnly [true|false]	only draw root locations and ignore the rest
* clade 	Name of XML file containing a single TaxonSet in BEAST XML format. If specified, the location of the MRCA of a clade is used (and the rootonly flag is ignored).

Let me know if any of this is unclear.

There is no way to change the colour range other than to change the code at the moment -- will look into this.

**Comment by rbouckaert** [comment]
Since this is an issue for the Babel package, I opened an issue with that package here: https://github.com/rbouckaert/Babel/issues/9

**Comment by rbouckaert** [comment]
A feature was added to the HeatMapMaker to allow setting the start colour and range of colours, available in GEO_SPHERE v1.2.1.

The tutorial is now updated, available here:
https://github.com/BEAST2-Dev/beast-geo/releases/download/v1.2.0/phylogeography_s.pdf

Hope this fixes the issues you were running into. Let me know if you run into any further problems.

**Comment by 826187573** [comment]
Dear Sir,
I'm using HeatMapMaker with GEO-SPHERE package, beast version 2.5.1 and GEO_SPHERE version 1.2.0.
I input the Tree Set and Background, but it always wrong. It shows in attached.
Could you please sent me what you set in "HeartMapMaker Editor", your Tree Set and Background. I want to recurrent the Heart Map in the tutorial. Thank you very much.

Best wish
![微信截图_20190512162023](https://user-images.githubusercontent.com/44313460/57579733-cc3cc680-74d2-11e9-961b-4821c94a605a.png)

**Comment by rbouckaert** [comment]
There was an issue with HeartMapMaker that was fixed in a version later than 1.2.0. Can you upgrade GEO_SPHERE and let me know if the problem persists? Upgrading is easiest via BEAUti using the menu File/Manage packages, then select GEO-SPHERE in the list and click the "Install/upgrade" button.

**Comment by 826187573** [comment]
I upgrade to the lasted version 1.2.2, but the problem persists. I'm not sure if the problem is on my settings of "HeartMapMaker Editor".

**Comment by rbouckaert** [comment]
Thanks for the feedback -- can you try to run with minimal changes of the input value:
start with only the tree file, then (if that succeeds) add background image and other parameters. Please let me know whether the error persists.

**Comment by 826187573** [comment]
I just input the tree file, succeed. But when background image added, it shows the same error. It is my background image.
![Uploading tu.png…]()

**Comment by rbouckaert** [comment]
When I follow the link to the image, my browser (Firefox) says the image cannot be displayed because it contains errors. I suppose that is the source of the problem. Perhaps the image needs to be converted, e.g., using Image Magic, Gimp or photoshop.

**Comment by 826187573** [comment]
Yes, I tried another image, and it shows as follow. I don't know what the background image needs to be asked. 
It can output a png file, but the same as the background image.

Loading background image C:\Users\Administrator\Desktop\_20190514220417.png
No mask image
translation map size = 3
Parsing trees D:\master\beastﾳﾢￊￔ\geo\+BDSKYseril\2mcc.tree ...  done
Drawing dots...
|=========|=========|=========|=========|=========|=========|=========|=========|=========|=========|
done
Writing file heatmap.png done
Writing legend null\\legend.png  done in 1 seconds
All done

**Comment by rbouckaert** [comment]
There are a number of possible reasons for this:
* the tree file does not contain geographical data. If so, the image produced without using a background should be blank.
* an incorrect name for the metadata tag is used (`tag` input in the dialog), which should also give a blank image when no background image is used.
* if the image without background image is not blank, perhaps you should use more replicates (increase `repeats`) or disc size (`discSize` entry in the dialog) or decrease translucency (by increasing `translucency`).
Hope this helps, Remco

**Comment by 826187573** [comment]
Thank you so much! I have got a perfect heatmap.
