### ISSUE TITLE
OSX: CUDA warning but no CUDA installed

### ISSUE THREAD

**Issue by timkahlke** [CompEvol/beast2#836]
Hi,

I just tried to update BEAST from 2.4 to 3.x on my MAC laptop (OSX 10.11.6 El Capitan) but am getting the "Cuda installed, please remove" warning. Unfortunately, I don't have CUDA installed and never did. Also BEAST 2.4.x starts up nicely but none of the 3.x versions do. Any suggestions?

**Comment by rbouckaert** [comment]
This is probably due to a bug in v2.4 in detecting the java version being used. This should have been fixed now. Did you install the java JDK 8 (from [here](https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html))?

Can you try the latest version, v2.5.2?

**Comment by timkahlke** [comment]
Thanks Remco, updating Java fixed it.

**Comment by rbouckaert** [comment]
Great, thanks for confirming that it worked.
