### ISSUE TITLE
Can we add a flag to mark BEASTObjects as uncloneable?

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#840]
In BEAUti it is possible to select clone information from one partition to another.  For instance, in the tip dates panel, it is possible to set up tip dates for one tree and then copy those dates other trees.  This is tremendously useful when lots of partitions are involved.

The difficulty I'm having is that I am trying to compose a template for a model which places a prior on multiple trees (via a network).  The objects representing the network and the operators which act jointly on the network and the trees must be shared by all tree partitions.  This turned out to be delightfully easy to set up (drawing inspiration from the EBSP tree prior template).  However, when I attempt to clone tip dates between trees belonging to this set the `BeautiDoc.deepCopyPlugin()` method which takes care of this under the hood inadvertantly copies things other than just the tip dates: some of the previously-shared objects wind up being duplicated as well.

There are already provisions in this method for avoiding copying certain objects.  A set of "taboo" objects is built up by the following code:
```java
        Set<BEASTInterface> taboo = new HashSet<>();
        taboo.add(parent);
        // add state
        taboo.add(mcmc.startStateInput.get());
        // add likelihood and prior
        if (mcmc.posteriorInput.get() instanceof CompoundDistribution) {
            for (Distribution distr : ((CompoundDistribution) mcmc.posteriorInput.get()).pDistributions.get()) {
                if (distr instanceof CompoundDistribution) {
                    taboo.add(distr);
                }
            }
        }
        // add posterior
        taboo.add(mcmc.posteriorInput.get());
        // parent of operators
        taboo.add(mcmc);
        // add loggers
        taboo.addAll(mcmc.loggersInput.get());
        // add exception for *BEAST logger (perhaps need to be generalised?)
        if (doc.pluginmap.containsKey("SpeciesTreeLoggerX")) {
            taboo.add(doc.pluginmap.get("SpeciesTreeLoggerX"));
        }
// ... etc
```
It would be great if there were a way for package authors and beauti template developers to add arbitrary objects to this list.  Indeed, this is even suggested by the comment above the hard-coded *BEAST work-around.  (I've verified that adding the shared objects in my network model to this list completely solves my problem.)

I see two possibilities:

1. **Add an input to the BEASTObject class** that lets objects be specified as non-clonable at the instance level.  This would provide an easy solution to the *BEAST species tree logger problem without requiring a special species tree logger.  However it would mean that _every_ BEASTObject would have this input, which would result in lots of other ugliness.  (Off  the top of my head, beauti templates would need to explicitly supress these inputs, or beauti itself would have to be modified to do this.)

2. **Add a default method to BEASTInterface** that returns true if the object implementing the interface is cloneable (default) but can be overridden.  This would not immediately solve the *BEAST problem, but that could be addressed very easily by creating a logger that simply extends the existing logger but overrides this method.  No other changes would be necessary.

I would definitely choose the second option.

What do you all think?  (Or is it somehow potentially dangerous/messy to allow developers to add objects to this list?)

**Comment by alexeid** [comment]
2 looks good to me.

**Comment by rbouckaert** [comment]
I agree that option 2 looks like the better option.
