### ISSUE TITLE
"r" and "split" buttons are disappeared in BEAUti

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#843]
"r" and "split" buttons are disappeared in BEAUti 2.5.2.

Mac OS 10.14, Java 10.0.1.

<img width="400" alt="Screen Shot 2019-04-02 at 10 26 37 AM" src="https://user-images.githubusercontent.com/5743014/55440178-599f1800-5603-11e9-9c17-db252288914d.png">

An error message "Warning: corrupt classpath entry: " was found using the menu _Help->Messages_.

**Comment by walterxie** [comment]
I tested BEAUti using Java 8, it had the same problem: 

<img width="400" alt="Screen Shot 2019-04-03 at 11 32 47 AM" src="https://user-images.githubusercontent.com/5743014/55440538-71c36700-5604-11e9-822e-7471c7f518d7.png">

**Comment by walterxie** [comment]
But if I did not use `BeautiLauncher`, the problem disappeared (no error message):

<img width="400" alt="Screen Shot 2019-04-03 at 11 32 47 AM" src="https://user-images.githubusercontent.com/5743014/55440681-fdd58e80-5604-11e9-920d-b25cdcf05007.png">

**Comment by walterxie** [comment]
After an exhausting investigation, I find the `BeastLauncher.run()` works without loosing buttons, if I force the `classpath` using only pure `beast.jar`. Because my machine installed most of packages, I am not sure which package loaded in the `classpath` was causing the problem.

Can we just use `beast.jar` in `BeastLauncher.run()`'s `cmd`? The rest of packages and libs will be loaded by the BEAUti main afterwards anyway.

**Comment by rbouckaert** [comment]
@walterxie  If you can come up with a way to dynamically load jar files with Java 9 or newer that would solve many problems. The old way works fine with Java 8, but not with Java 9. The launch mechanism is a way around dynamically loading jar files.

**Comment by walterxie** [comment]
@rbouckaert 
It looks Java 9 made some changes to add jar to classpath at runtime:

https://stackoverflow.com/questions/48041764/add-jar-to-classpath-at-runtime-under-java-9

https://www.oracle.com/technetwork/java/javase/9-relnote-issues-3704069.html

But this will require a new development. Maybe, it will be considered as the feature of a new PackageManager using Module system (in a separated issue)?

For this issue only, I think my above simply solution could fix it. I can show you the detail on Monday if you are interested.

**Comment by walterxie** [comment]
As Remco advised, my simply solution will break the code specified to load jars after Java 9. This issue has to postpone after we could have a better solution to deal with this change from Java 9.

**Comment by tgvaughan** [comment]
What does the new launch mechanism have to do with disappearing buttons in the alignment panel?

**Comment by rbouckaert** [comment]
When starting from the beast.jar file directly, the button appear.

When starting through BeautiLauncher, the button disappear.

It may be due to some package interfering with BEAUti somehow: packages are not loaded when starting from beast.jar directly, but they are when using BeautiLauncher. 

@walterxie: which packages do you have installed.

**Comment by walterxie** [comment]
@rambaut about 30 packages. I will try if I could locate which one.

**Comment by walterxie** [comment]
Updating the codon substitution models package to [v1.1.2](https://github.com/BEAST2-Dev/codonsubstmodels/releases/tag/v1.1.2) will solve this problem.
