### ISSUE TITLE
Using Validate.OPTIONAL in Input declarations can lead to errors

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#845]
Intuitively, Validate.OPTIONAL should be a valid option to add, but for some reason any programmer using it is reprimanded with a confusing message (via initByName, called from test code, or XML parser). Removing Validate.OPTIONAL from the input declaration fixes the problem, but it would be nicer to have it as a viable option.

**Comment by tgvaughan** [comment]
I agree.

**Comment by rbouckaert** [comment]
Turns out only a menacing message was printed, but things worked as expected otherwise.
