### ISSUE TITLE
remove upper limit of bPopSizes in Bayesian Skyline

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#848]
As Alexei advised, it was wrong to make the default of `bPopSizes` in Bayesian Skyline having upper limit, because their values could be big numbers in a real analysis. User should define the prior.

**Comment by rbouckaert** [comment]
Were improper priors as defaults not frowned upon? Why change the lower bound?

**Comment by walterxie** [comment]
I do not think the effective population size smaller than 1 would make any sense.

**Comment by tgvaughan** [comment]
@walterxie Ne values below 1 **do** make sense.  Particularly as these are actually Ne*g values, i.e. inverse pairwise coalescence rates. Depending on the time scale chosen, these inverse rates can be arbitrarily small.
