### ISSUE TITLE
XMLProducer should ignore reserved names

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#849]
The `XMLProducer` currently produces XML that looks inconsistent to new developers. For example the `state` can contain `stateNode` elements as well as `parameter` elements (which then have a `name` attribute). `RealParameter` state nodes are treated the latter way, while `IntegerParameter` and `BooleanParameter` are treated the former way, e.g.,

	<parameter id="BMT_ProportionInvariable.s:tRNA-others" lower="0.0" name="stateNode" upper="1.0">0.1</parameter>
	<stateNode id="hasInvariableSites.s:tRNA-others" spec="parameter.IntegerParameter">1</stateNode>
	<stateNode id="hasGammaRates.s:tRNA-others" spec="parameter.IntegerParameter">1</stateNode>

The `XMLProducer` has a set of reserved names (`distribution`, `operator`,`input`,`data`,`log`,`state`,`sequence`,`tree` and `parameter`) that are treated specially, and do not require a `spec` element, but may require a `name` attribute instead (as in the example above).

I suggest we generate all XML the conventional way (i.e., always use `spec` attributes, even for reserved names). This will have as consequence that the state and other XML looks more consistent, but also means that each sequence will have a `spec` attribute.

The `XMLParser` can still be aware of reserved words and the associated classes for backward compatibility.

**Comment by alexeid** [comment]
Agree!
