### ISSUE TITLE
Error Parsing Input Tree: Around line 773 Number of taxa (366) is not equal to 'dimension' field (765) specified in 'taxa

### ISSUE THREAD

**Issue by Deyi-Wangg** [CompEvol/beast2#851]
Hi,
I wanna use TreeAnnotator.exe in Beast_v2.5.2_windows. But it failed with the following error.

"Processing 14002 trees from file after ignoring first 30% = 6000 trees.
Finished - Quit program to exit.
java.io.IOException: Around line 773
Number of taxa (366) is not equal to 'dimension' field (765) specified in 'taxa' block
	at beast.util.NexusParser.parseFile(Unknown Source)
	at beast.util.NexusParser.parseFile(Unknown Source)
	at beast.app.treeannotator.TreeAnnotator$FastTreeSet.<init>(Unknown Source)
	at beast.app.treeannotator.TreeAnnotator.<init>(Unknown Source)
	at beast.app.treeannotator.TreeAnnotator.main(Unknown Source)
Error Parsing Input Tree: Around line 773
Number of taxa (366) is not equal to 'dimension' field (765) specified in 'taxa' block"

Is there anyone who knows the reason?

Deyi

**Comment by rbouckaert** [comment]
TreeAnnotator appears to encounter a tree that only contains 366 taxa, while it is expecting 765 taxa. It may be that the file is corrupted. You might want to open the file in a text editor (like notepad) and have a look at line 733

How did you generate the tree file?

**Comment by rbouckaert** [comment]
@Deyi-Wangg were you able to identify the problem? If not, could you make the tree file available so I can investigate?

**Comment by Deyi-Wangg** [comment]
Dear Remco,

Sorry for my delayed reply.
I still can not figure out what's the problem with my trees. Please kindly
check my tree file.
I use TreeAnnotator v2.5.2 window. Here is the screenshot.

*Processing 5*
 tree1.trees
<https://drive.google.com/file/d/1CwTRHAgkaHKFPl2efiacNPYjLdZIhMRW/view?usp=drive_web>










*01 trees from file.Finished - Quit program to exit.java.io.IOException:
Around line 773Number of taxa (366) is not equal to 'dimension' field (765)
specified in 'taxa' block at beast.util.NexusParser.parseFile(Unknown
Source) at beast.util.NexusParser.parseFile(Unknown Source) at
beast.app.treeannotator.TreeAnnotator$FastTreeSet.<init>(Unknown Source) at
beast.app.treeannotator.TreeAnnotator.<init>(Unknown Source) at
beast.app.treeannotator.TreeAnnotator.main(Unknown Source)Error Parsing
Input Tree: Around line 773Number of taxa (366) is not equal to 'dimension'
field (765) specified in 'taxa' block*

Thanks in advance!

Kind regards,
Deyi


Remco Bouckaert <notifications@github.com> 于2019年6月10日周一 下午9:22写道：

**Comment by rbouckaert** [comment]
Dear Deyi, 

Thanks for the file, which was very helpful and made me realise that taxon names with spaces in them are not dealt with properly; only the part of the name before the space is output in the tree file, and because you have multiple taxa with the same starting name, the tree parser (used by TreeAnnotator) only recognises 366 unique names, while it expects 773, hence the error message.

Currently, the only way to deal with this is to replace spaces in taxon names with for example underscores and run the analysis again.

I put in a fix to the code, and ran TreeAnnotator on your file after editing it so that taxa names are no longer truncated in the taxa block, and this is the resulting [MCC tree](https://gist.github.com/rbouckaert/73a7899e95776f6963b586a1cbf0551d#file-tree1-tree). This fix should be available in v2.6.0, and we are working on that release right now (#858), which should be available in a few weeks.

Cheers,
Remco

**Comment by Deyi-Wangg** [comment]
Dear Remco,Thanks for your efforts! Looking forward to the new version!Cheers,Deyi------------------ Original ------------------From: Remco Bouckaert  <notifications@github.com>Date: Tue,Jun 11,2019 10:31 PMTo: CompEvol/beast2 <beast2@noreply.github.com>Cc: Deyi-Wangg <wangdeyi2018@gmail.com>, Mention <mention@noreply.github.com>Subject: Re: [CompEvol/beast2] Error Parsing Input Tree: Around line 773Number of taxa (366) is not equal to 'dimension' field (765) specified in'taxa (#851)Dear Deyi,
Thanks for the file, which was very helpful and made me realise that taxon names with spaces in them are not dealt with properly; only the part of the name before the space is output in the tree file, and because you have multiple taxa with the same starting name, the tree parser (used by TreeAnnotator) only recognises 366 unique names, while it expects 773, hence the error message.
Currently, the only way to deal with this is to replace spaces in taxon names with for example underscores and run the analysis again.
I put in a fix to the code, and ran TreeAnnotator on your file after editing it so that taxa names are no longer truncated in the taxa block, and this is the resulting MCC tree. This fix should be available in v2.6.0, and we are working on that release right now (#858), which should be available in a few weeks.
Cheers,
Remco

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/CompEvol/beast2/issues/851?email_source=notifications\u0026email_token=AKVD7YPIUOELHGF7PTRQITTP2ADRJA5CNFSM4HPXEPC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXONEWQ#issuecomment-501011034",
"url": "https://github.com/CompEvol/beast2/issues/851?email_source=notifications\u0026email_token=AKVD7YPIUOELHGF7PTRQITTP2ADRJA5CNFSM4HPXEPC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXONEWQ#issuecomment-501011034",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
