### ISSUE TITLE
Build Failing due to source level of PackageManger

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#855]
Since commit 1a3c860c95d43a3620da7b93dc7ed63d0378624e the ant build script fails with

```
    [javac] /root/beast2/src/beast/util/PackageManager.java:640: error: multi-catch statement is not supported in -source 1.6
    [javac] 		} catch (IOException | ClassCastException e) {
    [javac] 		                     ^
    [javac]   (use -source 7 or higher to enable multi-catch statement)
```

See the latest master build: https://travis-ci.org/CompEvol/beast2/builds/541486902.

**Comment by rbouckaert** [comment]
Good catch! I propose we switch to the package manager on branch issue834 shortly, and will fix it there as well.
