### ISSUE TITLE
MRCAPrior bounds incorrectly applied by RandomTree with date-forward trait.

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#856]
## Steps to reproduce:

1. Set up a dated tip analysis where tip dates are all 10, set using a TraitSet with typename="date-forward".

2. Place an MRCAPrior on the root node, setting lower and upper bounds (say -0.1 and +0.1).

3. Initialize the tree using RandomTree.

4. Run the analysis. (Example XML: [calibrationPriorIssue.xml.txt](https://github.com/CompEvol/beast2/files/3257862/calibrationPriorIssue.xml.txt))

## Expected result

Analysis should start, with the tree initialized to a height of 10.

## Observed result:

Analysis fails due to the MRCAPrior evaluating to -infinity.

## Additional comments

Opening a debugger reveals that with these MRCAPrior bounds the tree is initialized to a height of ~0.  This lies outside the prior when the date transformation is applied, as in this case the transformed bounds are ~10+/-0.1.  Conversely, setting the MRCAPrior bounds to 10+/-0.1 results in a tree with height ~10, but this again lies outside the transformed bounds which are now ~0+/-0.1.

Thus, the only way to apply such constraint priors seems to be to use a TraitSet with typename="date-backward".  I don't know enough about RandomTree to know whether this is also a problem for priors without hard boundaries.

(Sorry for the convoluted explanation, I found this super confusing.)

**Comment by rbouckaert** [comment]
I would not expect the analysis to start, given the tip dates are 10 and the calibration has bounds -0.1 and +0.1. I would expect the analysis to start if the bounds contain the target value, e.g., with bounds +9.9 and +10.1. The times in MRCAPriors should reflect actual times, not times offset by the most recent tip in the tree. It would be very confusing if it wasn't, since you need to know the tip ages to be able to specify an MRCAPrior.

Regardless, it is concerning that it works with "data-backward" but not with "date-forward".

**Comment by tgvaughan** [comment]
> I would not expect the analysis to start, given the tip dates are 10 and the calibration has bounds -0.1 and +0.1.
But the calibration is on the root node time, not the tips.  The forward-time of the root is 0.

**Comment by rbouckaert** [comment]
Sorry, I should have read more carefully -- the root node time should indeed be OK, but is not interpreted correctly.

The `SimpleRandomTree` class in the BEASTLabs package appears to suffer from the same defect.

On top of that, setting `rootHeight="10"` on `RandomTree` appears to give a starting tree of height 10, but does not satisfy the uniform prior. So, `RandomTree` certainly shows some unexpected behaviour.
