### ISSUE TITLE
Enhance @Param annotated c'tors

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#857]
To facilitate development of BEAST classes that do not rely on `Input/initAndValidate` construction, we already have constructors with `@Param` annotations, but these are quite limited. The following wish-list would make it much easier:

Primitives as Inputs, i.e., int, long, boolean, double, float, for example

    class MyClass {

	public MyClass(@Param("x","an integer input") int x) {
		this.x = x;
	}	

	public int getX() {return x;}
	public void setX(int x) {this.x = x;}

	int x;
    }

Array inputs of primitives

    class MyClass {
	public MyClass(@Param("x","an integer array input") int [] x) {
		...
	}

Array inputs of BEAST objects

Non-BEAST classes, for example String inputs:

    class MyClass {
	public MyClass(@Param("x","a String input") String x) {
		...

Allow inner classes to be serialisable to/from XML/JSON.

Allow multiple constructors to be annotated with the `@Param` annotation, and other c'tors without `@Param` annotations.

See for an elaborate example of such a class:
https://github.com/rbouckaert/xbeast/blob/master/src/test/xbeast/core/PrimitiveBeastObject.java

Allow 'id' and 'name' as input names.

Allow non-String default values by defining static methods called `default` + input name.

Allow classes not to have a default c'tor.

These are all implemented in the xbeast package already, so I suggest porting these back to beast2.

**Comment by rbouckaert** [comment]
The JSON Parser now requires all entries to have a spec element, and no longer uses the default spec values (similar to #849, but now for both JSONProducer and JSONParser). This means a major release is required for this to be released. In the light of changes required for launchers (#834) as implemented on branch issue834, this seems reasonable.

A blog post will appear shortly describing the practicalities of the changes for developers.

**Comment by rbouckaert** [comment]
56bdc7a  breaks BEAUti, so I created a branch issue857 to get this sorted out.

**Comment by rbouckaert** [comment]
By 4a3c1ce.

**Comment by tgvaughan** [comment]
@rbouckaert What was the reason behind the changes made to XMLParser as part of commit 56bdc7a above? Specifically it looks as though the around line 285 was changed back to roughly what it looked like before user-defined variables were added.  Was this intentional?  Also, the $(seed) subtitution is commented out, meaning that this no longer works in the latest release.  I suppose one can easily define this using user-defined variables, but this substitution is widely used so perhaps we can put it back in for the time being (and perhaps deprecate it)?

**Comment by rbouckaert** [comment]
Thanks for pointing that out -- it was not intended to be suppressed but was overlooked in the refactoring. Sorry for the inconvenience this caused. I restored it to the original behaviour. 

I don't think we want to deprecate the replacement of $(seed), since running it with the -D option requires synchronising both the `-seed` and `-D seed=` options, which would be error prone.

**Comment by tgvaughan** [comment]
I agree with not deprecating $(seed) - I was just suggesting this in the case that the change was intentional. :-)
