### ISSUE TITLE
TreeParser should warn all taxa in taxon set are in the newick tree

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#859]
Currently, a missing taxon in the tree when a taxonset is specified results in a `NullPointerException` in the `Tree.initAndValidate()` method, which is not quite hard to interpret. If the TreeParser could check and warn users before calling `Tree.initAndValidate()`, this situation will be easier to fix.

**Comment by tgvaughan** [comment]
Shouldn't this happen in Tree? That way the warning works for all tree
initializers, but just TreeParser.

**Comment by rbouckaert** [comment]
Good point -- will do.
