### ISSUE TITLE
Time running BEAST jobs

### ISSUE THREAD

**Issue by matiaskohler** [CompEvol/beast2#862]
Dear all,

I wish to know your experiences on time for running a BEAST job.

I have an 177 taxa and 80,000 pb alignment.
I'm interested in get divergence time estimations.

I'm using a GTR Gamma 0, relaxed clock log normal, Yule tree model process and a node age constraint with a normal distribution. To get good posterior distributions, I'm expecting to run MCMC for 500,000,000 length.

Lets say that I'll use Cipres resources to run this job (4 cpus?), how long it will take?

What can I do to optimize the process, when we have big alignments and high taxa sampling, and need to run big chain lengths?

Thanks for any comments.
Matias.

**Comment by rbouckaert** [comment]
Hi Matias,

In general it is hard to give advice, since the speed really depends on the data (not so much the length of the alignment, but the number of unique site patterns), the kind of analysis you run, and the mix of operator weights. You can do a short run to see how fast things run, and extrapolate from there.

You may consider using the calibrated Yule instead of the Yule prior to correct for the single age calibration, and it is recommended to use a log-normal distribution instead of a normal, since the normal distribution has a range that expands into the future, which is rather unrealistic.

Cipres has its own load balancing algorithm for BEAST jobs, but if you want to run it locally, there are some [performance suggestions](http://www.beast2.org/performance-suggestions/) on the beast2.org site.

Hope this helps,

Remco

PS This kind of question is more appropriate for the [beast-user list](https://groups.google.com/forum/#!forum/beast-users) -- this place is meant to be for reporting bugs and feature enhancement requests.

**Comment by matiaskohler** [comment]
Dear Remco, 

Thanks for your comments, they were really helpful.


Regarding the distribution, my age constraint is provided from
secondary data, and not a fossil age. 
Do you think it's still better to
use log-normal distribution in this case? 

Best,
Matias. 

PS. Sorry
for post here. I thought it would be better to post here instead the
beast-user-list. So I'll delete this 'issue report' from here later.


On 02/07/2019 18:28, Remco Bouckaert wrote: 

> Hi Matias, 
> 
> In
general it is hard to give advice, since the speed really depends on the
data (not so much the length of the alignment, but the number of unique
site patterns), the kind of analysis you run, and the mix of operator
weights. You can do a short run to see how fast things run, and
extrapolate from there. 
> 
> You may consider using the calibrated Yule
instead of the Yule prior to correct for the single age calibration, and
it is recommended to use a log-normal distribution instead of a normal,
since the normal distribution has a range that expands into the future,
which is rather unrealistic. 
> 
> Cipres has its own load balancing
algorithm for BEAST jobs, but if you want to run it locally, there are
some performance suggestions [1] on the beast2.org site. 
> 
> Hope this
helps, 
> 
> Remco 
> 
> PS This kind of question is more appropriate
for the beast-user list [2] -- this place is meant to be for reporting
bugs and feature enhancement requests. 
> 
> --
> You are receiving this
because you authored the thread.
> Reply to this email directly, view it
on GitHub [3], or mute the thread [4].
 

Links:
------
[1]
http://www.beast2.org/performance-suggestions/
[2]
https://groups.google.com/forum/#!forum/beast-users
[3]
https://github.com/CompEvol/beast2/issues/862?email_source=notifications&amp;email_token=AMNCNACGCNVBQ6YVK35WHJLP5PI7TA5CNFSM4H46FD42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZCXFDY#issuecomment-507867791
[4]

**Comment by rbouckaert** [comment]
Log normal is still preferred -- if you know the 95% HPD of the normal distribution, you can match this in BEAUti by using a log-normal with the same mean (make sure to check the "mean in real space" box) and a small standard deviation. The graph and information below it show you the corresponding 95% HPD. Just tune the standard deviation till they match.

Cheers, Remco

**Comment by matiaskohler** [comment]
Dear Remco, 

Ok, thanks for your valuable comments. 

If it is
possible, let me know your points for something: 

is it a rule that to
get reasonable ESS values for posterior, prior and substitution models,
I'll need to increase the MCMC chain length?
Like in the screenshot
below, I ran for 300 millions generations the MCMC, logging each 30.000
in the log file.

I do not know how to identify what are the issues in
my run, if it is just a length chain, or some priors not well fitted.


Sincerely,
Matias. 

On 02/07/2019 19:41, Remco Bouckaert wrote: 

>
Log normal is still preferred -- if you know the 95% HPD of the normal
distribution, you can match this in BEAUti by using a log-normal with
the same mean (make sure to check the "mean in real space" box) and a
small standard deviation. The graph and information below it show you
the corresponding 95% HPD. Just tune the standard deviation till they
match. 
> 
> Cheers, Remco 
> 
> --
> You are receiving this because you
authored the thread.
> Reply to this email directly, view it on GitHub
[1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/CompEvol/beast2/issues/862?email_source=notifications&amp;email_token=AMNCNACGXK7EUC5NN2NW3ELP5PRQ5A5CNFSM4H46FD42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZC26II#issuecomment-507883297
[2]

**Comment by rbouckaert** [comment]
This may be helpful: https://www.beast2.org/increasing-esss/
