### ISSUE TITLE
Add package sources from command line

### ISSUE THREAD

**Issue by J-Moravec** [CompEvol/beast2#867]
Is there a way to add package sources from the command line?

e.g.: https://github.com/rbouckaert/Babel

Unfortunately, `packagemanager` does not have this option. I have been also trying to find some file that the Beauti modifies when adding a new package source, but there seems to be nothing in `.beast`, the installation directory or linux `.config` or `.share` folders.

**Comment by rbouckaert** [comment]
Packages are supposed to come with source code included, e.g., when installing Babel, the file `Babel.src.jar` is included containing the source code used for building the package. Of course, you can use `git` to keep up to date with the latest source code for each of the packages. What else did you have in mind concretely that would differ from these two options?

**Comment by J-Moravec** [comment]
Ah, sorry, I could explain myself better.

What I mean is not source code, but access to packages not in default list/repository.

When I want to install `Babel` through package manager, I need to first add a new package repository/sources through Beauti gui, as written in Babel `README.md`:


> To install Babel through BEAUti, first add the extra repositories to the package manager like so:
> - start BEAUti, 
> - choose File/Manage packages
> - click ‘Package repositories’
> - Add URL https://raw.githubusercontent.com/CompEvol/CBAN/master/packages-extra.xml, click DONE

I have been trying to find a way to do this in the command line, i.e., by modifying some config file, but couldn't find where the package manager is storing these additional resources.

**Comment by rbouckaert** [comment]
I see -- the `beauti.properties` file in the package directory has an entry for `packages.url`, which contains the extra package URLs. If you set this to

```
packages.url=https\://raw.githubusercontent.com/CompEvol/CBAN/master/packages-extra.xml
```
(note the \ before :) the package manager will pick up packages from https://raw.githubusercontent.com/CompEvol/CBAN/master/packages-extra.xml.

**Comment by J-Moravec** [comment]
ah, I see it now, I have been looking at different version of beast libs. Solved then.

**Comment by rbouckaert** [comment]
I added a note to http://www.beast2.org/managing-packages/ to clarify this.
