### ISSUE TITLE
BEAUti fails to load template for "last" package in beauti.properties

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#868]
For instance, here is my beauti.properties file:

```
#Automatically-generated by BEAUti.
#
#Mon Jul 29 19:28:14 CEST 2019
package.path=\:/Users/vaughant/Library/Application Support/BEAST/2.6/BEAST/lib/beast.src.jar\:/Users/vaughant/Library/Application Support/BEAST/2.6/BEAST/lib/beast.jar\:/Users/vaughant/Library/Application Support/BEAST/2.6/BDSKY/lib/BDSSM.addon.jar
```

In my case the BEAUti templates for the BDSKY package fail to load.

It seems that this is due to an incompatibility between what is produced by `BeastLauncher::getPath` and what is expected by `BeautiDoc::processTemplate`.  The former returns a string bracketed by literal quotes ("), while the latter assumes that these quotes don't exist.  Since `getPath` is used in many other places I'm sure these quotes are important for something, so the fix should be to strip them in in `processTemplate`.

**Comment by rbouckaert** [comment]
Good spotting -- we might need a new release for this.
