### ISSUE TITLE
no manifest attribute in lib/beast.jar v2.6 

### ISSUE THREAD

**Issue by svanhal71** [CompEvol/beast2#891]
beast.jar fails to run on linux: have tried older versions these do work but unable to get GEO_SPHERE package to work in older version

**Comment by svanhal71** [comment]
Have found this solution

With v2.6.0 it is no longer possible to start BEAST with java -jar lib/beast.jar, but you can do this through java -jar lib/launcher.jar.

There is some more detail here: http://www.beast2.org/2019/09/26/command-line-tricks.html

Could I suggest you modify your README.txt file.

Thanks

**Comment by rbouckaert** [comment]
@svanhal71 sorry for the inconvenience. I realised the README was not up to date some time half way last year and updated it then. A new release (v2.6.2) is imminent, and it will be updated for that release.
