### ISSUE TITLE
MarkovChainDistribution should take a Function not a RealParameter

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#893]
Taking a RealParameter as input means the distribution can only take genuine parameters as input.  Replacing this with a Function type input would make it more flexible, allowing the distribution to be applied to transformed parameters.

In general, having _all_ Distributions take Functions instead of RealParameters would open up a lot of doors, as this allows them to be applied to the results of Slice, RPNCalculator, and others we haven't implemented/thought of yet.  Is there a downside to this??

**Comment by rbouckaert** [comment]
Good idea! Cannot think of any drawback.

**Comment by tgvaughan** [comment]
For some reason this breaks one of the BEAUti unit tests.  Reverting and reopening until I figure out why.

**Comment by tgvaughan** [comment]
It seems some indeterminacy has crept into the BEAUti tests somewhere, as they failed again even after rolling back that change. By rerunning them I was able to get them to pass.

Thus I'm reinstating the original commit (sorry about adding noise to the history). and again closing this issue.  Another issue should perhaps be opened re the stochastic test outcomes.

**Comment by rbouckaert** [comment]
I have observed some issues with indeterminancy with BEAUti tests before, and usually look at which test failed, run the test on my local machine, and (assuming it passes) keep an eye on it that test next time a travis is run. Not very elegant, but somewhat less work than pinning down what turns out to be a non-bug.

**Comment by tgvaughan** [comment]
Hey Remco.  I know I haven't regularly committed for a while, but from memory there was a period soon after I managed to get the tests passing in the Docker container that they seemed to remain fairly stable.  Unless I've just been really unlucky over the last 24hrs, this seems to have deteriorated..

**Comment by tgvaughan** [comment]
BTW I'm not _at all_ pointing fingers here!  It's also possible that this commit has somehow weirdly influenced the _rate_ of failure.  (Shudder.)

**Comment by rbouckaert** [comment]
Hi Tim, There must be something random going on, so certainly something to sort out at some stage -- once any covid work is not overwhelming all of us... Take care.
