### ISSUE TITLE
BEAST argument values from file

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#894]
With the `-D name=value` option, attribute values of the XML containing `$(name)` will be replaced by `value`, which is quite handy to parameterise the XML. However, command lines can become a bit unwieldy when there are many parameters, or values are quite large. Also, it is not possible to replace large sections, like all sequences.

I propose to introduce a `-DF` option that specifies a file in say JSON format that defines name/value pairs, which is what a JSON dictionary provides quite naturally, and allows for multiple lines for values. For example, like so:

```
{
"sequences":"
<sequence taxon='D4Brazi82'>            ATGCGATGCG        </sequence>
<sequence taxon='D4ElSal83'>            ATGCGATGCG        </sequence>
...
<sequence taxon='D4Thai84'>             GTGCGATGCG        </sequence>
";
"datetrait":"D4Brazi82  = 1982,
                D4ElSal83  = 1983,
...
                D4Thai84   = 1984"
}
```

where `...` means many more of the same. This would allow for using the same analysis with multiple data sets (or  multiple analyses with the same data set), which can be handy for well calibrated simulation studies or situations where the data set rapidly evolves.

**Comment by tgvaughan** [comment]
Hi Remco, just wondering - if you're going to go down this path, do you really want to introduce a whole other file?  Might it be better instead to simply allow people to define the variable values within the XML file itself, perhaps in a <variables> element within <beast>?  This way we don't get too far away from having the XML file be the single source of truth for an analysis.

**Comment by rbouckaert** [comment]
Hi Tim, The use case at the moment is for testing various sub-samples of a larger alignment, which means sequences, sample dates and taxa names change between different sub-samples. Setting up an analysis in BEAUti is rather error prone (due to human error :-(). How would defining variables in the XML help? What issues do you see in having the analyses and sub-sample specific information in separate files? Do you think there is another way to facilitate this case?

**Comment by tgvaughan** [comment]
Hey Remco, I suppose I am just conscious that the user-defined variables + command line option combination was already deviating from the original philosophy of guaranteeing that all of the settings required for an analysis remain with the XML file.  For longish command lines I keep them in the script I use to run the analysis, seeing as these are often situations where I'm iterating over lots of different combinations anyway.  But I've never had command lines that scale with the size of the dataset, as I guess yours would here!

Just in case you're interested, I have a handful of classes in feast that might help with your particular case:
- `AlignmentFromFasta` and `AlignmentFromNexus` (do what their names suggest)
- `TraitSetFromTaxonSet` (basically implements the equivalent of beauti's "guess" button)
I've been using these a _lot_ for setting up ncov analyses with tonnes of trees with linked phylodynamic parameters.  There's some brief documentation [in the feast readme](https://github.com/tgvaughan/feast#traitsetfromtaxonset).

BTW default XMLParser constructor doesn't initialize `parserDefinitions`.

**Comment by rbouckaert** [comment]
Hi Tim, I agree it is not ideal that data and inference engine are separated, but it is indeed just a natural expansion from allowing definitions through the `-D` option, and in urgent need at the moment with ncov data changing regularly. The feast classes look like a good alternative.

Thanks for that `XMLParser` fix. There still seems to be a problem with the `ExampleXmlParsingTest.test_ThatParameterisedXmlExamplesRuns()`, which crashes without trace, but runs without problems in Eclipse. Will investigate what is happening there.

**Comment by rbouckaert** [comment]
Passes all tests at least once due to a2f36ab

**Comment by rbouckaert** [comment]
Turns out that it is a bit hard to debug the XML or JSON file when there is an error. Having an extra option to save the XML with both XML and JSON merged, then quit will help find these errors quicker. Adding a `-DFout <file>` option to BEAST could do this.

**Comment by alexeid** [comment]
Maybe if -DFout was the default it would allay Tim’s concerns a little? You could even have beast stop itself and re-run on the generated XML file to be completely sure...

**Comment by rbouckaert** [comment]
Good idea. Perhaps requiring `-DFout` if `-DF` is used, or even have as default `-DFout $(filebase).out.xml` if `-DF` is used, but `-DFout` not specified. 
Lately, I found it quite handy to have the `-DF` option and running non-stop. So, perhaps we can do without the stop-option.

**Comment by alexeid** [comment]
I mean just that beast generates the new XML before actually doing the analysis (i.e. essentially runs in a command-line beauti mode first), then re-runs itself on the new XML, to ensure that the XML and log and trees files always go together… but yeah, anything along those lines sounds good to me.

**Comment by rbouckaert** [comment]
Fixed by  13945fd

**Comment by rbouckaert** [comment]
The behaviour for when using `-D` has changed: the XMLParser will write a file, even if the `-DF` option has not been used, but the `-D` option has. Writing a file when `-DF` option was used should be default (presumably a lot of the XML will be replaced), but a single `-D` option should not result in writing a file, unless the `-DFout` option is used.

**Comment by rbouckaert** [comment]
Using `-DF` option with `-resume` currently results in attempting to write the XML file (again), so the `XMLParser` asks 

```
Trying to write file outFile.xml but the file already exists (perhaps use the -overwrite flag
Overwrite (Y=yes/N=no/A=overwrite all)?:
```
which changes the file mode to overwrite on answer `A` and exits on `N`. Default behaviour should be not to attempt to write the file again on resuming, unless a `-DFout` option is used explicitly. Also, on resume the file mode should not be set to `overwrite`.
