### ISSUE TITLE
BEAUti import/load file dialog don't show hidden folders (linux)

### ISSUE THREAD

**Issue by papok** [CompEvol/beast2#901]
I started to follow the continuous phylogeography tutorial. The tutorial instructs (in linux) to import an alignment file from a subfolder of .beast/ which is a hidden folder and don't show among home/ items. A couple of words in the tutorial on how to open the hidden folder ("to access the hidden folder type .beast on the file field and press enter") would suffice.

**Comment by tgvaughan** [comment]
Thanks @Papok.  You can also choose File->"Select working dir"->BEAST, which was added to solve precisely this sort of problem.  This might be a better suggestion to add to the tutorial, as it would simplify the existing text.
