### ISSUE TITLE
Parametric prior graph gets clipped

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#903]
As reported in [this thread](https://groups.google.com/forum/#!topic/beast-users/y0lhocLMRxg), on a Windows Surface machine in BEAUti the parametric prior graph gets clipped in the priors panel, making it impossible to see the 95% and 97.5% quantiles.

![like so](https://17404302257233382898.googlegroups.com/attach/5649838e29ed4/priors.png?part=0.1.2&view=1&vt=ANaJVrE0_KhSR6Fj0oV8pmZkkirDAmIZRvQj03NAQc81TJKToYHcM4KrKh4QMn-9EyvvstlagF7U1W_Bas8iqoZRbRE2wXfet70y4S0wvxCaIlLPe_9HygM)

**Comment by rbouckaert** [comment]
Note that Justin also reported that "it also may be my computer, as this happened with Tracer and some other software like in Geneious", which suggests this may be a hard one to reproduce.

**Comment by alexeid** [comment]
Can you put the whole contents of the tab into a JScrollPane that only have a horizontal scrollbar when necessary? It looks like a hi-res screen auto-font-size problem perhaps making everything else too big? 

Another observation: The drop-down with “Log Normal” in it looks really big. Is there some funky long name in that list?

**Comment by rbouckaert** [comment]
Yes, adding scroll pane could solve the problem. The long text may be because Justin is zoomed in a bit too much, which may also explain the missing quantiles. I'll ask him to see what happens when he zooms out.

**Comment by rbouckaert** [comment]
Turned out to be high res screen scaling issue that was overlooked. Fixed by 2b765e2.
