### ISSUE TITLE
Can't access the BEAST 2.6.2 manage packages

### ISSUE THREAD

**Issue by starsareintherose** [CompEvol/beast2#910]
Report:
OS: Windows10
Error reading the following package repository URLs: https://raw.githubusercontent.com/CompEvol/CBAN/master/packages2.6.xml
Could not get an internet connection.
The BEAST Package Manager needs internet access in order to list available packages and download them for installation. Possibly, some software (like security software, or a firewall) blocks the BEAST Package Manager.
If so, you need to reconfigure such software to allow access.
Download of file https://raw.githubusercontent.com/CompEvoI/CBAN/master/packages2.6.xml timed out.
Perhaps this is due to lack of internet accessor some security settings not allowing internet access.

Problem:
I close the security software or VPN, but this software still report this eorror

**Comment by tgvaughan** [comment]
I suspect this is still some kind of network issue.  Perhaps try opening the repository URL "https://raw.githubusercontent.com/CompEvol/CBAN/master/packages2.6.xml" using a web browser (or curl) from the computer with the problem.

Just an aside: did you type in the second URL in your issue above by hand?  I'm asking because the final "l" in CompEvol has been replaced with an "I" (impossible to distinguish with github's default sans font,  but the first is an "Ell" while the second is an "Eye").  If the above was copied directly from the error output, I'd be very curious about how this happened.  I've checked the source, and there's no misspelling there.

**Comment by tgvaughan** [comment]
Reopening, as it seems the above commit referenced the wrong issue.

**Comment by starsareintherose** [comment]
> I suspect this is still some kind of network issue. Perhaps try opening the repository URL "https://raw.githubusercontent.com/CompEvol/CBAN/master/packages2.6.xml" using a web browser (or curl) from the computer with the problem.
> 
> Just an aside: did you type in the second URL in your issue above by hand? I'm asking because the final "l" in CompEvol has been replaced with an "I" (impossible to distinguish with github's default sans font, but the first is an "Ell" while the second is an "Eye"). If the above was copied directly from the error output, I'd be very curious about how this happened. I've checked the source, and there's no misspelling there.

Thanks. The mistaken-spelling is the mistakes of OCR. I use OCR to get the report. And I can get access to the packages2.6.xml. However, I still can't get access to the function. Also, I try to install it by hands, following the guide (https://www.beast2.org/managing-packages/) Install by hand section, but I only found file/setting work dir/VSS new to BEAUti and I still can't access to the manage packages function.

**Comment by hk20013106** [comment]
same issue here. Can access https://raw.githubusercontent.com/CompEvol/CBAN/master/packages2.6.xml using a web browser. But cannot read in BEAUTI. Turning on/off  VPN/firewall does not solve the problem.

**Comment by starsareintherose** [comment]
At the beginning of this year, I start to use ArchLinux, it is solved.

**Comment by tgvaughan** [comment]
@hk20013106 We need more information, otherwise we can't replicate the problem.  What OS are you using?  What is the exact error you are seeing?

**Comment by hk20013106** [comment]
@tgvaughan  Thank you very much for replying. 
OS: Windows10 64
BEAUTI: I tried versions 2.6, 2.5, 2.4
My location: China

Error message: exactly the same as mentioned by @starsareintherose 

> Error reading the following package repository URLs: https://raw.githubusercontent.com/CompEvol/CBAN/master/packages2.6.xml
>
> Could not get an internet connection.
> The BEAST Package Manager needs internet access in order to list available packages and download them for installation. Possibly, some software (like security software, or a firewall) blocks the BEAST Package Manager.
> If so, you need to reconfigure such software to allow access.
> Download of file > https://raw.githubusercontent.com/CompEvoI/CBAN/master/packages2.6.xml timed out.
> Perhaps this is due to lack of internet access or some security settings not allowing internet access.

![beauti no connection](https://user-images.githubusercontent.com/5851110/145961523-baf90e8d-1c7b-4940-ba63-924f404d3a9a.png)


I saw information on this webpage (https://www.beast2.org/managing-packages/), but I haven't tried this out. I assume this could solve the problem.

**Comment by zhangchicool** [comment]
I cannot access GitHub most of the time, including github.com and githubusercontent.com, from mainland China. I remember I have seen this error multiple times when I tried to install a package. The workaround for me is to use an VPN. I use macOS ver.12 and Beast 2.6.  So I agree with Tim, it is likely a network issue :(

**Comment by tgvaughan** [comment]
@zhangchicool Thanks Chi, and that's sad to hear. :( @hk20013106 mentioned that they'd tried using a VPN, but is it possible that the java URL fetching API is somehow not using the VPN?

In any case, I think the most robust solution here would be to install the package(s) by hand as detailed at the end of this page: https://www.beast2.org/managing-packages/.

This is another reason that it'd be nice to move package hosting away from github at some point.
