### ISSUE TITLE
Provide ability for any parameter to have user-specified unique names (keys) for each of its dimensions

### ISSUE THREAD

**Issue by alexeid** [CompEvol/beast2#913]
The names would be unique only within the scope of the parameter.

Parameter interface would get three default methods:

String getKey(int i);
T getValue(String key);
String[] getKeys();

The default implementation would make the key for dimension i be the string representation of i.

Then Parameter.Base could have a new (optional input) called "keys" which would be a space-delimited list of keys of the same length as the number of dimensions of the parameter, and would override these three methods to provide user-specified keys when provided while using the default behaviour otherwise.

Logging behaviour would use getID() for single dimension parameters and getID() + "." + getKey(i) for the i'th dimension otherwise.

**Comment by rbouckaert** [comment]
Multidimensional parameters without keys are now numbered from 0 instead of 1, which is the v2.6 behaviour, which makes it confusing to compare log files of different versions. I suggest to start from 1 to keep consistency.

**Comment by alexeid** [comment]
Zero-based indexing is the standard for Python, Java, C, C++ et cetera. It is also the standard for mathematical notations. The design goal was a default of zero-based indexing. It is easy to override it explicitly with the keys attribute. Please don't change the original developer's intention without discussion.

**Comment by alexeid** [comment]
Closed with 93e82f5.

**Comment by rbouckaert** [comment]
Perhaps you missed my comment -- the one reopening the issue?

Also, we discussed this in person last week, where we concluded it was rather arbitrary whether it is zero or one based. Given the current default behaviour is one based, I assumed you had no objections.

As you say, it is easy to change the XML, so why make a big deal out of this.

Perhaps you should consider branching/forking, which has the benefit of not having to deal with current default behaviour, backwards compatibility, dependent packages or existing junit tests.

**Comment by alexeid** [comment]
You can branch if you want to keep an old version. The whole point is to fix all the things that have been overbearingly and conservatively maintained. Otherwise the software becomes a dinosaur because of excessive conservatism. Backwards compatibility has been used as an excuse for stagnation for a long time. I am taking an opportunity to make changes now.
