### ISSUE TITLE
Trait "age" bug in Node

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#942]
In the `Node` class, both `setMetaData(...)` and `getMetaData()` do not handle `TraitSet.AGE_TRAIT` "age", so when using keyword "age", the variable `height` of this node will not be set/get correctly. 

It makes some packages sampling wrong heights, for example MASCOT.

The attached XML (it has to change to .txt to upload successfully) modified from https://taming-the-beast.org/tutorials/Mascot-Tutorial/ can reproduce the problem, where the date traits are properly changed to ages. The result of this XML will have very different "TreeHeight" and "clockRate" comparing to the original XML in the tutorial.

[H3N2age.xml.txt](https://github.com/CompEvol/beast2/files/5626761/H3N2age.xml.txt)

However, if the `traitname="age"` is changed to `traitname="date-backward"`, then everything goes back to normal.

**Comment by walterxie** [comment]
I suggest to create a static function `public static boolean isDateTrait(String traitName)` in the `TraitSet`, and replace every places using `if then` to use this function instead.

```
public static boolean isDateTrait(String traitName) {
       return DATE_TRAIT.equals(traitName) || 
                  DATE_FORWARD_TRAIT.equals(traitName) || 
                  DATE_BACKWARD_TRAIT.equals(traitName) || 
                  AGE_TRAIT.equals(traitName);
} 
```

**Comment by tgvaughan** [comment]
Hi Walter, I think I'm misunderstanding something.  Why is this a bug?  I don't recall "age" being a valid trait name for tip dates.  Is it used somewhere else in BEAST?  The original MASCOT tutorial XML is fine, isn't it?

**Comment by walterxie** [comment]
Hi Tim, this comes from Alexei's idea only using "age" in the tips in a different software LPhy. The complexity of metadata regarding to dates is handled as preprocessing. So we convert LPhy scripts in a BEAST XML, the "age" will be used as the design.
I understand in the BEAST convention "age" is reserved for fossil data only, even though you could convert "dates" into "ages" in a correct way and apply to virus data. But the argument here is not about the convention. It is about the bug in the code.
