### ISSUE TITLE
Pacakge manager fails on packages > 16MB

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#958]
It downloads package files up to 16MB due to  https://github.com/CompEvol/beast2/blob/1dee831dcd2607f6d17f418a9d9d84f075a51e67/src/beast/util/PackageManager.java#L506

where the 2<<24=16MB limits the size of the package file download. Updating this to 2<<26=64MB should be enough for everyone :-), but a more permanent solution would be useful.

**Comment by alexeid** [comment]
Why not increase to Long.MAX_VALUE? 64MB is still pretty small these days.

**Comment by alexeid** [comment]
Or at least test if the number of bytes read was the maximum, so that an error can be reported when the file is truncated?

**Comment by rbouckaert** [comment]
Yes, Long.MAX_VALUE appears to work just fine, and keeps the code simple.
