### ISSUE TITLE
LogCombiner GUI Produces No Output

### ISSUE THREAD

**Issue by sckieran** [CompEvol/beast2#967]
I'm combining three tree files in LogCombiner for MacOS. Used to work fine, since the update (or at least, sometime in the last week), it no longer produces any output (or error logs). It seems like the bugfix in the update means it can now print to stdout if no -o is attached, presumably when run from the command line, but through the GUI it doesn't seem to work to save any output file regardless of name/directory. I've tried a few tree files, including ones that I know are good, so I assume it's just an issue writing the output, or maybe me being a doughhead.

Edit: works from the command line.

**Comment by tgvaughan** [comment]
Hi @sckieran, thanks for bringing this up.  Indeed it seems that the solution to #962 had the side effect you note.
