### ISSUE TITLE
Nexus parser not generalized for new data types

### ISSUE THREAD

**Issue by kche309** [CompEvol/beast2#972]
The Alignment class has a general method `findDataTypes()` to check data types using the BEASTClassLoader.
The NexusParser class `parseDataBlock(final BufferedReader fin)` has hard coded data type checking inside if-else statements. 

Could we refactor the NexusParser, so when new data types are implemented these can be added automatically?

https://github.com/CompEvol/beast2/blob/4d95f0095d20a6999d2757299c629bfbbf14b94b/src/beast/evolution/alignment/Alignment.java#L67

https://github.com/CompEvol/beast2/blob/4d95f0095d20a6999d2757299c629bfbbf14b94b/src/beast/util/NexusParser.java#L751

It looks like the key parts are setting alignment.dataTypeInput to the correct DataType and totalCount for the number of states.
```
// binary data
alignment.dataTypeInput.setValue("binary", alignment);
totalCount = 2;
```

**Comment by kche309** [comment]
@alexeid Your changes look good to me.

**Comment by rbouckaert** [comment]
@alexeid Checked and it looks all fine to me.
