### ISSUE TITLE
File error: dr.app.tools.TreeAnnotator 

### ISSUE THREAD

**Issue by mjnetherland19** [CompEvol/beast2#980]
Hello,

I have cloned the most recent repository of BEAST2 and am running into the error in the attached picture. I have read that dr.app.tools.TreeAnnotator was associated with the first BEAST. I am confused as to why it is asked for in BEAST2. I've also included a picture of the first lines printed after running 'treeannotator', which references BEAST v1.8.4, if that is helpful in understanding the error. I would appreciate any insight you have.

Thank you for your time.

![treeannotatorError](https://user-images.githubusercontent.com/66214214/124048973-82323a00-d9e5-11eb-8989-2b11f54c0001.JPG)
![treeAnBegin](https://user-images.githubusercontent.com/66214214/124049083-bdcd0400-d9e5-11eb-9330-fe3bff3d1a40.JPG)

**Comment by rbouckaert** [comment]
@mjnetherland19 There is indeed no "dr" package in BEAST 2, so perhaps your path was set such that it picks up treeannotator from BEAST 1 before that of BEAST 2. Maybe you can include the whole (or part of the) path when starting treeannotator or beast and see whether the problem persists?

**Comment by mjnetherland19** [comment]
Your suggestion worked. Thank you!
