### ISSUE TITLE
RandomTree MRCA prior calibration error

### ISSUE THREAD

**Issue by brj1** [CompEvol/beast2#997]
If you use nonzero offsets in your date prior in a MRCAPrior with `tipsonly=false` then the calibrations will be incorrectly calculated. See the lines below:

https://github.com/CompEvol/beast2/blob/5a9ffcd1b1e177c027cc9c3b34df7581b41c902a/src/beast/evolution/tree/RandomTree.java#L237-L238

The inverseCumulativeProbability() function already takes the offset into account so in the the code above the offset will be added twice resulting in incorrect bounds.  The lines should be the following:

```Java
double tLow = distr.inverseCumulativeProbability(0.0); 
double tHi = distr.inverseCumulativeProbability(1.0); 
```

**Comment by rbouckaert** [comment]
Well spotted! Thanks for pointing that out. It may explain why the SimpleRandomTree from the BEASTLabs package has always been more robust than RandomTree.
